### ISSUE TITLE
 WebAssembly.compileStreaming() documentation does not mention a compelling use case

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1010]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1484557

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compileStreaming

This page says:
 > This function is useful if it is necessary to a compile a module before it can be instantiated

But it does not explain in what case this would be necessary. And the example given on the page is one where instantiateStreaming would be more appropriate - it's not a case where "it is necessary to a compile a module before it can be instantiated".

Could you add an example of a case where compileStreaming is preferred over instantiateStreaming?

Is it useful when a WebAssembly module is used on multiple threads? E.g. I could envision one thread calling compileStreaming to compile the module, and then the module could be passed to a pool of worker threads, each of which calls new WebAssembly.Instance(module, imports) to create an instance.

**Comment by mknet** [comment]
Hello @chrisdavidmills,

from my perspective this issue is not yet solved but closed anyway.
Actually, I (still) do miss a better example to make the use case (more) clear.

Did I miss something?
Could you provide me more info to understand you latest view on this issue and maybe the use case of `compileStreaming`as well?

Many thanks in advance - take care
Marcel
