### ISSUE TITLE
MDN Samples Server is down

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/sprints#1017]
Trying to&nbsp;connect to&nbsp;[mdn&#x2011;samples.moz.works](https://mdn-samples.moz.works/) results in&nbsp;`NSURLErrorDomain` and&nbsp;querying DNS&nbsp;resolvers for&nbsp;it results in&nbsp;no&nbsp;`A` or&nbsp;`AAAA` records.

---

I&nbsp;originally wanted to&nbsp;open an&nbsp;issue about improving mobile support for&nbsp;the&nbsp;landing page (https://github.com/mdn/samples-server/pull/59), but&nbsp;this is&nbsp;much more serious.

**Comment by a2sheppy** [comment]
So, the mdn-samples server is not part of the MDN dev team's purview; it's mine. It is not available through `moz.works` at all. I will investigate this, though it is not super important because we're actually in the process of probably phasing this out and just using things like Glitch instead.

I still personally feel that we should have something like this managed by Mozilla to run samples like this on, but it's been incredibly fragile. Events outside my control tend to bring it offline and despite being configured to automatically restore itself, it doesn't come back online on its own, and I don't get any kind of notice that it's down.

**Comment by a2sheppy** [comment]
OK, just a quick status update... the problem is indeed that the domain name has gone away. I am working to get it restored. Then we will have to check into the certificate; the one it currently has has expired, but IIRC a CNAME trick was used to map it to the same cert used by other MDN sites, so hopefully fixing it won't be hard once the name is back in place.

**Comment by a2sheppy** [comment]
This is fixed.
