### ISSUE TITLE
Express Tutorial Part 3, cannot create a mlab account

### ISSUE THREAD

**Issue by CODevOp** [mdn/sprints#1021]
# Request type
- [ ] New documentation
-  Correction or update

## Page to change
If this request relates to an existing article, please give its URL: 
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#Setting_up_the_MongoDB_database

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*
The article Express Tutorial Part 3: Using a Database (with Mongoose) uses mlab as the online cloud provider for the exercise. MongoDb has purcahsed mLab and is migrating user to MongoDb Atlas cloud. This article is now out of date because new users to mLab cannot create a new account. In addition, the populatedb.js file will need to be updated to handle the new mongodb+srv:// protocol

I, @escattone DevOp, will gladly make this change to convert the article over to MogoDb Atlas or any other MDN approved cloud service. 

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by hamishwillee** [comment]
> DevOp, will gladly make this change to convert the article over to MogoDb Atlas or any other MDN approved cloud service.

@CODevOp You're absolutely right - and your offer to help update to another service is gratefully accepted. 

mLab was selected because it was very simple to set up, and free for users for this size of database. If MongoDb Altas has a similar free tier (?) and is accessed similarly then happy to use that. Is there any compelling alternative?

I'm going to be working through the tutorial from beginning to end over the coming months and updating. If you don't get around to updating before I get to part 3 I'll help with that too.

Thanks again.

**Comment by CODevOp** [comment]
@hamishwillee, 
I explored Compose, ScaleGrid, MongoDb Atlas and ObjectRocket. ScaledGrid is the easiest and requires fewer changes to the overall page. The service is free for 30 days. 

MongoDB Atlas is also pretty easy but requires a few more steps and requires other code changes.  Atlas has a free tier with no time limit.

Both Compose and ObjectRocket require the setup of billing information. Based on the requirements in your reply we should go forward with ScaleGrid. 

Thanks, 
Bret

**Comment by hamishwillee** [comment]
Hi Bret, 

I think Altas sounds better even with the additional steps and code changes. Two reasons:
- 30 days is not a lot for someone getting started and familiar with a system.
- Next time I update these docs I don't want to have to purchase a ScaledGrid license in order to test the setup.

Make sense?

**Comment by CODevOp** [comment]
I have started making the changes and think I need your help. I thought I was saving a draft and actually published my changes. I went forwarded and edited the database creation instructions but cannot add the images.

**Comment by hamishwillee** [comment]
Hi Bret,

Awesome, thank you. Did you "finish" (other than the images)? If so, I can go through this in the afternoon and add the images. 

So what is the problem stopping you? If it is "working out how", basically you edit the page, and at the bottom you can upload images. Once uploaded, you can then select the image and add next time you do a page edit. Make sense?

Cheers
Hamish

**Comment by CODevOp** [comment]
Hello Hamish,

I did not finish there are some more references and explanations I need to fix. I can finish those tomorrow, proof read and add my images. I did not know the upload button was at the bottom.

I did not realize the edit form was auto saving drafts so I hit save. I now know it does not warn you and the document is published. I will rely on the auto save going forward.

Thanks for you help,
Bret

**Comment by hamishwillee** [comment]
Hi Bret,
All good - a learning experience that harms no one :-). I've run through the instructions and they work, though of course will be better when you have added images (did minor reference fixups). The _populatedb_ script (near the end) doesn't work without disabling the check on the URL format. I'll fix that up in the source code in the coming week(s).

**Comment by hamishwillee** [comment]
Hi Bret,

I updated https://github.com/mdn/express-locallibrary-tutorial to the latest version generated by express generator (docs are all updated in line with that). Also change the URL to point to my default mongoDB Atlas account, so it will all work out of the box.

One thing that came of this, that I would like you to include in chapter 3 if possible, is that to connect to mongoDB you need to whitelist the IP. Because in production we don't necessarily know the IP instead we select "All Any IP" when we add the whitelist, which sets the value to 0.0.0.0/0

**Comment by CODevOp** [comment]
Hello Hamish,

I have completed all changes to replaced mLab with MongoDB Atlas. Thank you for your help. Let me know what you think or if you have any guidance about the images or changes. 

The last step is to update populatedb.js on https://github.com/mdn/express-locallibrary-tutorial. I am looking for guidance now to clone, code and submit a pull request.

**Comment by hamishwillee** [comment]
Hi Bret,

Thanks for that. I hope to have a look at the images/page updates over the week and I will get back to you.

> The last step is to update populatedb.js on https://github.com/mdn/express-locallibrary-tutorial. I am looking for guidance now to clone, code and submit a pull request.

No need, that is part of what I did yesterday :-)

But should you need to post a change in future, this is a traditional github process - fork the repository, clone and fix code, push a branch with fixes to your fork, submit PR from your fork back to master.

Cheers
Hamish

**Comment by CODevOp** [comment]
Hello Hamish,

I have update chapter 3 to use 0.0.0.0/0 instead of use my local IP. I have also included a best practice disclaimer.

**Comment by hamishwillee** [comment]
Hi Bret, 

Looks great! I've made some minor mods to my taste, but this all done IMO. 

@chrisdavidmills - Can you please mark this as closed. The MDN text updates were mostly done by @CODevOp. I have updated and tested the code and the rest of the example all the way through with latest versions of all dependencies and this new backend database supplier.

Thanks again Bret - really appreciate your work in helping keep this tutorial current!

**Comment by chrisdavidmills** [comment]
Sure thing; closing. 

Thanks @CODevOp !
