### ISSUE TITLE
Update/Improve "What is a domain name?"

### ISSUE THREAD

**Issue by rachelnnoli** [mdn/sprints#1061]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

As a person new to front-end web development, I have read several dozen MDN web docs. They've all been clear in description, well-written, and built on knowledge I learned in other documents. I've been impressed! However, the document titled "What is a domain name?" is not nearly as helpful and stands out to me from past readings. The information is not precise, there are spelling and grammar errors, and I still have questions that are unanswered. 

This is true particularly for the "Deeper Dive" section -- for example, 

- Why do TLDs require strict criteria? 
- What are the general requirements by TLDs? 
- This is not clear: "When controlling the "upper" part of a domain name (e.g. mozilla.org), one can create other domain names (sometimes called "subdomains") (e.g. developer.mozilla.org)." 
- Why can't domain names be bought? 
- How does a local DNS database connect to top-level DNS servers? (Or do the top-level servers connect to the local DNS databases?) The writer's comment about "propagation time" is also confusing in this section's note. I don't understand what propagation is, nor how it relates (or doesn't relate) to this "wait time."

I would like to learn more on domain names and can certainly do more research to answer my existing questions. But I do hope some of these issues are resolved.

Thank you!

**Comment by a2sheppy** [comment]
URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_domain_name

**Comment by chrisdavidmills** [comment]
I've gone through this, improved the article, and answered some of your questions. In particular:

> Why do TLDs require strict criteria?

this is mainly so their purpose is clear. I've stated this and add more examples to that particular bullet

> What are the general requirements by TLDs?

I'm assuming you mean things like maximum length? I've added a bit more about this too, to the same bullet point about the TLDs as before. I don't think too much detail here is helpful, as this is supposed to be a beginner's article.

> This is not clear: "When controlling the "upper" part of a domain name (e.g. mozilla.org), one can create other domain names (sometimes called "subdomains") (e.g. developer.mozilla.org)."

This was a bit confusing. I've updated the wording here to make it better?

> Why can't domain names be bought?

I have added an answer to this.

> How does a local DNS database connect to top-level DNS servers? (Or do the top-level servers connect to the local DNS databases?) The writer's comment about "propagation time" is also confusing in this section's note. I don't understand what propagation is, nor how it relates (or doesn't relate) to this "wait time."

I've tried tweaking this section, and I've gotten rid of the bit about propargation time because it really just confuses more than it helps. But I am wary of going too deep into this subject. IT is a beginner's article, and going into too much depth will just confuse people.
