### ISSUE TITLE
Refactor sensor and orientation, forms and input events

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#1122]
This is a work item for #685.

sensor and orientation:

* [X] *devicelight*
https://developer.mozilla.org/en-US/docs/Web/Events/devicelight 
moved to https://developer.mozilla.org/en-US/docs/Web/API/Window/devicelight_event
moved other languages
doesn't exist, so didn't spend much time updating (was in https://www.w3.org/TR/2015/WD-ambient-light-20150903/#devicelightevent-interface but isn't in https://w3c.github.io/ambient-light/#ambient-light-sensor-interface)
Did not archive as Edge still supports it. Should archive when removed from Edge.
Properties section kept due to additional information
No examples as it doesn't exist anymore
Did not link from window as it doesn't exist
BCD present
<br/>

* [X] *devicemotion*
https://developer.mozilla.org/en-US/docs/Web/Events/devicemotion 
moved to https://developer.mozilla.org/en-US/docs/Web/API/Window/devicemotion_event 
moved other languages  
Properties section kept due to additional information
BCD is finally showing 
linked to from https://developer.mozilla.org/en-US/docs/Web/API/Window#Events
<br/>

* [X] *deviceorientation*
https://developer.mozilla.org/en-US/docs/Web/Events/deviceorientation 
moved to https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event.
BCD showing - https://github.com/mdn/browser-compat-data/pull/3820
Translations moved.
Properties section kept due to additional information - espeically since example uses those properties
<br/>

* [X] _deviceproximity_
https://developer.mozilla.org/en-US/docs/Web/Events/deviceproximity
https://developer.mozilla.org/en-US/docs/Web/API/DeviceProximityEvent/deviceproximity_event
Then archived
New location: https://developer.mozilla.org/en-US/docs/Archive/API/deviceproximity
Translations archived
<br/>

* [X] _userproximity_
https://developer.mozilla.org/en-US/docs/Web/Events/userproximity
archived at https://developer.mozilla.org/en-US/docs/Archive/API/userproximity
no translations

forms and input:

* [X] *input* event
https://developer.mozilla.org/en-US/docs/Web/Events/input 
moved to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event
BCD PR: Add input event to api.HTMLElement #3911
added to 
 * https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement, 
 * https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable,   
 * https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement#Events
 * https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement#Events
 * https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#Events
<br/>

* [X] *invalid* event
https://developer.mozilla.org/en-US/docs/Web/Events/invalid 
moved to https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation/invalid_event 
then moved to https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/invalid_event
moved translations
moved general info table to top section
rewrote text
added some see also (:invalid pseudo)
removed properties
added example
changed title
added specifications
basically, rewrote the page.
BCD is in PR phase - https://github.com/mdn/browser-compat-data/pull/3989
still not convinced it belongs under element (prefer constraint validation)
added link to htmlelement and HTMLelement. did not remove from constraint validation
<br/>

* [X] HTMLFormElement reset event
https://developer.mozilla.org/en-US/docs/Web/Events/reset 
moved to https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event
translations moved
BCD 
Added to https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#Events
properties section removed
added description to bcd in https://github.com/mdn/browser-compat-data/pull/3990,
<br/>

* [X] HTMLFormElement submit event
https://developer.mozilla.org/en-US/docs/Web/Events/submit 
moved to https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit/submit_event
translations moved
BCD 
added description to BCD in https://github.com/mdn/browser-compat-data/pull/3990
Added to https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#Events
properties section removed
<br/>

* [ ] https://developer.mozilla.org/en-US/docs/Web/Events/submit_(event) (note: dupe of`submit` above)

AC:
* all pages migrated 

STATUS:
3 PRs need to be merged and an additional BCD needs to show - was merged today so not yet showing.

**Comment by estelle** [comment]
@irenesmith When you have some time, can you review? Thank you.

**Comment by irenesmith** [comment]
@estelle As soon as I'm done with the SVG events.

**Comment by irenesmith** [comment]
@estelle - Here is my feedback:

I noticed that in some cases, your Event handler property has the entire name, i.e. GlobalEventHandler.oninput instead of just oninput. You can change the text that is displayed by adding the display text to the macro call, like this: {{domxref("GlobalEventHandlers.oninput", "oninput")}}

- https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs/devicelight_event:
Double-check with Chris, but I think this needs to be under Window since the defaultView is a Window object. And don't forget to  add it to the Events section of that page
  Should have {{APIRef}} macro, the blue table has more rows than necessary. Supposed to be Bubbles, Cancelable, Interface, and Event handler property
The Properties section should have been removed
No examples, no link to specifications, and no BCD

- https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent/devicemotion_event
This should be under Window and added to the Events section of that page
Extra rows in the table. Should be only the four listed above
Example heading should be plural (this is from a comment I received from Will)
Properties section should be removed

- https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent/deviceorientation_event
This should be under Window and added to the Events section of that page
Once again, extra rows in the table
Remove Properties
Examples heading should be plural
Use BCD macro

- https://developer.mozilla.org/en-US/docs/Web/API/DeviceProximityEvent/deviceproximity_event
This should be under Window and added to the Events section of that page
Extra rows in the table
Remove Properties section
No example
Related Events needs to be removed and the entry under it should be added to See also

- https://developer.mozilla.org/en-US/docs/Web/API/UserProximityEvent/userproximity_event
This should be under Window and needs to be added to the Events section of that page
Extra rows in the table
Properties should have been removed
No example

- https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/input_event
This should probably be under HTMLFormElement and should be added to the Events section of that page
Extra rows in table
Remove Properties section
Example should be Examples (plural)
You didn't remove the old compatibility table
Don't repeat the oninput macro link in See also

- https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation/invalid_event
Should be under HTMLInputElement and needs to be added to the Events section of that page
Remove Targets and Default Action from table. Need to have the Event handler propert added to the table
Example header should be plural
Don't repeat the oninvalid property in the See also section
No BCD section

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event
If this is under HTMLFormElement, an Events section needs to be added to the page and this event should be listed there.
Remove Targets and Default Action from the table and move onreset into the table as the Event handler property
Example should be plural
No BCD

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit/submit_event
Should be listed in the Events section under HTMLFormElement
Targets and Default Action should be removed from the table.
Example header should be plural
Specification should be specifications
onsubmit belongs in the table as the Event handler property
Don't repeat onsubmit in the See also section
No BCD section

**Comment by wbamberg** [comment]
@estelle, thanks for this!

I think we decided to archive https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs/devicelight_event ?

Some of @irenesmith 's comments still need dealing with (and I spotted a couple of others).

In all cases please check that the blue box at the top contains the right rows in the right order. You can use https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointermove_event as a guide. It's OK to include some extra rows if you think it's important, but especially Target is not needed (it's now obvious because the event is under its target) and Default action is not needed if it's just None.

-----------------

> https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent/devicemotion_event

This should have "Other properties" removed.
The GlobalEventHandlers.ondevicemotion link in See Also is broken (I think this should be Window.ondevicemotion). Actually this can be removed if we link to it from the blue box.

> https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event

This should have "Other properties" removed.
The `ondeviceorientation` link in the blue box is broken.
The code sample should be marked as JS so we get syntax highlighting.
Browser compat still uses the old table.

> https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

Irene commented that this should be under HTMLFormElement, but I think what you have here is right.
The title should be "HTMLElement: input event".
But it should be listed in https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement#Events.

> https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation/invalid_event

As Irene commented, I don't think this should be under Constraint_validation, it should maybe be under HTMLElement? It also needs the correct title.

> https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event

This needs the correct title.

> https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

"Example" should be "Examples".

---------------

For BCD:

These pages are missing a BCD section:
* https://developer.mozilla.org/en-US/docs/Web/API/Window/devicemotion_event
* https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation/invalid_event

These pages have a BCD section but are missing the data:
* https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event#Browser_compatibility (this one still has a vestigial old table too)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event#Browser_compatibility

These pages have data showing up:
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event#Browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event#Browser_compatibility

However, it looks like the data is missing a "description": "\<code>eventname\</code> event" key, which means it's shown in the table like "`eventname_event`" rather than "`eventname` event".

**Comment by estelle** [comment]
@wbamberg I think I got everything and this should be much easier for you to read. This overwrites any comments in https://github.com/mdn/sprints/issues/1284, which i closed as a 'duplicate' of stuff covered here.

**Comment by wbamberg** [comment]
Thanks @estelle  for the updates!

Some of the comments above aren't showing up on the pages. Especially, please double check:

* page titles
* the format of the blue boxes (sorry I know it seems really pedantic but having reference docs consistently formatted seems like a helpful thing for us to have).
* the "Other properties" section (this is just duplicated from the event's interface page, and it's much better to have it in one place)

For BCD:

* https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event#Browser_compatibility is missing

* https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event#Browser_compatibility
Link capitalisation is wrong: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event#Browser_compatibility - this seems like a super-nit I know, but it means that the caption in the table is made into a link (because the URL doesn't match I guess).

* https://developer.mozilla.org/en-US/docs/Web/API/Window/devicelight_event is showing BCD for the event interface not the event

**Comment by estelle** [comment]
So frustrating.... i replied, then lost the post before hitting 'comment'....

I spoke with @chrisdavidmills about the 'other properties'.  While those properties are on the interface page, were the 'other properties' not their, our visitors have no way of knowing the event has additional properties without going to the interface page. I strongly believe we need to leave those other properties there. 

https://github.com/mdn/browser-compat-data/pull/4042 is a fix for the caption in the table

The BCD for invalid event is showing.

Instead of adding a BCD for the obsolete devicelight event to the Window API, i archived the page. The devicelight event isn't in any spec, so adding it to the Window API would mean we would need to add information about an obsolete feature that is in no  specification, giving importance to something that should not be hilighted.

**Comment by chrisdavidmills** [comment]
> I spoke with @chrisdavidmills about the 'other properties'. While those properties are on the interface page, were the 'other properties' not their, our visitors have no way of knowing the event has additional properties without going to the interface page. I strongly believe we need to leave those other properties there.

I remember us having this conversation, and I do agree with you that it would be nice to have this information more readily accessible. As I said at the time, I am concerned about inconsistency, and then I forgot to mention it to Will (sorry), plus we were already quite far through the process by then. Ideally we should have talked about this at the start of the process, but hey ho.

The problems at this point are:

* There are only what, two event pages that have this "Other properties" section? This is really inconsistent and just looks strange. All other event pages have the problem you are trying to solve (which again, I think is a valid problem to solve).
* "Other properties" will probably confuse some readers — properties other than what exactly?
* If you go to the [DeviceMotionEvent](https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent) page, you'll see that it doesn't mention its inheritance from event, which is a problem.
* You still have to go somewhere else to find all the other things available on the event object (e.g. inherited from [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event))

For now, I would suggest getting rid of these sections to make things consistent, then we should come up with a proper plan that might solve this problem more effectively.

A simple thing to do would be to replace "Interface" in the blue box with "Event object interface" or similar, to make it more obvious what this is. This wouldn't take much time.

You could perhaps also have an expanded section below called "Event object features", which says that the event object is of type x so has the features available on that page. x inherits from the Event interface, so it also have those features available. You could use florian's inheritance macro to make this easier. This would take a little bit more time, but be more effective.

A more complex thing to do would be to have the above section, but use the page macro to transclude the features available on the event object into this page too. So they are available in both places, but only need to be updated in one place. This would be a lot more complex, and would also rely on us updating all of the event object pages to be consistent. This would take loads of time.

**Comment by wbamberg** [comment]
> Ideally we should have talked about this at the start of the process, but hey ho.

We discussed this question in https://github.com/mdn/sprints/issues/915 (see https://github.com/mdn/sprints/issues/915#issuecomment-462475700 and follow-up) and it was documented in the guidelines I wrote for this https://github.com/mdn/sprints/issues/685#issuecomment-463425113, and that's the guideline we've followed for all the other events that we've migrated.

So first, these would be the only two pages out of a hundred or so that use this approach to documenting event interfaces that extend `Event`.

I do appreciate that it's important to help developers understand which properties are available in the object passed into event listeners, but I don't think this is the right way to do it.

First, the presentation doesn't make sense to me. These pages aren't documenting an object, so it doesn't have properties. And "Other properties" - in addition to what exactly?

It would make more sense to have a heading like "Event handler argument" that says something like:

> The argument passed to the event handler is a `DeviceOrientationEvent` object that derives from `Event`. It has all the properties of `Event` and adds the following extra properties:

But then we get into duplication. I think it's important to have one place where we document things rather than duplicating content. Otherwise they inevitably diverge, and readers are left wondering which is right, and having to check both sources to make sure they didn't miss anything.

At the moment there are basically three pages of interest:

* the "event" page (e.g. https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointermove_event)
* the "event handler property" page: (https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onpointermove)
* the "event interface" page: (https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent)

If we duplicate "other properties" in `pointermove_event`, why not also duplicate them in `onpointermove`? But then also of course the same event interface is sometimes used for many events, sometimes across quite unrelated interfaces (`MessageEvent`, for example). Which means the same list of properties would be duplicated over ten or more pages scattered through Web/API, and this seems like it will be hard to maintain.

So I think links are a simple way to resolve this: the `eventname_event` and `onevent` pages link consistently to the event interface page, and we have one copy of the list of properties.

And this is what we've tried to do with the entry in the "blue box". Looking at it now, I can see that "Interface" is a pretty confusing name for that entry, perhaps "Event handler argument" might be clearer?

Or even take it out of the blue box and have some text consistently placed, saying something like:

> "The argument passed to the event handler is a `DeviceOrientationEvent` object."

Finally: Chris mentioned transclusion as a possible solution to having this content replicated across all these pages, but still only having one copy to maintain.

I've thought a bit about transclusion in general, and: I think transclusion is a great solution, *if it's done automatically*. If we were in a situation where the platform can build documentation pages from component pieces, and we can specify that an event page contains a section describing its handler's argument, which the platform knows where to find, then this is great. But in Kuma transclusion means we make up some ad hoc thing for this one case, that we either don't document or document somewhere noone ever sees, so most people who maintain the docs don't know about it, and just end up copying the docs anyway, or they don't understand how to do it, or they accidentally break the `<div>` we are using to indicate to the {{page}} macro which bit of content to transclude... so it's likely to end up a mess.

**Comment by chrisdavidmills** [comment]
@wbamberg after a discussion with @estelle, I've removed the "Other properties" sections.

Can we close this now?

**Comment by chrisdavidmills** [comment]
@estelle there are a couple of other updates needed above; then we can close this.

**Comment by estelle** [comment]
If something else needs to be done, either let me know what it is or do it if it's faster than explaining. Thanks.

**Comment by chrisdavidmills** [comment]
I spent 10 minutes checking over the previous comments made, and there were a few things still not done. I decided to do them, because it is pretty much as quick for me to do them as it is to write out a list of what needs to be fixed. I also checked that all the BCD stuff is now showing  up correctly.

https://developer.mozilla.org/en-US/docs/Web/API/Window/devicemotion_event:

* blue box corrected to be consistent with other event pages
* on... handler removed from See also as it was now in the blue box.

https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event:

* blue box corrected to be consistent with other event pages
* on... handler and event object interface removed from See also as they are now in the blue box.
* Weird formatting on intro paragraph sorted out.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event:

* blue box corrected to be consistent with other event pages
* on... handler and event object interface removed from See also as they are now in the blue box.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event:

* blue box corrected to be consistent with other event pages
* on... handler and event object interface removed from See also as they are now in the blue box.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event

* blue box corrected to be consistent with other event pages
* on... handler and event object interface removed from See also as they are now in the blue box.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

* blue box corrected to be consistent with other event pages
* on... handler and event object interface removed from See also as they are now in the blue box.
* "Specification" heading corrected to "Specifications"

@wbamberg OK, now I think this can be closed ;-)

**Comment by wbamberg** [comment]
Looks good to me. Thanks @estelle and @chrisdavidmills for your work on this.
