### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics

### ISSUE THREAD

**Issue by alanmehio** [mdn/sprints#1142]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

See below. The  result become undefined since it return no value unless we type the below  on the console
var person = {}; person();  
instead of the below. 
var person = {};

Regards,
Alan Mehio

**Comment by alanmehio** [comment]
Please revisit all simmilar issue. The user does not see the result which is stated as below  
[object Object] 
but rather "undefined" 
This has been tested on Chrome dev console.

**Comment by chrisdavidmills** [comment]
Hi @alanmehio !

I'm not really sure I understand the problem here. Sre you talking about the instructions at the start of the https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics#Object_basics section?

These seem correct to me. 

In any JS console, if you type in

`var person = {}`

Followed by 

`person`

you'll get a result along the lines of `[object Object]`, `Object { }` or `{ }`. I updated the section that tells you what the result should be, because since I wrote this, Chrome and Firefox both return different things to specify an object.

If you type in `person()` you'll get an error, because there is no top-level function called person defined on the page.

**Comment by alanmehio** [comment]
True
But I can’t see after defining this
var person = {};
person;


I see
var person = {};

Only

**Comment by alanmehio** [comment]
Chris,
You are right but in the document is states the below
*person = {};*

*If you enter person into your JS console and press the enter button, you
should get a result similar to one of the below lines:*

I am saying   just add this   instead

*person = {}; person;*

I have not tested with FireFox  but on IE (internet explorer) 11.96  it
works  but it does not work on Chrome.  Again it may work on FireFox but I
have not tested it .

On Chrome,  when you define an object like person and press enter, it
display "undefined" while on IE it works as stated in the documentation.

Good to hear there is somebody who takes feedback. This encourage me and
others.


Regards,

Alan Mehio

**Comment by chrisdavidmills** [comment]
Thanks @alanmehio , I think you've now helped me to understand what the confusion is here.

The instructions do state to enter both `person = {}` and `person`; it's just that you are supposed to enter the first one in the example code file, and the second on in the JavaScript console.

I have rewritten the instructions to make it clearer what you are being asked to do.

Is it better now?

**Comment by alanmehio** [comment]
Chris,
It is better now.  The problem is the issues between browser. I want you to
try it on Chrome and see if you get the same result as on the FireFox and
Internet Explorer.
The document is fine now.
I will try it on FireFox tonight and Chrome tonight and send you two images
to see the differences. I would like to recommend the MDN mention the
FireFox as the browser to test with.

In general the documentation has become much better on MDN.

Regards,
Alan

**Comment by alanmehio** [comment]
Chris,
I am attaching the images as promised
Google Chrome is up to date
Version 72.0.3626.121 (Official Build) (64-bit)

FireFox QUANTUM
65.0.1 (64-bit)

IE 11.590

Testing on Window 10 64 bit

Strange the behavior of IE at work and at home is different

See the "undefined" once you  type "var person = {};" and press "enter"

// Alan

**Comment by chrisdavidmills** [comment]
Right. So this is standard behavior for DevTools, on Chrome/Firefox (I don't have IE handy to test on.) It doesn't mean that the value is not set, just that it is not returning anything. It just sits there and does nothing until you decide to do something with it.

It shouldn't happen if you follow the instructions in this article correctly, because you are entering the object definition in the sample file, loading that in the browser, then opening the devtools and typing `person`.

I am happy to update them again if you feel like I need to.

I wonder if I should also add a line to the "What are browser developer tools?" article to make it clear what `undefined` means in that context?

**Comment by alanmehio** [comment]
Chris,
Your are right
I think you should leave it like that  in order to avoid  more confusion

// Alan

**Comment by chrisdavidmills** [comment]
Thanks again Alan. closing this for now.
