### ISSUE TITLE
Array.map() is misleading, as it is actually Array.prototype.map()

### ISSUE THREAD

**Issue by ghost** [mdn/sprints#1164]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Since `Array.map` is `undefined`, I'm afraid writing `Array.map` can be misleading.

![mdn_array_map_github_issue](https://user-images.githubusercontent.com/48134868/54072551-6a66a300-427c-11e9-810d-76b28168bb10.jpeg)

**Comment by a2sheppy** [comment]
I don't think this is a thing we're going to fix. Yes, it's technically Array.prototype.map(). In reality, this is not something that matters most of the time, and it's confusing for newcomers.

**Comment by jmswisher** [comment]
In our last [big discussion](https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/31641/41) of this issue, we were close to converging on either array.map() or Array: map(). There was an open question of how these might affect SEO. @a2sheppy Did you ever look into that? 

Also, @chrisdavidmills someone has munged the formatting of the doc you wrote on [Options for fixing titles of WebAPI reference pages](https://docs.google.com/document/d/19ZJbG3tp7CBygsFCj0BeY9CPWCcvnv75GZeTKhGzSlQ/edit?usp=sharing). Can you fix that, and restrict the sharing so that doesn't happen again?

**Comment by a2sheppy** [comment]
So, yes, it will affect SEO but it should be pretty brief. The experiment
we’re setting up to run on a few CSS reference pages will help us to
confirm this.

On March 20, 2019 at 4:39:26 PM, Janet Swisher (notifications@github.com)
wrote:

In our last big discussion
<https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles/31641/41>
 of this issue, we were close to converging on either array.map() or Array:
map(). There was an open question of how these might affect SEO. @a2sheppy
<https://github.com/a2sheppy> Did you ever look into that?


Eric Shepherd
Senior Technical Writer
MDN Web Docs <https://developer.mozilla.org/>
Blog: https://www.bitstampede.com/

**Comment by chrisdavidmills** [comment]
I fixed the doc and the permissions; thanks Janet!

The conclusion the research came to was that the best way to fix the JS/API titles would be to simply lower case the interface name to imply that it is an instance name rather than the Interface itself.

So `Array.map()` and `Array.prototype.map()` would be updated to `array.map()`.

`XMLHttpRequest.open()` (for example) would be updated to `xmlHttpRequest.open()`

I was planning to make these updates as part of the periodic tier1 page maintenance. Unless someone comes up with a really good reason why we shouldn't. I'm looking forward to the results of the SEO experiement too ;-)
