### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Introduction#%E5%AE%83%E4%BB%AC%E6%98%AF%E5%9F%BA%E4%BA%8E%E5%AF%B9%E8%B1%A1%E7%9A%84

### ISSUE THREAD

**Issue by SamoZ** [mdn/sprints#1178]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Failure of the link indicated by the arrow

![image](https://user-images.githubusercontent.com/25240164/54249163-1d374980-457a-11e9-998a-b6ab01995196.png)

**Comment by chrisdavidmills** [comment]
I have deleted the links that are not working.

But really this article needs to be updated to match the updated English version. We removed the Google Maps examples because Geolocation is not working very well anymore, and Google Maps is really bad to send beginners to for learning about APIs (it is hard to sign up for, reequired a credit card, etc.)
