### ISSUE TITLE
Document the Payment Handler API

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/sprints#1186]
# Request type

- [X] New documentation
- [ ] Correction or update

# Details

While going through all the APIs that have no compatibility data for Firefox, I found that there is no documentation regarding AbortPaymentEvent.  The pull request that adds this event into the W3C spec can be found [here](https://github.com/w3c/payment-handler/pull/170).

The API is here: https://w3c.github.io/payment-handler/

**Comment by a2sheppy** [comment]
@vinyldarkscratch - Just to be clear, you mean there's no documentation and not that there's nothing in BCD, yes? I ask because you say you noticed this while checking through BCD, but there is stuff in BCD, so presumably that means that this look through BCD led you to notice a lack of content on the site. I just want to be sure I understand, because if you mean the BCD stuff, then this is already fixed. :)

**Comment by a2sheppy** [comment]
So, this is tricky, because this is part of the Payment Handler API, which is the same specification as Payment Request. We have not really started to document Payment Handler yet.

Here's what I'm going to do -- I'm going to change this to "Document the Payment Handler API". :)

**Comment by vinyldarkscratch** [comment]
Yeah, sorry for the confusion there!  I'm referring to MDN documentation, I noticed it while trying to update the existing data in BCD.  The new title looks perfect as well!

**Comment by a2sheppy** [comment]
It's worth mentioning that Mozilla has no intention of implementing this API at this time, so priority-wise this will wind up being pretty much a zero. :)

**Comment by a2sheppy** [comment]
Also, this event was never added. There was a PR created but it was never merged, regardless of whatever GitHub status fields might claim. :)

**Comment by jpmedley** [comment]
This one would actually fall to me since Chrome, I believe is the only implementation. I just don't know when I'll get to it.
