### ISSUE TITLE
SEO: Run an experiment with simpler titles for CSS reference pages

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1280]
The first experiment gained about 11% traffic using names of the form "CSS foo — short description of foo". We now want to do an experiment using the simpler "CSS foo property" or "CSS bar pseudo-element" form.

**We can reuse the same control pages as the other experiment.**

- [x] Select 10 new CSS reference pages to alter for this test; these must be different than the first test
- [x] Alter the titles of those 10 pages
- [x] Start a test on sanitycheck.io
- [ ] Wait an appropriate length of time (4 weeks)
- [ ] Examine the results
- [ ] Compose a Discourse post reviewing the results; compare to previous test
- [ ] Hopefully make a decision on what to do with CSS page titles

**Comment by a2sheppy** [comment]
The test is running!

**Comment by jmswisher** [comment]
@a2sheppy Should we close this and create a new issue for getting the results (in Sprint 4)?

**Comment by a2sheppy** [comment]
I'm going to just move this to the next sprint instead of starting a new one

**Comment by jmswisher** [comment]
It's going into Sprint 4 (Koko Taylor), not Sprint 3 (Jessye Norman).

**Comment by jmswisher** [comment]
In general, when a story like this has pieces to be done in different sprints, it's better to make them two (or more) stories, so we can track how much work is accomplished in a given sprint. When it's left incomplete, the work in the first sprint doesn't get counted in that sprint; it just kind of disappears from the tally. That's different from stories where it's incomplete because it just took longer than expected.

**Comment by jmswisher** [comment]
@a2sheppy Is the estimate still correct?

**Comment by a2sheppy** [comment]
@jmswisher yes

**Comment by jmswisher** [comment]
[Results posted in Discourse](https://discourse.mozilla.org/t/resuls-of-second-css-reference-title-a-b-test/41366)
