### ISSUE TITLE
HTTP "Upgrade" Header Documentation is Missing

### ISSUE THREAD

**Issue by campbellbrendene** [mdn/sprints#1283]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade is missing. I tried to follow links to the page from https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/101.

**Comment by hamishwillee** [comment]
I've created page here: https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade

BCD is in progress here: https://github.com/mdn/browser-compat-data/pull/7367

@chrisdavidmills I think this is a useful summary. Mostly I am concerned about the BCD because, as usual, hard to find confirmation of whether things are supported and in particular, the version. We will see.

**Comment by chrisdavidmills** [comment]
Nice work, thanks @hamishwillee . I've given the page a light copy edit and cleared up a few styling bits; looks good to go.

And yeah, we'll see what Daniel says about BCD.

**Comment by hamishwillee** [comment]
@chrisdavidmills Awesome. I'm going to close this issue. The BCD thing is separate, and finding out the detail is gong to take forever.

**Comment by hamishwillee** [comment]
FYI, BCD updates. I removed the "hidden" on the compat table as this is now merged https://github.com/mdn/browser-compat-data/pull/7367 . Right now BCD has not updated but it will, and I don't want to forget!
