### ISSUE TITLE
Debugger - Log points

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1289]
# User story
As a developer, I want to be able to add log points, places in the document where I want to send values to console, so I can clearly see what my code is doing.

# Acceptance criteria
- [x] Log points documentation has been added to the Debugger page that discusses breakpoints
- [x] Images showing the use of log points have been created and added to the documentation
- [x] New documentation has been reviewed
- [x] Information has been added to 67 release notes.

**Comment by irenesmith** [comment]
Created a new page: [Set a log point](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Set_a_log_point), along the same lines as [Set an XHR breakpoint](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Set_an_XHR_breakpoint) that describes how to create and work with log points.

**Comment by janodvarko** [comment]
There is a typo on 'Set a log point' page in `When should you use log points?` section.
When when you want to know... => When you want to know...

In case of `Set an XHR breakpoint` there is step #3:
Click the plus sign next to the XHR breakpoints header, enter the URL in which you are interested, and press Enter.

There could be a note explaining that the user can enter just a keyword that is used to break on any URL containing it.

Otherwise it looks great to me!
Thanks for working on it!
Honza

**Comment by irenesmith** [comment]
Thank you! I fixed the typo and added a note to the XHR breakpoint page as follows:

Note: If you enter a key word instead of a URL, code execution will pause on any call to a URL that contains that keyword.
