### ISSUE TITLE
Grizzly: Research localisation process for banner strings

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1294]
# User story

As a product owner, I need to ensure that all relevant banner string can be exposed for translation and successfully displayed on the front end.

# Acceptance criteria

- [ ] There is a documented mechanism by which strings for the banners are extracted and exposed for localization.
- [ ] Localised strings for banners can be shown on the front end

# Tasks

In [PR 5339](https://github.com/mozilla/kuma/pull/5339) a method of making strings available for localisation was suggested by John Whitlock:

> The strings will need to be present in a source file as well. For example, the search topics are exported to a Python file using `./manage.py generate_search_names`:
> 
> [/kuma/search/management/commands/generate_search_names.py@`master`](https://github.com/mozilla/kuma/blob/master/kuma/search/management/commands/generate_search_names.py)
> 
> The output is written to a file that is checked into the repository:
> 
> [/kuma/search/names.py@`master`](https://github.com/mozilla/kuma/blob/master/kuma/search/names.py)
> 
> This works decently for search topic names, because it is rare to change them. You'll have to set up some processes around generating source files for banner text.

Based on the above, we would need to write a similar solution for the banners. This will need to be run more frequently as new banners are added, and existing banners are changed.

1. - [ ] Write a script similar in nature to `./manage.py generate_search_names` for banner content
2. Write contents to a file similar in nature to [/kuma/search/names.py@`master`](https://github.com/mozilla/kuma/blob/master/kuma/search/names.py)
3. - [ ] Setup and document a process to manage these strings.
4. Ensure the strings are exposed to the front-end

**Comment by schalkneethling** [comment]
@peterbe I did not estimate this one(as I have no idea of the complexity really) or assign it to anyone. I am thinking this might be a good item for you to work on if it is of interest to you.

We can also work on it together, but that might slow things down more than it helps anyone. Let me know your thoughts. Thanks!

**Comment by peterbe** [comment]
As I see it, with my newbie eyes, is that there are two choices:

1. Add a `locale` field to the `Banner` model and then, using the Django Admin, type in the banner titles and banner bodies, in each individual language. Perhaps leave the English one un-set so it acts as the default. (Or not, perhaps, like with the wiki if there isn't a `sv` version don't bother falling back on the `en-US` one)

2. Type it up somewhere and execute a command so as to check in the original strings in .po files and then ship these to `mdn-l10n` for translation. Similar to what we're doing for search names. 

It all depends on how much the content is going to fluctuate over the next couple of months/years. 

A caveat is that if we make the content localized, there's no easy place to edit it. Surely the only people who even have access to Django Admin, in Prod, are a select few who at best speak Afrikaans and Swedish at most.

**Comment by schalkneethling** [comment]
> A caveat is that if we make the content localized, there's no easy place to edit it. Surely the only people who even have access to Django Admin, in Prod, are a select few who at best speak Afrikaans and Swedish at most.

Thanks Peter, I agree. This is why I was thinking of using the same process as the search names do. Pinging @atopal as he is one of the people that will use this feature most. Thoughts Kadir?

**Comment by peterbe** [comment]
@schalkneethling and I chatted about this a great deal and it seems very hazy on the expectations and details. Mayhaps it is written down somewhere but I don't see it. 

To get banner content (title, body, button text) into different locales, our only tool is to put the English into code (jinja templates or python) so it goes through `gettext`. Options, as I see it:

### Option 1

Do what we did with [search names](https://github.com/mozilla/kuma/blob/master/kuma/search/names.py) but that requires someone to use their local dev environment to run the django command and prepare a PR for a code change. Then it hops onto the pontoon and stage and prod deployment train. 
**Question:** Who's going to be responsible for generate this code change and PR? When do they know to do it?

### Option 2

Don't localize banners at all. Instead, banners can become a replacement for Soapbox but with more powers in terms of design. 
**Question:** How important is it to be able to present banners in all locales? What exact features from Soapbox do we need/desire?

### Option 3

Maintain the source of truth for all *possible* English banners in a `jinja2/banners-content.html` Jinja template. Each banner can be a macro. [Like this pseudo code](https://gist.github.com/peterbe/9874e3731aaba5f3c4740002b57140ca)
No Django Admin. If you need to change anything (e.g. a typo in `"In Maintanence Mode"`) you edit in git and make  GitHub PR and wait for the Pontoon, Stage, Prod deploy dance. 


### Option 4

A bit of both.
First, check this into Python [like this pseduo code](https://gist.github.com/peterbe/1971d9bb65b1f30a4865e60e28b04274) then, in runtime, we mix that list of banners with a database query for *active* banners (might depend on URL) that have been authored in the Django Admin. 
In both this option and Option 3, the driving force for deciding to show can be Waffle switches. 

@atopal Really hoping to hear your thoughts and side to this.

**Comment by atopal** [comment]
In terms of why we need this: We're going to field a survey in about 3 weeks that is going to be localized into 8 languages. Showing the call to action in English only defeats the purpose for that (increasing the audience that takes the survey).

We won't always localize the banners, eg asking people to participate in user interview, since that interview would have to be in English.

We could possible get away with not going through pontoon for these, although I'd highly prefer it.

Regardless of how we handle this long term, we need the ability to field the survey in a localized form on May 6.

**Comment by peterbe** [comment]
Wow! So it's urgent. That's good to know. 

So I then think we should do the hybrid solution. Put some banner *content* into (git) code. There'll be a fixed set of these and they'll be tagged by ID. 

Also, in the Django Admin you'll get to pick between choosing one of these ready-made, or you can override and type in your own text. 

In rendering, I suspect it'll look something like this:

```jinja2
{% for banner in waffle_enabled_active_banners_ordered_by_priority %}
<div id="{{ banner.id }}" class="banner">
  <h4>{{ banner.get_title() }}</h4>
   <p>{{ banner.get_content() }}</p>
</div>
{% endfor %}
```

And the `Banner` model's could look something like this:

```python
from .banner_texts import default_banner_texts

class Banner(models.Model):
    id = models.CharField(max_length=12, unique=True)
    title = models.CharField(null=True, blank=True) 
    ...
    
    def get_title(self):
        if self.id in default_banner_texts:
            return default_banner_texts[self.id]
        elif self.title:
            return self.title
        else:
            raise NotImplementedError("Banners must have a known ID or their own content in the DB")
```

And the defaults text something like this:

```python
# In kuma/banners/banner_texts.py

from django.utils.translation import ugettext_lazy as _

default_banner_texts = {
    "developer_needs": {
        "title": _('Can you take this survey please?'),
        "content": _('Yada yada yada'),
    },
    "maintenance_mode": {
        "title": _('MDN is in Maintenance Mode'),
        "content": _('We started this madness %(date)s'),
    },

}
```


### Advantages

* Some banners get localized but at the slow paces of prepping English strings and waiting for Pontoon. 
* We can switch to using Banners instead of Soapbox and have 1 less moving part (...an aging unmaintained python library). 
* If we type up a standard "Maintenance message" banner, in code, you could potentially type just use the Django Admin to enter parameters for that and ultimately you can have a banner that says "Just nu är MDN i underhållsläge tills April 21 2019"

### Challenges

* We need to get these "standard banners" (e.g. the survey one) into Python (gettext) code ASAP so we can get that going with Pontoon well before May 6. **Where is the exact text?**
* Not entirely sure the Banners work is finished. @schalkneethling and I need to escalate his PR to support these features. 
* Not sure how this work is going to coincide with the React rendering effort. Perhaps best to focus on Jinja only for now and ping @davidflanagan to keep an eye on the work. 
* Perhaps it's easier to not get fancy with the database and just do a pure Jinja + Waffles solution. Whatcha think?

**Comment by atopal** [comment]
Re text, I'll provide the final wording early next week. Might also be a good opportunity to get design help from Nick.

**Comment by peterbe** [comment]
> Re text, I'll provide the final wording early next week. Might also be a good opportunity to get design help from Nick.

It might be. But May 6 is just around the corner. It could compromise the deadline. The more I think about it, the more I'm attracted to...:

* Putting the banners into code (like the developer-needs version) ONLY
* Getting the new texts into Pontoon ASAP
* Get Nick involved to work with @schalkneethling sooner
* NOT use MySQL at all for banners until AFTER May 6
* NOT attempt to use MySQL + Banners to replace Soapbox for urgent messages that don't need to (always) be localized. 

Also, one thing that's fuzzy with regards to *replacing Soapbox* is that there's a big difference between banners like "Hey, would you like to take part in something" vs. "Warning! Our database is on fire! Please accept our apologies"

**Comment by jmswisher** [comment]
This was marked as Done in the spreadsheet, but it's not clear to me that it's done. Maybe I missed/zoned out on some discussion. @atopal Did you ever provide the needed strings? Is this moot at this point?

**Comment by schalkneethling** [comment]
> This was marked as Done in the spreadsheet, but it's not clear to me that it's done.

Hey @jmswisher - That was for the research portion of this. We are not going to move forward with this right now. It is temporarily put back in the backlog(Ice Box?). The new strings was provided, and there is a pull request to get those into master. Thank you for following up.

**Comment by peterbe** [comment]
This got left open for no good reason. The world is a different place now.
