### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API

### ISSUE THREAD

**Issue by RobJacobson** [mdn/sprints#1343]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update 

# Details
There are two bugs in this article:
- [x] The zip file from "direct zip file download" is out-of-date and doesn't match the GitHub repo.
- [ ]  The source code never uses/consumes the "chunks" buffer.  It writes to this buffer, but never reads from it.  Instead, the "stop" command simply returns the last uncommitted blob of data.  If other blobs have already been saved in the "chunks" buffer, they won't be played.  See the link for a correct example.
[https://developers.google.com/web/updates/2016/01/mediarecorder](url)

**Comment by RobJacobson** [comment]
Another example:
[https://github.com/mdn/webaudio-examples/blob/master/create-media-stream-destination/index.html](url)

**Comment by a2sheppy** [comment]
Removed the zip file download link, which isn't necessary anyway.

**Comment by a2sheppy** [comment]
@RobJacobson: Are you sure about #2? I ask because I'm looking at the code for the onstop handler in the example and it's creating a blob from the `chunks` array and using that as the `src` property on the `<audio>` element:

```
  var blob = new Blob(chunks, { 'type' : 'audio/ogg; codecs=opus' });
  chunks = [];
  var audioURL = window.URL.createObjectURL(blob);
  audio.src = audioURL;
```

So it creates a new `Blob` object by concatenating the recorded chunks together, then empties the `chunks` array to prepare for re-use before creating a URL for the `Blob` and setting `audio.src` to that.

LMK if you still feel there's a problem.

**Comment by RobJacobson** [comment]
You're absolutely correct.  Thanks for clarifying!  I'll close the issue.
