### ISSUE TITLE
URL API Page from index link is not working

### ISSUE THREAD

**Issue by dbalve** [mdn/sprints#1516]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
On the index page, https://developer.mozilla.org/en-US/docs/Web/API, the URL API link goes to https://developer.mozilla.org/en-US/docs/Web/API/URL_API and it should link to https://developer.mozilla.org/en-US/docs/Web/API/URL.

Please drop off the _API from the index URL.

**Comment by wbamberg** [comment]
Thanks for filing! It looks like you have encountered this problem: https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/17. The underlying issue is that there isn't an "overview page" for the URL API. (https://developer.mozilla.org/en-US/docs/Web/API/URL is the page for the URL interface, which is one of the things defined in the URL API. It's confusing.)

I'm going to be filing bugs to add all missing overview pages and will point this bug at that one once I have done so.

**Comment by wbamberg** [comment]
Actually this is being worked on over in https://github.com/mdn/sprints/issues/1047 so I'll close this one.
