### ISSUE TITLE
border-bottom

### ISSUE THREAD

**Issue by nana8** [mdn/sprints#1520]
# Request type
 
[x] Correction or update

# Details

The last CSS demo in the [border-bottom](https://developer.mozilla.org/en-US/docs/Web/CSS/border-bottom) page, 
_border: 4mm ridge rgb(170, 50, 220, .6);_

I think '**a**' is missing 
border: 4mm ridge rgb**a**(170, 50, 220, .6);

**Comment by chrisdavidmills** [comment]
This is a reasonable thought, as a while ago you had to specify `rgba` to be able to use the 4th "alpha" property. But more recently the specs were changed so that `rgb()`  and `hsl()` now accepts the "alpha" property.

So the line is correct. Try loading the page in the latest Firefox or Chrome and adjust the 4th value, and you'll see the opacity of the bottom border change.
