### ISSUE TITLE
Primary tool docs tasks for Firefox 68 (Irene)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1572]
See https://trello.com/c/iix8aZmH/195-primary-tool-updates-eg-console-css-pane-fx-68 for the original trello card.

# Acceptance criteria

1. - [ ] [Add a 'chrome'/'content' filtering for the Browser Console](https://bugzilla.mozilla.org/show_bug.cgi?id=1260877) — documented appropriately.
1. - [ ] [Allow to filter console by regular expression](https://bugzilla.mozilla.org/show_bug.cgi?id=1441079) — documented appropriately.
1. - [x] [Add a way to emulate print media type from DevTools](https://bugzilla.mozilla.org/show_bug.cgi?id=1534984) — documented appropriately.
1. - [ ] [Display an indicator on properties with inactive CSS](https://bugzilla.mozilla.org/show_bug.cgi?id=1306054) — documented appropriately.

**Comment by irenesmith** [comment]
## Added the following to the release notes:

A button has been added to the rules panel of the Page Inspector that allows you to toggle display of any print media queries ({{bug(1534984)}}).

## Added the following to the Page Inspector documentation:

Added information in two places within the inspector documentation. First, I updated the images at the [top of the page](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Examine_CSS_rules) to show the new UI, and then added a video in a section labeled: [View @media rules for Print](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#View_media_rules_for_Print) further down the page that shows the toggle in practice.

**Comment by irenesmith** [comment]
Added the following text to the section of the Inspector documentatation [Examine CSS Rules](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS#Examine_CSS_rules) as follows:

A warning icon appears next to unsupported CSS properties or rules that have invalid values. This can help you understand why certain styles are not being applied. In the following example, a spelling error, "background-colour" instead of "background-color" has made the rule invalid.

I also added an image to go with the text.

I also added a comment to the release notes.
