### ISSUE TITLE
WebExt proxy and webrequest docs tasks for Firefox 68

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1580]
See https://trello.com/c/khmwRVQp/209-proxy-and-webrequest-api-related-tasks-fx-68 for original trello card.

# Acceptance criteria

1. - [x] [Allow proxy.onRequest to set Proxy-Authorization header and connection isolation token, handle this in Necko](https://bugzilla.mozilla.org/show_bug.cgi?id=1545420) — documented appropriately.
1. - [x] [Expose private browsing flag on proxy/webrequest details](https://bugzilla.mozilla.org/show_bug.cgi?id=1545163) — documented appropriately.
1. - [x] [add cookieStoreId to webRequest APIs](https://bugzilla.mozilla.org/show_bug.cgi?id=1391992) — documented appropriately.
1. - [x] [Emit console warning for deprecated proxy APIs](https://bugzilla.mozilla.org/show_bug.cgi?id=1545841) — documented appropriately.
      - [x] Create pull request to update BCD for deprecated APIs
      [Update associated example and create pull request](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/1891)
1. - [x] [support incognito in request filter for webrequest and proxy](https://bugzilla.mozilla.org/show_bug.cgi?id=1548177) — documented appropriately.

**Comment by irenesmith** [comment]
A deprecation notice has already been added to both proxy.register and proxy.unregister. Directly below the generic deprecation notice, I added an image of the console error to: [proxy.register](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/register) and [proxy.unregister](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/unregister) with the following text:

This method has been deprecated in Firefox 68 and will be removed from Firefox 71. In Firefox 68 or later, calling this method logs an error message to the console

**Comment by irenesmith** [comment]
Added the following new values to [proxy.RequestDetails](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/RequestDetails):

cookieStoreId
string. The cookie store ID of the current context.

incognito
    boolean true for private browing requests

Both values are also included in the Release notes.

**Comment by irenesmith** [comment]
Added the following to [webRequest.RequestFilter](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/RequestFilter):

incognito Optional
    boolean. If provided, requests that do not match the incognito state (true or false) will be filtered out.

This is also included in the release notes.

**Comment by irenesmith** [comment]
Split out the changes for the example to: [MDN/Sprints 1891](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/1891)

**Comment by jmswisher** [comment]
@irenesmith The first AC item doesn't appear to be done, so continuing this to next sprint. Let me know if that's incorrect.

**Comment by irenesmith** [comment]
I missed that one. Here are the changes I made for it:

I have added the following to the definition of proxyInfo:

proxyAuthorizationHeader
string. The authorization header value for the request attempt. Contains the credentials to authenticate a user agent to a proxy server.

connectionIsolationKey {{optional_inline}}
string. An optional key used for additional isolation of this proxy connection.

Please check what I've added and let me know if there is more I should say here. As far as this issue is concerned, I realize it is the bare minimum of information but I think it covers this change.

I'm not sure I understand how you would like to present additional information that should go in other places to describe the consequences of the change. If what I have is right, a pointer to where else this information needs to go and a rough description of what Add-on developers need to know would be greatly appreciated. If you could add the information to this issue, or send me an email with the information, I will create an issue in the documentation repo on GitHub to track the additional changes.
