### ISSUE TITLE
Missing pages for HTTP status-codes 506, 507, 508, 510

### ISSUE THREAD

**Issue by amosonn** [mdn/sprints#1669]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status has 506, 507, 508 and 510 as possible HTTP status codes, with links to pages. Pages are missing, and these status codes also don't appear on the sidebar for other HTTP status code pages.

**Comment by wbamberg** [comment]
I've added some pages for these status codes:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/506
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/507
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/508
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/510

They are a bit obscure.

@Elchi3 , since you I think wrote most of the original HTTP docs, would you mind reviewing? Or please let me know otherwise and I'll find another victim.

**Comment by Elchi3** [comment]
Hey Will, thanks for writing these pages! I think this is good enough given how obscure these are. I don't think we would need anything more here, it is mainly just to have them documented for completeness sake, I would think. r+ and closing this.

**Comment by wbamberg** [comment]
Thanks Florian!

> I think this is good enough given how obscure these are

Yeah, that was kinda how I felt too :).
