### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Syntax

### ISSUE THREAD

**Issue by Thegg53** [mdn/sprints#1680]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Syntax
There is a wrong image to display the output of css.
The output should have the li elements with color black instead of red
![Screenshot from 2019-05-29 21-25-03](https://user-images.githubusercontent.com/17069668/58588742-42258980-8258-11e9-84c9-42f0d2aac1eb.png)

Here is what it should return:
![Screenshot from 2019-05-29 21-26-08](https://user-images.githubusercontent.com/17069668/58588805-6b461a00-8258-11e9-8833-d0117e295ea1.png)

Fortunately, I already know a bit of css, otherwise this would make it hard to start

**Comment by Thegg53** [comment]
Also, the Hello World! text should be black, since it uses colour instead of color in your example.

**Comment by jmswisher** [comment]
Fun one! Thanks @Thegg53 for reporting this!

The output shown in the page is actually generated from the code snippets in the page. However, due to a quirk in how that's implemented, it was pulling in _all_ the code snippets, some of which override what's supposed to be in the displayed example. (The use of "colour" is an intentional error; see the section "Active learning: spot the declarations".) I've fixed things to limit what's pulled in to the "live" example.
