### ISSUE TITLE
Missing `Payload body` in Glossary

### ISSUE THREAD

**Issue by ioggstream** [mdn/sprints#1723]
# Request type
- [x ] New documentation
- [x ] Correction or update

# Details
The HTTP Glossary misses  "Payload body" defined in RFC7230.

Payload body is the body of the originating message, which may then
be altered via Transfer-Encoding by the HTTP Intermediaries.

# Further info

All references to the now obsoleted term `entity` should be properly redirected to
`representation` which is defined in  
https://tools.ietf.org/html/rfc7231#section-3

**Comment by hamishwillee** [comment]
With respect to the "Further info", entities have indeed been deprecated.
I have fixed this, as described in https://github.com/mdn/sprints/issues/2203#issuecomment-735584757 - ie they are still mentioned, but

**Comment by hamishwillee** [comment]
Done in https://wiki.developer.mozilla.org/en-US/docs/Glossary/Payload_body

@chrisdavidmills @ioggstream OK? This is actually kind of hard to explain because the term payload body is synonymous with message body unless transfer encoding is used _and_ the encoding requires additional data in the message body.

**Comment by chrisdavidmills** [comment]
Looking good to me; closed!

@ioggstream feel free to chime in if you have any other comments.
