### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

### ISSUE THREAD

**Issue by somestuff** [mdn/sprints#1725]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In regards to page:
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
 Near the bottom under specification there are listed the to level of api 1 & 2 as obsolete with no
link to the current apis 3 & 4

https://www.w3.org/TR/2018/REC-selectors-3-20181106/
&
https://www.w3.org/TR/selectors-4/

It is confusing as a novice to read that the supplied documentation is obsolete.  Can there be updated the Specification table to read with the addition of the current api?

Thank for you time, William Warren

**Comment by chrisdavidmills** [comment]
Hi @somestuff,

Thanks for reporting this; yes, we have quite a lot of obsolete spec links, and are soon hoping to replace the manual tables with a more automated solution.

In this case, I have just replaced the obsolete spec links with a link to `querySelector()`'s definition in the WHATWG DOM Living Spec. I think that's the most relevant one now, especially since the W3C is stopping publishing snapshots of the relevant WHATWG stuff in this area.
