### ISSUE TITLE
Correction required to Promises article

### ISSUE THREAD

**Issue by krislondon** [mdn/sprints#1843]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

In your article "Graceful asynchronous programming with Promises" the sections titled "Responding to failure" and "Chaining the blocks together" imply that an erroneous URL will cause the catch callback to initiate. However, this does not work since, as MDN has pointed out another article titled "Using fetch",

  "The Promise returned from fetch() won’t reject on HTTP error status even if 
  the response is an HTTP 404 or 500. Instead, it will resolve normally (with ok 
  status set to false), and it will only reject on network failure or if anything 
  prevented the request from completing."

Therefore, it is required of the programmer to check the results of the fetch call in either promise2 or promise3 (such as, in promise3, checking the size of the Blob - if it is zero, then there must have been an error), and if an error occurs throwing an error in *that* promise.

If I am mistaken, I apologize for the inconvenience.

**Comment by chrisdavidmills** [comment]
Article in question: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises

**Comment by chrisdavidmills** [comment]
I can't believe it has taken so long for us to get to this one! Indeed you are right @krislondon — the fetch examples were all working incorrectly because of the facts you have reported.

I have gone through all of the examples in the cited article, and the async/await one that follows it, and added in a block that serves to check the status of `response.ok` and throw an error if it returns `false`. The examples now work in that they throw an error when the URL 404s.

I've updated both the code blocks in the articles, and the full examples on GitHub.

Let me know if you spot any other fetch examples around MDN that need fixing up.
