### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

### ISSUE THREAD

**Issue by kdunagan-od** [mdn/sprints#1879]
# Request type

- [x] Correction or update

# Details

I'm very sorry if this is not the place for this kind of request. Please let me know if this isn't the right place for this comment.

Anyways, the webpage https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent says that initEvent is deprecated. I'm under the assumption that this means that initEvent will be eventually deleted from the webAPI. I'm a software developer who's worried that the eventually deletion of this method would break the programs I'm in charge of. Is there a timeframe for the intent to delete this function?

**Comment by jmswisher** [comment]
Hi @kdunagan-od ! Yours is a good question, but since it has to do with what will happen in the DOM standard, you're more likely to get a clear answer in the [WHAT-WG's DOM repo](https://github.com/whatwg/dom/). 

I notice that the [section of the DOM spec about initEvent()](https://dom.spec.whatwg.org/#dom-event-initevent) has a note that mentions, "It has to be supported for legacy content." This makes me think that there is enough such legacy content that it's not going away any time soon. And even if/when it is removed from the spec, it will take a good while longer before it's removed from browsers. But that's all just speculation on my part.
