### ISSUE TITLE
missing queryCommandValue documentation

### ISSUE THREAD

**Issue by andrevenancio** [mdn/sprints#1885]
there's a page 404 on `queryCommandValue`

**Comment by chrisdavidmills** [comment]
What page did you find this 404 on?

**Comment by andrevenancio** [comment]
Hey, sorry for the lack of explanation above.

So on this [URL](https://developer.mozilla.org/en-US/docs/Web/API/Document)
If you click on the `Document.queryCommandValue()` link it takes you to [this](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandValue) page.

**Comment by chrisdavidmills** [comment]
Right, ok. Yeah, someone has filled in the summary on the Document page, but not created the actual method page.

Would you be interested in helping us to create this page?

**Comment by andrevenancio** [comment]
Hey, yeah I wouldn't mind, but I have no clue on where to start. Is there any guidance available to have a look through it?

**Comment by chrisdavidmills** [comment]
There are a whole bunch of guidelines at https://developer.mozilla.org/en-US/docs/MDN/Contribute. A huge number, in fact.

I think probably an easier way to handle it is like so:

1. You need an MDN user account, then I need to give you page creation permissions, so that when you click the red link, it gives you the page creation page, rather than a 404 page.
2. On the on page creation page, you fill in all the content for the page.
3. the easiest way to get the content in the correct structure is to grab an existing method page that has the correct structure, copy the entire content, paste it into the new page, and then change it so it is about the correct method for that page.
4. A good example of a correctly structured method page is https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
5. Have a go at it and see how you get on, and feel free to ask me for help or reviews if you need it.
