### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript

### ISSUE THREAD

**Issue by orochitian** [mdn/sprints#1889]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/28913785/62177361-3b5de480-b377-11e9-804c-74d8fd3ffe75.png)

![image](https://user-images.githubusercontent.com/28913785/62177382-4fa1e180-b377-11e9-8cda-04ef2e4d18a5.png)

这两个怎么能单独列出来？他们都是中国下属的省，怎么能在国家中列出！！！

**Comment by chrisdavidmills** [comment]
Bottom line translated as "How can these two be listed separately? They are all provinces of China, how can they be listed in the country! ! !"

Where did you find this drop-down menu?

**Comment by orochitian** [comment]
> Bottom line translated as "How can these two be listed separately? They are all provinces of China, how can they be listed in the country! ! !"
> 
> Where did you find this drop-down menu?

我在页面底部的调查问卷中看到这个列表。
日期是 2019-07-31
但是今天我找不到这个调查问卷了

**Comment by orochitian** [comment]
> Bottom line translated as "How can these two be listed separately? They are all provinces of China, how can they be listed in the country! ! !"
> 
> Where did you find this drop-down menu?

如果你是mozilla的相关工作人员，希望可以及时修复这个问题。
这个错误或许是因为文化差异或其他什么导致的，我并不想把它升级到任何政治层面。
但是中国及中国公民在这个问题上的立场是非常坚定的。希望得到你们的理解与支持！
同时，也希望您能告诉身边的同事、朋友，香港、澳门、台湾都属于中国领土。这一点毋庸置疑。
谢谢。

**Comment by orochitian** [comment]
截止今天，这个问题依然没有修复

**Comment by chrisdavidmills** [comment]
> 我在页面底部的调查问卷中看到这个列表。
日期是 2019-07-31
但是今天我找不到这个调查问卷了

This means that the problem is in the developer survey we are running at the moment.

@schalkneethling , can I pass this to you? It looks like the language drop selector in the developer survey has a problem because some Chinese provinces are listed in the country drop down. Is this something we can fix, or are you using some kind of third party code for this?
