### ISSUE TITLE
Improve History API docs: complete API ref, create proper landing page, etc.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1892]
The History API is only a small API, but it'd be nice to get the reference docs sorted out, finalised, and into a proper structure.

* Most of https://developer.mozilla.org/en-US/docs/Web/API/History_API reads like a tutorial. This needs to be turned into a proper landing page.
* The tutorial content at the above URL should be turned into a "Using the History API" tutorial page.
* The https://developer.mozilla.org/en-US/docs/Web/API/History interface has a number of member pages missing that should be created.
* The sidebars for these pages need sorting out.

# Acceptance criteria

- [x] Tutorial page created
- [x] Proper API landing page created
- [x] Kuma PR created
- [x] All methods and properties properly documented

**Comment by irenesmith** [comment]
Added the following pages:
[window.history.back()](https://developer.mozilla.org/en-US/docs/Web/API/History/back)
[window.history.forward()](https://developer.mozilla.org/en-US/docs/Web/API/History/forward)
[window.history.go()](https://developer.mozilla.org/en-US/docs/Web/API/History/go)

**Comment by irenesmith** [comment]
This page for the [History object](https://developer.mozilla.org/en-US/docs/Web/API/History) already exists. Checking it to make sure that all properties and methods are defined.

**Comment by irenesmith** [comment]
Created a tutorial page [Working with the History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API) but it needs editing because it is just the extra copy removed from the History API landing page.

Thanks to Chris, I stopped the redirection for a couple of the History object methods to the original landing page for the API to the moved content.

**Comment by irenesmith** [comment]
Created [history.replaceState](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) page to define the replaceState method.

**Comment by irenesmith** [comment]
Created pages for:
  - [history.state](https://developer.mozilla.org/en-US/docs/Web/API/History/state)
  - [scrollRestoration](https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration)

Created a [BCD PR 4801](https://github.com/mdn/browser-compat-data/pull/4801) to update the BCD for the history.back method because it was incorrectly pointing to https://developer.mozilla.org/docs/Web/API/History/url

**Comment by irenesmith** [comment]
All work except the Kuma PR has now been done.

**Comment by irenesmith** [comment]
[Kuma PR](https://github.com/mdn/kumascript/pull/1241)
