### ISSUE TITLE
CSS Subgrid Firefox 69

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1899]
See https://trello.com/c/Yo7oH9PY/6-css-grid-subgrid-fx-69 for original trello card

# Acceptance criteria

1. - [x] [[css-grid-2] Enable subgrid by default in Nightly (and early beta?)](https://bugzilla.mozilla.org/show_bug.cgi?id=1496502) (just BCD update needed, and maybe experimental features?)

**Comment by rachelandrew** [comment]
So it seems that the change here is to enable subgrid by default (no flag required) in Nightly. I don't think it is shipping in 69 into Firefox, so I don't think there is anything to do given I've already documented the feature.

Unless we have a way to indicate "only in Nightly" in the compat data?

**Comment by chrisdavidmills** [comment]
@rachelandrew so for this work, I'd like to:

* Add entries for the subgrid value on the grid-template-columns and grid-template-rows ref pages (don't worry about an example yet, maybe just link to the subgrid page you wrote in the grid guides? Also add the value to the /data repo entries for them).
* Add a BCD entry for the value, for each of them. You should specify that it is available behind a flag in 69 onwards using a [flags field](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables#Including_browser_preferences_or_flags), and perhaps also [include a note](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Structures/Compatibility_tables#Including_a_footnote) to say it is enabled by default in Nightly only.
* See if the [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#CSS) entry for Subgrid needs updating at all?

Usually we wouldn't go to quite this much trouble for a feature that is so early on in implementation, but subgrid has a big buzz around it.

**Comment by rachelandrew** [comment]
BCD PR https://github.com/mdn/browser-compat-data/pull/4657

**Comment by rachelandrew** [comment]
Data PR https://github.com/mdn/data/pull/382

**Comment by rachelandrew** [comment]
@chrisdavidmills While doing this I've found a lot of the pages have a polyfill added, which I started to remove, however I note that some also have hidden text referring to https://discourse.mozilla.org/t/mdn-rfc-001-mdn-wiki-pages-shouldnt-be-a-distributor-of-polyfills/24500, so I don't really understand what is going on here? https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column (edit it and you'll see the hidden section).

The person who added this, only seems to have ever made edits in order to add it: https://developer.mozilla.org/en-US/dashboards/revisions?user=motine

I do not think we should be encouraging people to add stuff like this to the pages. As it looks like an endorsement.

**Comment by rachelandrew** [comment]
Removed the polyfill sections, added a link to the level 2 spec, added subgrid as an allowable value, linked to the subgrid page from `grid-template-columns`, `grid-template-rows`. Once the data and BCD shows up that should I think be most things for now.

**Comment by chrisdavidmills** [comment]
Nice one Rachel. I've reviewed and merged the data/ updates. So once the BCD is sorted and it all shows up, we can defo close this, yes.
