### ISSUE TITLE
Research online assessments to determine what we should do for the learning area

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1924]
# User story
As an MDN writer, I want to know what constitutes an effective online assessment, so I can start adding useful assessments to the learning area/learning pathway.

# Acceptance criteria

1. - [x] Existing online assessments researched, to see what others do, and what works.
2. - [ ] Key people asked about their thoughts and experience of online learning assessments, and what works (e.g. Jess, Rachel, others).
3. - [x] Plan written up detailing what our assesments should ideally look like, and what we can get done for the MVP release.

**Comment by chrisdavidmills** [comment]
Online assessments researched, and some thoughts written up at https://docs.google.com/document/d/1qvvJxDQoqztyxmtWCJUysy7LIeePy5Bg7URUz0mwbpQ/edit#

@atopal , @rachelandrew I was wondering if you had any thoughts on this?

**Comment by rachelandrew** [comment]
The recent couple I did, I just linked to the solution on GitHub, suggesting they try it out for themselves first. I don't know why we need to only give them the guide if they ask for it - is this because colleges are also using this material wholesale with students so don't want them able to just look up the answer?

We probably need to identify who is using these, and what the aim of the marking guides is. Outside of that I think what would be sensible is:

1. Have the solution available for all assessments in a standard place.
2. Encourage people to try it for themselves first.
3. Explain that if they don't understand why it worked they should put their code into CodePen or similar before posting to the forum (this is good practice to get into if they want to ask for help anywhere)
