### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types

### ISSUE THREAD

**Issue by Mookiepiece** [mdn/sprints#2001]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Some data types  occurred in https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types
do not occurred in https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units and https://www.w3.org/TR/css3-values

such as **< basic-shape>< blend-mode>< filter-function>**

I do not know why those data types occurred in this page
may be they are complex and need to open a new page to explain them 
and then somebody referred their pages to this page
but what about those red links?they do not have their own page.

I suggest those complex data types(which not defined in www.w3.org/TR/css3-values) should be put into another group and an additional note is needed

**Comment by rachelandrew** [comment]
@chrisdavidmills so the issue here is that some types are defined in their own spec, they aren't covered by Values and Units.

The referenced page is Types, so probably should cover all types (whether in Values and Units or elsewhere). However the specs it links to are only the Values and Units ones.

To further complicate matters we do have a Values and Units page which then links to a lot of the specs that define types. In addition to those in Values and Units. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units

My proposal would be to make the Types page cover all types, perhaps breaking them down into where they are defined. Then make Values and Units cover Values and Units. I think that would sort the confusion.

@Mookiepiece the red links just mean that documentation hasn't been written for those yet.

**Comment by Mookiepiece** [comment]
It would be a hard work to collect all those Types, but less profit, we don't read them much. at least I know my guess is not wrong now, my suggestion is rewrite this page to an introduction instead of a reference table.

**Comment by rachelandrew** [comment]
@chrisdavidmills I think there are other issues that relate to Types, eg: 

- https://github.com/mdn/sprints/issues/3243
- https://github.com/mdn/sprints/issues/1128

So maybe I do as I've just done for selectors and tidy this up. I think I put together quite a lot of the Values and Units page, and that's actually an explanation of what all these are. So Types is probably more of a listing but maybe broken down into the various groupings with clarity as to which spec they are from.

**Comment by chrisdavidmills** [comment]
Thanks Rachel, I think your proposal here is sound. I'm happy as long as we use a consistent approach (i.e. along the same lines of the work you recently did on the pseudos page), and consider usefulness to the reader as the top priority. I mention this last bit because the only slight concern I have here is claifying what spec different types are from. I think this is fine, as long as it doesn't take priority over or get in the way of logical functionality groupings, which I think will matter the most to our readers.

**Comment by rachelandrew** [comment]
The Values and Units spec has logical groupings, and then a section for types defined elsewhere so I am following the same approach here: https://drafts.csswg.org/css-values-4/

The ones defined elsewhere are fairly well grouped anyway - images, color etc.

**Comment by chrisdavidmills** [comment]
OK, fair enough.

**Comment by rachelandrew** [comment]
@chrisdavidmills working on this locally as it's quite a list, but there are a number of these types listed in the index already and that aren't yet listed which we won't have a page for. Are we happy that these are just all red links or should I not xref anything that doesn't have a page? Some of them would benefit from a page if they are quite complex. Others the one line description I'm writing might be enough.

**Comment by chrisdavidmills** [comment]
This is a good question. Our normal practice would be to have a separate page for everything, but I can understand that being overkill if the types only require a single line.

I'd perhaps do this:

1. For every type, include a name and a one line description, but don't link the name.
2. For simple ones only requiring one line, leave it at that
3. For complex ones that need a sepaate page, include an extra line "For more complete information, see our <TYPE-NAME> page", and link "<TYPE-NAME>" to the separate page. Ones that have not yet been writen can just remain red for now.

**Comment by rachelandrew** [comment]
@chrisdavidmills so I've refactored that Types page to remove the index and do a more useful listing of commonly used Types: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types There are more that could be added, but I've linked p all the ones we do have documented already. I think I wrote a few pages when I did the work on Values and Units a while back.

**Comment by chrisdavidmills** [comment]
This is looking really good, thanks @rachelandrew . I've given it a bit of a copy edit. The only thing I'd like to see you do now is put in a link to the actual spec document wherever you include a spec name. After that, I think we can call this one done.

**Comment by rachelandrew** [comment]
@chrisdavidmills I've just linked those specs up.

**Comment by chrisdavidmills** [comment]
Perfect, I think we can close this one now?
