### ISSUE TITLE
Modernize the page on the Visual Rendering Model

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2020]
https://developer.mozilla.org/en-US/docs/Web/CSS/Visual_formatting_model

In working on a guide to the inline formatting context I took a good look at the above page. It has some errors, and also documents the model as it was in CSS2, without mentioning the way this is referred to in Level 3 models. It's potentially a bit confusing and needs to explain the interaction with newer layout methods, and the two value syntax for display.

**Comment by rachelandrew** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Visual_formatting_model

This was reasonably hard, the original text was pretty much just the CSS2 spec copied over. As this information now lives in various places in Level 3 specs in addition to referring to CSS2 I've tried to outline the relevant terminology and then link to the other relevant places in our docs. How successful I've been I am not sure, so let me know if there are things I've not included you think should be.

**Comment by chrisdavidmills** [comment]
This is a really interesting read Rachel, and I think it make a lot of sense. I learned a lot.

I gave it a good edit, and had a couple of questions:

* You talk about absolute positioning — "In the absolute positioning model, a box is removed from the normal flow entirely and assigned a position with respect to a containing block." Does this also cover fixed positioning? Surely fixed positioning works the same, except that it is assigned a position with respect to the viewport instead of a containing block? If I am not correct, then it might still be worth adding a note to explain where fixed position sits in all of this.
* "In specifications, block boxes, block-level boxes, and block containers are all referred to as block boxes in certain places. These things are somewhat different and the term block box should only be used if there is no ambiguity." — wow, I never knew this. In fact, up to this point in the article I'd been changing your usage of "block-level" to just "block", as I thought they were totally interchangeable. Have I messed up any explanations? And should this explanation come earlier in the article? It seems pretty fundamental.

**Comment by rachelandrew** [comment]
> " In fact, up to this point in the article I'd been changing your usage of "block-level" to just "block", as I thought they were totally interchangeable. Have I messed up any explanations?"

If I used block-level at any point that's very specific and I wouldn't have done so if it wasn't important so if you could put them back! We could perhaps refernce this in the note about block boxes and link to the section perhaps?

With regard to abspos, yes fixed positioning is included, but that's not a different model. It's essentially the same as absolute positioning.

**Comment by chrisdavidmills** [comment]
> If I used block-level at any point that's very specific and I wouldn't have done so if it wasn't important so if you could put them back! We could perhaps refernce this in the note about block boxes and link to the section perhaps?

Done, and done. Sorry about that!

> With regard to abspos, yes fixed positioning is included, but that's not a different model. It's essentially the same as absolute positioning.

OK, I've added a couple of bits to that section to make it clear that fixed positioning is also included in that.
