### ISSUE TITLE
Update "Whitespace in the DOM" article

### ISSUE THREAD

**Issue by violasong** [mdn/sprints#2039]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The article, [Whitespace in the DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace_in_the_DOM), is mainly about the use case of writing DOM manipulation code. It could be updated to focus on the more common case of unexpected whitespace in CSS layout debugging. 

(This discussion came out of [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1568847) on the DevTools Inspector's whitespace node feature. )

This article by @captainbrosset does a great job of explaining the practical details of how whitespace affects web layouts, and parts of this could be adapted for the MDN article.
https://patrickbrosset.com/articles/2016-10-21-when-does-white-space-matter-in-HTML.html

We also suggest that the article could be moved under CSS on MDN.

**Comment by chrisdavidmills** [comment]
@violasong It's taken a while, but I've finally gotten around to updating this article, with some of @captainbrosset 's article content:

https://wiki.developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

Let me know what you think! I have kept it in the DOM page tree for now, because it covers more than CSS, so I was not sure it was suitable to move it inside Web/CSS/

**Comment by violasong** [comment]
This is such a huge improvement - thanks so much Chris!!

**Comment by chrisdavidmills** [comment]
@violasong you're welcome; sorry it took so long to get to!
