### ISSUE TITLE
display page needs to be refactored to make it grokable

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2053]
There are the tried and true values for display that devs may want to use, but their definitions are elusive. Take for example "inline-block"

While the page is technically accurate, it leaves out what I think most people might be looking for.

**Comment by rachelandrew** [comment]
Hi @estelle I've already done a load of work on this locally, as prep for the two values of display which has now been bumped into Fireox 70, so I reprioritised it, but I've actually done a lot of the prep work in the last sprint to make the changes here and to other places.

See: https://github.com/mdn/sprints/issues/1894

Obviously, up to @chrisdavidmills but it seems you'd be re-doing my work here :)

**Comment by chrisdavidmills** [comment]
@ rachelandrew ah, so you did a bunch of the sorting out of this page as a precursor to that bit of work that you then didn't do because it slipped to Fx 70? Thanks for the heads-up.

I think it is still worth @estelle looking at the page to see if she thinks it needs anything else. I believe this ticket is one of the ones she filed when she was going through a load of MDN CSS stuff recently as she was writing her workshop slides.

**Comment by rachelandrew** [comment]
well I did a bunch of stuff locally which I then stopped doing. I think this page needs work to make the dual nature of display more understandable, which is what I was working on. So if Estelle looks at it now, I haven't made the edits yet, so I'm going to then change it again which doesn't seem to make a lot of sense!

**Comment by rachelandrew** [comment]
my next AEA talk is essentially just about display, so I've done a lot of work here it would be worth using in the MDN docs I think.

**Comment by chrisdavidmills** [comment]
Closing this, in favor of newer issues around display.
