### ISSUE TITLE
[WebExt] WebRequest docs tasks, Fx 70

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2134]
Trello: https://trello.com/c/khmwRVQp/209-proxy-and-webrequest-api-related-tasks-fx-70

# Acceptance criteria

1. - [x] [Support intercepting WebSocket connections from WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1373639) (historic bug; need a mention on the webRequest page that websockets are supported (see [comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1373639#c3) of the bug))
2. - [ ] ~~[add webrequest redirect flags for onBeforeRedirect](https://bugzilla.mozilla.org/show_bug.cgi?id=1462006) (historic bug; needs a change to the webRequest page; ask Shane for details of what exactly)~~
3. - [x] [webRequest.onBeforeRequest/onHeadersReceived fetch redirect gets blocked due to bogus CORS error](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965) (added to 69, but was not done)
4. - [x] [Emit console warning for deprecated proxy APIs](https://bugzilla.mozilla.org/show_bug.cgi?id=1545841) (example still needs to be updated; see [end of comment 10](https://bugzilla.mozilla.org/show_bug.cgi?id=1545841#c10))

**Comment by rebloor** [comment]
@chrisdavidmills In following up [add webrequest redirect flags for onBeforeRedirect](https://bugzilla.mozilla.org/show_bug.cgi?id=1462006) I got a reply from Shane noting that "This is not a closed bug, so you should be looking at it." A further note indicated that bugbug thought this was a regression. Should I remove it from the worklist on this issue?

**Comment by rebloor** [comment]
@chrisdavidmills FYI for [webRequest.onBeforeRequest/onHeadersReceived fetch redirect gets blocked due to bogus CORS error](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965) Steve confirmed that the issue has been fixed and, therefore, as the documentation was to cover the case where it wasn't fixed, no changes are needed. He removed the dev-docs-needed flag.

**Comment by rebloor** [comment]
@chrisdavidmills looks as though we are in a bit of a loop with [Support intercepting WebSocket connections from WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1373639). I've made another request for information on the bug, however, my reading of the bug is that  "if we support intercepting websockets we need to document it, but were not sure that we do or how we do"? And I fear that figuring out how to answer that question myself could take some time.

**Comment by chrisdavidmills** [comment]
@rebloor bleh, I don't think it's worth wasting loads of time on this one, if the engineers aren't really sure what to say. Let's revisit this later on if someone else starts to make a load of noise about it.

For now, maybe just update the intro paragraph like you suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1373639#c8, so at least there is a mention of it.

**Comment by rebloor** [comment]
Thanks @chrisdavidmills, done, which clears the last task off this issue.
