### ISSUE TITLE
U - [HTTP] Docs requirements for SameSite=Lax by default

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2152]
# User story
As a web developer, I want to reads docs about the new default SameSite setting, so I can find out how this affects my work.

This contributes to MDN's completeness, and the KR "Increase traffic 5% y/y". MDN users need this information to be able to do their jobs effectively going forward.

# Background

Same site cookies were shipped a few versions ago. Browser are now agreeing on a proposed change to treat all new cookies as SameSite=lax by default

This is interesting for 2 reasons:

1. We need to do this to avoid compat issues if other browsers all do it
2. It is an opportunity to work with other vendors to eliminate entire class of security vulnerabilities (CSFR)

We are trying to line up changes to coincide with other browser vendors, and this includes documentation. Chrome are aiming for about Chrome 78, available behind pref since 76.  We are not yet 100% sure what Firefox version it will be enabled in, but it'll probably be Fx 71, or maybe even 70.

Docs updates needed on

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies (SameSite section)
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie (mention update to default behavior)

New page needed

* SameSite cookies page; will explain the change in detail, explain the errors you'll see in the console, and give developers advice about what they should do going forward. This will satisfy the need talked about at https://bugzilla.mozilla.org/show_bug.cgi?id=1620334. 

We may also do with a hacks post to explain the story (how we fixed CSRF forever! google drove it, we thought of it) and what difference this wil make for web devs. This would also coincide with a more technical write up on the Moz sec blog. If these happen, the engineers will write them and we can help edit them.

Mark Goodwin was the engineering contact for this, now it's being implemented by Andrea Marchesini (baku). Ask him for help if needed.

# Acceptance criteria

1. - [x] [Prototype SameSite=Lax by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1551798) (see also the [intent to implement](https://groups.google.com/forum/#!topic/mozilla.dev.platform/nx2uP0CzA9k)) (Fx 69, behind a pref at this point)
2. - [ ] [Enable sameSite=lax by default on Nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1604212)
3. - [ ] [Implement sameSite lax-by-default 2 minutes tolerance for unsafe methods](https://bugzilla.mozilla.org/show_bug.cgi?id=1608384)
4. - [ ] [Need MDN landing page that SameSite console warnings can reference](https://bugzilla.mozilla.org/show_bug.cgi?id=1620334)
5. - [ ] MDN docs written as described above.
6. - [ ] hacks and sec blog content reviewed/edited (not sure if this is still needed, will ask)

[Enable sameSite=lax by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1617609) tracks the release of these changes in final release Fx. Bear in mind that we want to get this done by Fx 76 beta, so we will need to delay communicating that this is enabled in release till a later sprint).

**Comment by chrisdavidmills** [comment]
I'm clearing the milestone and attachment to Fx71 for now; I was told this would be a big thing to do probably around Fx71, but then heard nothing else about it.

**Comment by chrisdavidmills** [comment]
More information from chatting to Mike Conca:

* Platform team wants this by the time Fx 76 goes to beta, which will be April 7th, so it needs to go into the Charlie-Delta sprint.
* On the new page talked about in the description, we need information along the lines of https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite

**Comment by Elchi3** [comment]
I've started a page here in case folks need a URL for the console message now https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Will add some more examples and describe the planned change some more.

Also this hasn't landed in Firefox yet, so I haven't updated the BCD for it yet.

**Comment by Elchi3** [comment]
So, I think this is done for the moment. mconca seems to be happy with the page (see https://bugzilla.mozilla.org/show_bug.cgi?id=1620334#c4) and we will need to continue this work when it actually lands (probably next sprint with Firefox 76).

**Comment by Elchi3** [comment]
Given https://blog.chromium.org/2020/04/temporarily-rolling-back-samesite.html, I think this might not be shipped in Firefox either. So, maybe this should be parked instead of scheduled for the next sprint.

**Comment by chrisdavidmills** [comment]
@Elchi3 thanks for the heads up.

**Comment by chrisdavidmills** [comment]
I'll put it in 76 for now, and we can remove it when the official line comes in.

**Comment by chrisdavidmills** [comment]
Confirmation that this is being pushed out to a future version. We'll park it for now.

**Comment by hamishwillee** [comment]
- According to [Chromium SameSite updates](https://www.chromium.org/updates/same-site) this was enabled by default on all versions after 80 (stable) - i.e retrospectively enabled on a bunch of versions once v84 came out). Generally the version it is said to have appeared in though is v84 (ie in [samesite cookies explained](https://web.dev/samesite-cookies-explained/)).
- BCD for Chromium appears to be up to date with this the former point - listing support from version 80. It is also up to date for Firefox - indicating the value is behind a preference. 
- This appears to not be mentioned in the [experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features)
- There is a slight mix of assuming new behaviour and old behaviour in the docs. In particular [Headers > Set-Cookie> SameSite](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) feels to be mostly about the new behaviour while its parent feels to be more "old" behaviour.

- Doc: [Headers > Set-Cookie> SameSite](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite). 
  - Does not state what happens if `SameSite` not specified at all. Arguably it shouldn't ... but IMO it should.
  - Would be good if it had links to what a "first-party context" vs "third party context" means - perhaps [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Third-party_cookies), but check glossary too.
  - in [Lax](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#Lax) it isn't clear what is meant by top level navigations.  I believe this means that when you click a link to go to a site, the cookies for that site will be downloaded following the GET request, but if you just looked at an image then you wouldn't get the cookies. I think this text is therefore not quite right:
    > Cookies are allowed to be sent with top-level navigations and will be sent along with GET request initiated by third party website. This is the default value in modern browsers.

    it should be something like

    > The cookie is withheld on cross-site subrequests, such as calls to load images or frames, but is sent when a user navigates to the URL from an external site (i.e. when following a link). This is the new default value in the standard (see "SameSite: Defaults to Lax" feature in Browser Compatibility).
  - Worth adding a link to https://web.dev/samesite-cookies-explained/ - it is a good explanation. 
  - Common warnings - might be better as screenshots. I think I need to verify these. 

- Doc: [Headers > Set-Cookie](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie). 
  - [Syntax](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Syntax)
    ```
    Set-Cookie: <cookie-name>=<cookie-value>; SameSite=None
    ```
    Does note yet have the `Secure` which is also needed.
  - [Attributes](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Attributes)
    - Should link to SameSite sub-doc
    - Should note what happens if SameSite not defined AND in Lax option, that this is default.
    - The Note "Browsers are migrating to have ..." is good, but perhaps point to BCD line "SameSite: Defaults to Lax" and also show the preferred setting for this SameSite header.
       - More precisely, spelling it out [like this would be good](https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite):
         - Cookies without a SameSite attribute will be treated as SameSite=Lax.
         - Cookies with SameSite=None must also specify Secure, meaning they require a secure context.
    - Perhaps also update `Secure` section to note that it must be set if SameSite is None (maybe not :-)

- Doc: [HTTP > Using HTTP cookies](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie). 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)
  - [SameSite attribute](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie). 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_attribute) - has same note "Browsers are migrating to have ...". If this changes/is updated then also update here. Also note the default in this.
  - [Third party cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Third-party_cookies) - make note that you can control how these are used by the server.
  - [See also](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#See_also) - add link to same-site doc.

**Comment by hamishwillee** [comment]
@chrisdavidmills I have updated this as above. Specifically this now updates the three main docs that mention SameSite to reflect the new behaviour, and point people to the BCD at end of pages to check specific versions. Details above.

The impact of this change is that the docs will not go out of date with new releases. So when FF accepts the bug the BCD and release note will update, but the docs will be correct.

I think this can probably be closed with a new doc opened when this feature is actually in the live version.

**Comment by chrisdavidmills** [comment]
@hamishwillee this is looking great, thanks! Yup, I'll close this. The bug referenced above already has `dev-doc-needed` set, so we'll pick it up again when the bug is resolved.
