### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/Document

### ISSUE THREAD

**Issue by lukaszroz** [mdn/sprints#2155]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

It should be in English. I am getting:
`O Document interface representa qualquer página da web carregada...`

**Comment by ultraq** [comment]
I think this has happened to a few pages.  I can see pages edited by user [brasmon8351](https://developer.mozilla.org/en-US/profiles/brasmon8351) have converted pages to Portuguese, probably by accident, instead of making the edits to the Portuguese versions of the pages?

Maybe there's a way to revert the pages back to their English versions?  (I'm not a contributor, but maybe if I register that'd be possible.)

**Comment by chrisdavidmills** [comment]
This fortunately only happened on a few pages; thank you @ultraq for reverting most of them, I just caught another couple. It looks like most of brasmon8351's edits are on pt-BR pages, so they are getting the right idea.

No harm done.
