### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Debugging_CSS

### ISSUE THREAD

**Issue by travelingmoustache** [mdn/sprints#2157]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

Articles on the CSS - Styling the Web article listing link incorrectly. There are two different  lists of articles, seen below, and they seem to jump back and forth between each other with no clear way to distinguish which list of articles is up to date. 
<br> 
For example, the article on combinators, found <a href="https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators">here</a>, shows a list of links to CSS articles that indicate the next article should be one on CSS Values and Units, but at the bottom of its page it says the next article is on the CSS Box Model and links to that article, found <a href="https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/The_box_model"> here</a>. The Box Model article contains a different list of CSS articles with topics in a completely different order. The screenshots below show each page, with their different topic orders. 

![image](https://user-images.githubusercontent.com/50025194/64968893-eae00f00-d870-11e9-9291-71f7d915eead.png)
![image](https://user-images.githubusercontent.com/50025194/64968948-02b79300-d871-11e9-864d-c499cdad565d.png)

**Comment by chrisdavidmills** [comment]
The sidebar on https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Combinators was wrong because the page had not been regenerated properly. I've fixed it by doing a Shift + Refresh on the page (Shift + Ctrl (or Cmd on Mac) + R). If you find others with the wrong sidebar, this should fix.

Also, in the sidebar I don't list the selectors sub articles, whereas in the Previous/Next buttons they are included. I should probably fix that inconsistency at some point.
