### ISSUE TITLE
Hacks Blog post for two-value display syntax

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2191]
Firefox 70 implements the two-value display syntax, which is interesting in terms of how it describes display.

Write a hacks post to introduce and explain the syntax.

**Comment by rachelandrew** [comment]
Hi Chris, link for the two values of display hacks blog post is here https://docs.google.com/document/d/1lPJynw1SnsO6Roh5xQtCf78eCNYOA93rdZYKBhmdth0/edit?usp=sharing

**Comment by chrisdavidmills** [comment]
Thanks Rachel, this is looking really good. I've read through the article draft and given it a few small edits.

The only thing I didn't see (and apologies if I missed it) — an explicit explanation of what happens when you use the old one-value syntax in newer browsers that support two-value syntax. Are the single values just going to become aliases for their two-value equivalents?

**Comment by rachelandrew** [comment]
I thought I had inferred that in the first paragraph of the conclusion but have added _which will remain as aliases of the new syntax_ to make that completely clear.

**Comment by chrisdavidmills** [comment]
That's perfect, thanks! So I think this is ready to go on hacks. Havi would be happy to get it put up there and formatted; are you ok to ask her?

**Comment by rachelandrew** [comment]
yup - I'll do that today.
