### ISSUE TITLE
Add information around focus

### ISSUE THREAD

**Issue by kenchris** [mdn/sprints#2245]
@rakina has been leading an effort to clean up and fix the user and interoperability story around focus on the web platform and has a very nice blog post explaining a lot of the details.

I think it would be very valuable to have most of this info available on MDN:

https://blog.whatwg.org/focusing-on-focus

**Comment by chrisdavidmills** [comment]
This is a nice summary of focus, although to be more useful for the MDN audience it would probably need to be expanded a bit to talk about related different code features and how they should be used, best practices, code examples, etc.

We don't have much time to do this in the MDN team; are you willing to help with adding it?

I'd recommend that it goes under a generla place such as https://developer.mozilla.org/en-US/docs/Web/Guide, rather than under a specific area like focus()

**Comment by hinell** [comment]
I have [left][0] a link in the `HTMLElement.focus()` article (notes section) to the WHATWG blog post so interested folks may easily navigate and add more info to related topics.

[0]: https://wiki.developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus$compare?to=1590752&from=1582631
