### ISSUE TITLE
Possible mistake in documentation of runtime.connectNative()

### ISSUE THREAD

**Issue by espertus** [mdn/sprints#2365]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X] Correction or update

# Details

The documentation for `runtime.connectNative()` [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connectNative] has this description for the parameter `name`:

> `string`. The name of the native application to connect to. This must match the "name" property in the native application's manifest file.

I'm not sure this is correct. These files in https://github.com/mozilla-mobile/android-components seem to contradict it:

line 3 of "https://github.com/mozilla-mobile/android-components/blob/abdcd18b82b79d468c820dd67c636b3ae63250a0/components/feature/readerview/src/main/assets/extensions/readerview/manifest.json":

>   "name": "Mozilla Android Components - ReaderView",

line 320 of "https://github.com/mozilla-mobile/android-components/blob/67b34b8fadced0f386b2e4ce0aabe89b58f5492b/components/feature/readerview/src/main/assets/extensions/readerview/readerview.js"

> let port = browser.runtime.connectNative("mozacReaderview");

**Comment by chrisdavidmills** [comment]
One for you to do in the next sprint, @rebloor .

**Comment by rebloor** [comment]
I don't think this is an issue. 

mozilla-mobile/android-components/components/feature/readerview/src/main/assets/extensions/readerview/ is a web extension. 

android-components/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/  is a "native" app that provides an interface between the browser and the readerview web extension. In line 251 of [ReaderViewFeature.kt](https://github.com/mozilla-mobile/android-components/blob/b056812b875701964cf5ab902f6558b6073d9419/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt) this app is given the name "mozacReaderview".

It is the readerview "feature" ("mozacReaderview") that is then referenced in line 320 of readerview.js, not the web extension ("Mozilla Android Components - ReaderView").

Therefore, this example supports the documentation rather than indicating it is in error.

@espertus  are you satisfied with the explanation, can I close this issue?

 FYI @chrisdavidmills

**Comment by espertus** [comment]
Thank you, @rebloor. I was wrong.

If you have time to answer, I do wonder where the native manifest is for ReaderViewFeature? When I search in that repo for "mozacReaderView", I don't see any manifest.

**Comment by rebloor** [comment]
@espertus unfortunately, this is not a repository that I am particularly familiar with and from a quick review of the codebase I couldn't identify where the manifest is or where it is generated. If you are still curious, I suggest posting an issue on the repository to see if you can get an answer.
