### ISSUE TITLE
/en-US/docs/Web/API/EventListener

### ISSUE THREAD

**Issue by JustinWebDev** [mdn/sprints#2367]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

The title of this page is "EventListener".  However, the example code shows only the addEventListener() method.

**Comment by chrisdavidmills** [comment]
This is correct — the `EventListener` object represents the object referenced inside the `addEventListener()` method that handles the event; see the second example inside the examples section.

This is a legacy thing. These days we tend to just pass a function directly into `addEventListener()`, rather than putting it inside the `EventListener` object and passing that in.
