### ISSUE TITLE
/en-US/docs/Web/Web_Components/Using_templates_and_slots

### ISSUE THREAD

**Issue by Leokuma** [mdn/sprints#2368]
# Request type
- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
I'm not sure if this is an error or not, but please take a look at these two examples:

![image](https://user-images.githubusercontent.com/9329952/68065667-55f38100-fd0b-11e9-8619-cbe936b6ebc3.png)

![image](https://user-images.githubusercontent.com/9329952/68065691-b1257380-fd0b-11e9-9cd3-a4a835265495.png)

`shadowRoot` is being set the value returned from `appendChild()`. However, I'm afraid `appendChild()` doesn't work as expected in this case because of [this](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild):

![image](https://user-images.githubusercontent.com/9329952/68065582-27c17180-fd0a-11e9-99e7-479f8b075f7e.png)
Assuming a `<template id='my-template'>` full of DOM elements inside, it works like this:

_Same as the examples above, supposedly incorrect:_
```javascript 
  // ...
  let template = document.querySelector('#my-template').content;
  const shadowRoot = this.attachShadow({mode: 'open'})
    .appendChild(template.cloneNode(true));

  shadowRoot.querySelectorAll("*"); // returns no element
```

_Supposedly correct:_
```javascript
  // ...
  let template = document.querySelector('#my-template').content;
  const shadowRoot = this.attachShadow({mode: 'open'});
  shadowRoot.appendChild(template.cloneNode(true));

  shadowRoot.querySelectorAll("*"); // returns all the elements
```

**Comment by chrisdavidmills** [comment]
So, the second one is working as you'd expect because you are saving the result of 

```
this.attachShadow({mode: 'open'});
```

in the shadowRoot variable. That method returns the shadowRoot contents when run. Then you separate append some children to the shadowRoot, then later on console log shadowRoot

the first one is not running as expected because you are saving the result of the following in the shadowRoot variable:

```
const shadowRoot = this.attachShadow({mode: 'open'}).appendChild(template.cloneNode(true))
```

And you are right - appendChild doesn't give you what you'd hoped.

Note that you could do this to return the children of the shadowRoot:

```
console.log(this.shadowRoot.children);
```
