### ISSUE TITLE
Add documentation for offset-position

### ISSUE THREAD

**Issue by rachelandrew** [mdn/sprints#2369]
# Request type

- [*] New documentation
- [ ] Correction or update

# Details

We have document the other properties from CSS Motion Path, however we do not have a page for `offset-position`.

Spec: https://www.w3.org/TR/motion-1/#offset-position-property

**Comment by chrisdavidmills** [comment]
compat data submitted: https://github.com/mdn/browser-compat-data/pull/5130

**Comment by chrisdavidmills** [comment]
Page created: https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/offset-position

Saying that though, I'd love your help on this @rachelandrew — I don't really understand the purpose of this property, and I'm sure my write up doesn't really capture what it's for.

**Comment by chrisdavidmills** [comment]
Another issue, which I'd quite like @Elchi3 's help on —

The sidebar for these properties is not working quite right. On the individual property pages, e.g. https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/offset-position, all the properties get listed, but the main landing page is listed in the sidebar as "Motion Path" with a red link.

The main page is https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Motion_Path, and on that page none of the properties are listed, and the main landing page is listed in the sidebar as "CSS Motion Path" with a blue link.

I thought this would be because the properties' group is specified incorrectly in the data repo, but I had a look, and it is specified as "CSS Motion Path":

https://github.com/mdn/data/blob/master/css/properties.json#L6443

So, any thoughts? Does this need another package release before it will become correct? If so, can you help me by doing that, as I still don't know how.

**Comment by Elchi3** [comment]
Ouch, this is terrible. I screamed several times in the last 15 minutes. Sidebar nightmares. So, after going through the horrible sidebar code, I think I now know what is wrong: 

We haven't released mdn-data and KumaScript doesn't load last master from the data repo anymore. It loads the latest release that we have on npm. That means that all these changes aren't on MDN: https://github.com/mdn/data/compare/v2.0.4...master
I would release it, but latest master is also failing the tests. So, all this is utterly broken :/

**Comment by chrisdavidmills** [comment]
Argh, that is pretty nasty.

I have filed this in the dev papercuts board, at https://trello.com/c/qCTpQ3Uw/16-please-help-us-fix-the-loading-of-mdn-data

@tobinmori probably too late for this sprint, but can you prioritise this in the papercuts list for the next sprint? This is fairly severe.

**Comment by Elchi3** [comment]
It is probably more an issue that we should get someone to maintain mdn-data properly.
 
To fix the build, you need to basically do this PR properly: https://github.com/mdn/data/pull/399#issuecomment-553910270 (I commented in there). 
And then someone needs to publish to npm (and do so regularly when updating mdn-data)

**Comment by chrisdavidmills** [comment]
OK, so I've adding the missing appliesTo value:

https://github.com/mdn/data/pull/400

Next, can you teach me how to do a package launch?

I guess we also need to think about why MDN is no longer loading the updated data, unless it is just to do with the package needing updating.

**Comment by Elchi3** [comment]
> OK, so I've adding the missing appliesTo value:

awesome, merged. Build passes!

> Next, can you teach me how to do a package launch?

Yes, I think we should add docs to this repo on how to do that. It is basically almost the same as https://github.com/mdn/browser-compat-data/blob/master/docs/publishing.md I would think.

> I guess we also need to think about why MDN is no longer loading the updated data, unless it is just to do with the package needing updating. 

It is just the package that needs publishing. We stopped loading from GitHub and load from npm in this PR: https://github.com/mdn/kumascript/pull/1126 but of course no one took on regular publishing afterwards (like I do for BCD).

**Comment by chrisdavidmills** [comment]
OK, I am gonna have a go at adding a release doc for the data repo. Once done, I'll give it to to do a quick check, and then i'll try following it and see if I cna do a successful release. Looks pretty straight forward.
