### ISSUE TITLE
/en-US/docs/Games/Tools/Engines_and_tools

### ISSUE THREAD

**Issue by irisss97** [mdn/sprints#2396]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Navigating the page https://developer.mozilla.org/pt-BR/docs/Games when trying to follow the link to Engines and Tools the web site directed me to a not found page, after googling what I wanted, I have found that the correct (I guess) page is https://developer.mozilla.org/en-US/docs/Games/Tools

![image](https://user-images.githubusercontent.com/56799261/68673698-1ca0e980-0533-11ea-9610-9faeafd641f6.png)

**Comment by Leokuma** [comment]
You're right.

Just to be language-specific, it's this page: https://developer.mozilla.org/pt-BR/docs/Games/Tools

**Comment by SphinxKnight** [comment]
Thanks! This dead link was also in some English page. I've changed it for the localized version so that it works now.

However, the [pt-BR page](https://wiki.developer.mozilla.org/pt-BR/docs/Games) is not on a par with the [English page](https://wiki.developer.mozilla.org/en-US/docs/Games) and its content shoud be updated.
