### ISSUE TITLE
Remove legacy extension for Firefox for Android pages

### ISSUE THREAD

**Issue by rebloor** [mdn/sprints#2421]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

The legacy extension for Firefox for Android pages, those under https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android need to be removed as the technology they describe has being unsupported for some time.

To complete this work, translated pages need to be deleted before the reference/English pages

**Comment by chrisdavidmills** [comment]
I have gone through and deleted all of the subpages of this page that I could delete. the following JSON indicates the ones that are left:

https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android$children

So basically it's the following three pages that are stopping us from getting this section complete deleted:

* https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/NativeWindow
* https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/NativeWindow/doorhanger
* https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/Home.jsm

I've been through and looked it over, and none of them have translations or children according to their $children JSON readouts or language menus. But I am still not able to delete them.

@escattone could you give me some help on this if you get the chance? Is this problem due to some kind of orphaned translations sat somewhere?

And if so, how do I find out what these are so I can delete them?

**Comment by escattone** [comment]
@chrisdavidmills I couldn't find anything suspicious about these documents, and I was able to successfully delete them manually using a production Django shell. Here are the five (5) documents I deleted:

- https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/NativeWindow/doorhanger
- https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/NativeWindow
- https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API/Home.jsm
- https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android/API
- https://wiki.developer.mozilla.org/en-US/docs/Archive/Add-ons/Legacy_Firefox_for_Android

I did not purge them (which would irrecoverably remove them from the DB), but if you'd like me to do that I can do that as well. I hope that helps, and let me know if you need anything more. Cheers!

**Comment by chrisdavidmills** [comment]
This is perfect, thanks @escattone !

I think that fixes this one. Closing.
