### ISSUE TITLE
[Media] WebRTC, Fx 72 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2465]
# Trello

https://trello.com/c/ejryeYyB/73-webrtc-10-fx-72

# Acceptance criteria

1. - [x] [Stop supporting "rid=" in simulcast attributes once ESR doesn't serialize it anymore](https://bugzilla.mozilla.org/show_bug.cgi?id=1470568)
2. - [x] [Add rtpTimestamp support to RTP synchronization and contributing sources](https://bugzilla.mozilla.org/show_bug.cgi?id=1583867)

**Comment by a2sheppy** [comment]
#1 should be trivial, since it's just "The protocol used for simulcast changed some time ago and we no longer support the old format, so communication with old browsers may not work." Likely just a Firefox for developers mention. Add a little time to double-check that there aren't places this should be mentioned (there are some possibilities in the articles that dive into SDP a bit), and I guess about half a day.

#2 is the addition of one property to each of two or three interfaces. It's a simple property, and the whole thing should take no more than half a day.
