### ISSUE TITLE
Create/Update Introducing JavaScript objects assessments

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2491]
Create or update assessments for the [Introducing JavaScript objects](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects) module 

# Acceptance criteria

Create/update the following.

## New "test your skills" pages to create

1. - [x] Accessing objects
2. - [x] Creating your own class
3. - [x] Inheritance
4. - [x] JSON

## Existing assessments to update

For each one, we need to make sure the assessment instructions are updated to tell people to put their code in an online editor, and make sure the assessment is best practice and still current.

1. - [x] https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features

**Comment by chrisdavidmills** [comment]
Object basics test in place:

* https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics#Test_your_skills!
* https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics

**Comment by chrisdavidmills** [comment]
OOJS tests in place:

* https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object-oriented_JavaScript
* https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS#Test_your_skills!
* https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes#Test_your_skills!
* https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Inheritance#Test_your_skills!

**Comment by chrisdavidmills** [comment]
JSON test in place:

* https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON#Test_your_skills!
* https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_JSON

**Comment by chrisdavidmills** [comment]
@Elchi3 is there any chance you'd have a little time to review these OOJS assessments?

Basically I'd be looking for:

* Is there anything really obvious that I've not covered in these tests?
* Do the code examples look sensible? Are there any bits that are obvious bad practice/stupid?
* Do they seem too hard for beginning JavaScripters, or too easy? Just about right?

**Comment by Elchi3** [comment]
> https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_Object_basics

Object basics 1: 
- Works well for me. Nice one!
- I was looking for the "Meow" in the inline pane, because that's where my attention was, but then I read that it is supposed to show up in devtools, which it does. So all good.

Object basics 2: 
- formed, split, released could be date objects instead of numbers, but maybe that is unnecessary distraction?
- Unlike in the first test, you have to build the string all by yourself which isn't as motivating as fixing the error that was thrown in the first example when you hadn't written any code. So, I created the band object, but then was too lazy to build a really nice string containing all the info from the object. Maybe have a failing string output here, too? Just a thought, though. Maybe not everyone is as lazy as I am.

Object basics 2: 
- nice way to let them play with "this".
- Again noticing that there is both the output pane and devtools involved. Not a big deal though as I said. Just two places to pay attention to.
- For `cat2`, you basically repeat the `greeting()` code? This is not DRY but I don't know if that matters for this stage of learning.

**Comment by Elchi3** [comment]
OOJS 1:
- Perimeter isn't in my English everyday vocabulary, but I was right in my intuition what it would be. :)
- The last item here I had to look up, because I almost never do that. Is it useful to do basic thing in a complicated way?:
  - Do it using the square instance constructor(), rather than using the Shape() constructor.
  - `let triangle = new square.constructor('triangle', 3, 3)`

OOJS 2: 
- If you have learned about classes, then this should be straight forward and very simple. Looks good to me.

OOJS 3:
- Here you create a specialized class "square", but you don't preset the name property to "square". Instead you will have to specify that upon instancing: "let square = new Square('**square**', 4, 5);". I guess best practice here would be to set the name in the class and then have a more sensible Square(4, 5) constructor. Does that make sense to you?

**Comment by Elchi3** [comment]
> https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Test_your_skills:_JSON

JSON 1:
 - The difficult thing about this one is that you have a data structure and that you have to loop over it and extract info, much like arrays or objects. So, that's not really JSON specific. I guess it is still on point, though, as this is just almost always the thing you need to do when dealing with JSON. You have two simple for loops here now. That seems to work, but maybe accessing data could be more elegant using array#filter or so. I don't know, just a thought.

**Comment by Elchi3** [comment]
Reviewed this, @chrisdavidmills! Overall, I think these assessments are great and support you nicely though this module. I have left some comments on each task above. Some things are probably really minor. Hope this helps!

**Comment by chrisdavidmills** [comment]
@Elchi3 wonderful, thanks mate, this is really helpful! I'll go through this all soon.

**Comment by chrisdavidmills** [comment]
@Elchi3 going through these now ... I made additions due to the following points. Thanks so much for trying these out!

> This is not DRY

I agree, but at the moment I am just testing knowledge of object literals in this bit. To acknowledge your point, I've add a question to the test, like so:

"The code is not very DRY (each bit of code should only be defined once) — you've got the same method defined twice, for example. Describe how you'd make it less DRY? If you are not sure, then don't worry — this is what we'll be looking at in future articles in the series!"

> Perimeter isn't in my English everyday vocabulary

I've added a definition in parens after my usage of the word, just in case.

> The last item here I had to look up, because I almost never do that. Is it useful to do basic thing in a complicated way?

I agree, that is a bit silly. I've removed that requirement, and changed the answer given in the marking guide to the basic one (`new Square()`, etc.`)

> set the name in the class and then have a more sensible Square(4, 5) constructor.

Ah yes, that is a really good point. I've updated the solution to the following, and added some hint text to the question to help with this.

```
class Square extends Shape {
  constructor(sides, sideLength) { 
    super(name, sides, sideLength);
    this.name = 'square'; 
  }
  
  calcArea() {
    console.log(`The ${ this.name }'s area is ${ this.sides * this.sides } squared.`);
  };
}

let square = new Square(4, 5);
```

Does this look OK to you? It seems to work OK.

> maybe accessing data could be more elegant using array#filter or so

Yeah, probably, but I've not really taught that anywhere in the course ;-) I probably ought to add some more about useful array methods of that ilk at some point.

**Comment by chrisdavidmills** [comment]
@Elchi3 let me know if you are satisfied by these changes, and feel we can move this to done.

**Comment by Elchi3** [comment]
I am mostly satisfied! Very well done, Chris! 

One last thing:

```
class Square extends Shape {
  constructor(sides, sideLength) { 
    super(name, sides, sideLength);
    this.name = 'square'; 
  }
  
  calcArea() {
    console.log(`The ${ this.name }'s area is ${ this.sides * this.sides } squared.`);
  };
}

let square = new Square(4, 5);
```

> Does this look OK to you? It seems to work OK.

This is already better, but I wonder if it is also a bit non-sense to have the "sides" parameter. A square always has 4 sides, right? 
So, I think better for `Square` would be `constructor(sideLength)` and `super(name, 4, sideLength)`. which makes you call  `let square = new Square(5)`. What do you think?

For the area calculation, you want ` ${ this.sideLength * this.sideLength }` and not ` ${ this.sides * this.sides }`.

**Comment by chrisdavidmills** [comment]
@Elchi3 ack, you are totally right.

OK, so I have improved the solution further, to this:

```
class Shape {
  constructor(name, sides, sideLength) {
    this.name = name;
    this.sides = sides;
    this.sideLength = sideLength;
  }

  calcPerimeter() {
    console.log(`The ${ this.name }'s perimeter length is ${ this.sides * this.sideLength }.`);
  };
}

class Square extends Shape {
  constructor(sideLength) { 
    super('square', 4, sideLength); 
  }
  
  calcArea() {
    console.log(`The ${ this.name }'s area is ${ this.sideLength * this.sideLength } squared.`);
  };
}

let square = new Square(9);


square.calcPerimeter();
square.calcArea();
```

And updated the description on the assessment further to make sure it is clear what is being asked for.

**Comment by Elchi3** [comment]
Thanks Chris! I think we're done here now!
