### ISSUE TITLE
/fr/docs/Web/JavaScript/Reference/Objets_globaux/Error

### ISSUE THREAD

**Issue by alaindebecker** [mdn/sprints#2495]
# Request type
- [X ] Correction or update

# Details

The automatic translator did translate the keyword `lineNumber`  in  `numeroLigne`, which is a good thing in general but a bad one for language resrved words.

To reproduce make an error named e. Then  `e.numeroLigne` is undefined, while `e.lineNumber` is the correct _numero de ligne_.

I did test, but I guess the same holds for `err.nomFichier` instead of `err.nomFichier`. 

Please can you instruct your translator softbot not to translate text in _syntaxbox_ nor _code_ tags.

**Comment by chrisdavidmills** [comment]
I've never heard @SphinxKnight referred to as a translator softbot before ;-)

Only joking; I don't know if we have used auto translators anywhere on the site? Sphinc do you have more information on this?

**Comment by alaindebecker** [comment]
You mean that all the MDN doc is manually translated. Hats off. And special congrats to @SphinxKnight!

**Comment by SphinxKnight** [comment]
@alaindebecker in this case `numeroLigne` is used as a translation when it's a parameter (and not a property or a reserved keyword). 
For my defense, I tend to translate variable names (but not built-in properties names or reserved keywords!) for simple examples so that beginners who are not well-versed in English can understand.

However, I understand how this might be confusing and I'll adapt the style here (adding a note to differentiate between parameters and built-in property names / keyword)

Re the translations: 

* @chrisdavidmills I'm not aware of any vast enterprise to use automatic translation tools to produce MDN content (at least in French). However there are sometimes I do encounter "copied-pasted" snippets of contents with hidden `<span blablbla translate blabla>` coming from Google Translate and  the like

* @alaindebecker : 🤖I am definitely not a robot 🤖 (even though Skynet would reply the exact same thing) and not all content of MDN is translated in French (yet (lol nope)). I do admit I'm responsible for quite [a bit of manually translated content](https://tech.mozfr.org/post/2017/01/31/Les-sections-HTML--CSS-et-JavaScript-de-MDN-sont-disponibles-en-francais) though.

**Comment by SphinxKnight** [comment]
https://wiki.developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Error$compare?locale=fr&to=1592590&from=1581900
