### ISSUE TITLE
Debugging worker threads page incomplete/low quality

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2497]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The [Debugging worker threads](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/Debug_worker_threads) page is basically just a skeleton - it was not completed, and needs more details adding and screenshots that work.

**Comment by chrisdavidmills** [comment]
Update — I've added working screenshots, improved the text a bit, and added in the sidebar, just so the page usable.

**Comment by hamishwillee** [comment]
@chrisdavidmills I don't think it makes sense to turn this into a "complete" topic on debugging worker thread, because AFAIK debugging a worker thread is _exactly_ the same as debugging a main thread. The only (minor) difference is that worker threads aren't necessarily created on page load (are created when needed),  so unlike the main thread the worker script might not be present in the sources list when you first load a page. 

Given that, making it clear that this is exactly the same as "normal" debugging and showing how to find the worker thread sources is all we should do. That is more or less what you already did.

Upshot, I very slightly modified this to make it very clear that this is business as usual and push people to existing docs:
- Clear first sentence: 
  ![image](https://user-images.githubusercontent.com/5368500/101304756-1c3d6400-3895-11eb-8be3-e7106bd66ea2.png)
- Further info section at end with links to the main topics people should read.
- Little more cross linking in the body. 

Seem reasonable? It is possible there are other differences, or there is a policy to show everything (i.e. we don't care about duplication).

**Comment by chrisdavidmills** [comment]
@hamishwillee all sounds reasonable. Is this another candidate for just redirecting to the main pages and putting in a little more info there? If that's going to be a pain then we could just leave it as is for now.

**Comment by hamishwillee** [comment]
> Is this another candidate for just redirecting to the main pages and putting in a little more info there? If that's going to be a pain then we could just leave it as is for now.

@chrisdavidmills Yes it is - very good idea.  I have copied the content almost verbatim into [Web_Workers_API > Using_web_workers | Debugging_worker_threads](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Debugging_worker_threads). It does not feel like unnecessary duplication in the context of web worker docs.

I have redirected the original doc here and also added a few other references to it. 
- [UI Tour > Source list pane ](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/UI_Tour)
  ![image](https://user-images.githubusercontent.com/5368500/101436041-86bbd600-3961-11eb-8793-a10d87864cbb.png)
- [Debugger home page > Howto guides](https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger)
   ![image](https://user-images.githubusercontent.com/5368500/101436116-a3580e00-3961-11eb-9869-a05696a44cdc.png)

**Comment by chrisdavidmills** [comment]
This is looking great, thanks @hamishwillee ! The only thing I'd say now is that you could do with making that section a bit more browser-neutral, as it is in a general web platform documentation page now, and not a Firefox devtools-specific page.

So for example:

"Most browsers allow easy debugging of worker threads in their JavaScript debuggers"
"For example, in Firefox..."
"Chrome's tools are similar, yadda yadda..."

**Comment by hamishwillee** [comment]
@chrisdavidmills Another good point. Fixed first paragraph to be generic, followed by Firefox specific "example". We could just link to the FF docs on debugging, but I think it is useful to show that things are "really the same".

![image](https://user-images.githubusercontent.com/5368500/101847018-587b0800-3ba6-11eb-87e8-e21db8c25182.png)

Closing as done :-)

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Another good point. Fixed first paragraph to be generic, followed by Firefox specific "example". We could just link to the FF docs on debugging, but I think it is useful to show that things are "really the same".

Looks great, cheers!
