### ISSUE TITLE
/ru/docs/Web/CSS/visibility Bad display of an example in Russian

### ISSUE THREAD

**Issue by p0lunin** [mdn/sprints#2511]
Bad display of an example in Russian.
- [ ] Correction or update

# Details
This display is only where I choose Russian.

![Photo1](https://user-images.githubusercontent.com/48922415/69912919-3ef29c80-1439-11ea-870e-2a362a42fbe6.PNG)

When I choose an another language, the example shown correctly.

![Photo2](https://user-images.githubusercontent.com/48922415/69912929-6cd7e100-1439-11ea-826b-14ace75a53a1.PNG)

**Comment by SphinxKnight** [comment]
Thanks for the report @p0lunin, this was due to the interactive example being enclosed in `<p>` and not `<div>`. I fixed it and it now looks OK on https://wiki.developer.mozilla.org/ru/docs/Web/CSS/visibility (the change will appear soon-ish on https://developer.mozilla.org/ru/docs/Web/CSS/visibility )
