### ISSUE TITLE
Subset the ZillaSlab and OpenSans fonts for different language support

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#254]
Tasks:
- [x] Identify correct subset for each locale
- [x] generate subsetted files
- [x] reference subsetted files accordingly for each locale
- [x] document process
- [x] measure and record performance impact

Acceptance Criteria:
- [ ] We're only loading the necessary subset for reach locale
- [ ]  confirm each font file contains only the specified subset
- [ ]  process documented
- [ ] performance impact reported

**Comment by tkadlec** [comment]
Looks like we use the Zilla font on the following locales (once we exclude the locales that will be removed in https://github.com/mdn/sprints/issues/449):

```
Svenska (sv-SE)
Portugues (pt-PT) and (pt-BR)
Polski (pl)
Nederlands (nl)
Melayu (ms)
Taqbaylit (kab)
Italiano (it)
Bahasa Indonesia (id)
magyar (hu)
Francais (fr)
suomi (fi)
Espanol (es)
Deutsche (de)
Catala (ca)
English (en-US)
```

**Comment by tkadlec** [comment]
Couldn't find a reliable resource about exactly which characters each individual locale would need in order to create a separate subset for each locale listed.

That being said, I created a Latin character subset that appears to support all the above languages. That brings the weight of the WOFF2 files for Zilla from 67kb (for each bold and regular) to 33KB each for a total reduction of 68kb (~50%).

It's a little more conservative than trying to get each language individually, but I also safer and a nice boost.

**Comment by tkadlec** [comment]
The documentation around `pyftsubset` is....not great. BUT, once you play with it it's pretty slick. To create the Latin subset, I created a file that contains the unicode ranges to include. There are other shortcuts to go to certain subsets, but I like the clarity this gives us in case we edit the subset in the future:

```
# Basic Latin
U+0020-007F

# Latin-1 Supplement
U+00A0-00FF

# Latin Extended-A
U+0100-017F

# Latin Extended-B
U+0180-024F

# General Punctuation
U+2000-206F

# Currency Symbols
U+20A0-20CF
```

Then you run the commands:

```
pyftsubset ZillaSlab-Bold.ttf --unicodes-file=latin-characters --flavor=woff2
pyftsubset ZillaSlab-Bold.ttf --unicodes-file=latin-characters --flavor=woff
pyftsubset ZillaSlab-Regular.ttf --unicodes-file=latin-characters --flavor=woff2
pyftsubset ZillaSlab-Regular.ttf --unicodes-file=latin-characters --flavor=woff
```
