### ISSUE TITLE
MDN contributor profile and settings updated workflow

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2546]
# User story
As a contributor I want to be able to quickly find all the pages I made contributions for (so that I can check back on my contributions, and so that I can continue/edit WIP).

# Acceptance criteria

- [x] We have solutions (ie. InVision mock-ups) for the above use-cases outlined ready for engineering
- [ ] Engineering sign off
- [ ] PM sign off

**Comment by SphinxKnight** [comment]
Hello,
(Contributor for some time here), I'm wondering what the contributor profile has to do with paid memberships?
is there any contribution workflow planned for d.m.c. or will paid memberships have an impact on the contribution for d.m.o?

I have to admit I'm a bit confused here :s

**Comment by malqinneh** [comment]
Great question! Short answer: you're right, it's not the ideal epic
associating user/contributor profiles with paid memberships. But, as with
all things, it's a little more complicated. Not so short answer: in effort
to prioritize user/contributor profiles work and ensure user/contributor
profiles accomodate future roadmap work (ie. compat data customization and
the move of the editting workflow to GitHub) it's advantageous that we
ensure the foundation and architecture of user/contributor profiles enable
us to implement future roadmap work starting with the managing of paid
memberships (whether you're a user or contributor).

However, I sent the issue to our PM (Kadir Topal) for review and will
reassess where to file this issue :)

Thanks for bringing this to our attention.

Mustafa

**Comment by malqinneh** [comment]
On first iteration, nothing specific is needed to differentiate between contributor and non-contributor accounts. One suggestion was about adding [Contributions] link in the drop-down for logged in users *if* the user happens to be a contributing member. @peterbe mentioned that it might effect page load times. We can default to showing [Contributions] link for non-contributors and contributors. On click, users would be taken to a GitHub landing page with all contributions filtered by their username (which for non-contributors would see '0' contributions).

**Comment by peterbe** [comment]
For the record, figuring out if a user is a **wiki-contributor** or not will *not* affect "page load times". The XHR request to `/api/v1/whoami` is loaded *after* the page load. But if it's slow, it takes longer for the "Sign in" link to be replaced with your mugshot. Also, that endpoint is already slow. But adding `Revision.objects.filter(creator=request.user).exists()` on every request might not actually be that hard. It'd give us, in the `whoami` endpoint, something like `"has_contributions": (true|false)` which we could use inside `login.jsx` to determine what should appear when/if you press your mugshot. 

Note that I phrased it as "wiki-contributor" because in a couple of months we'll lose the concept entirely as the content contributions will not be connected to the user database since, instead, only GitHub (and `git`), will have information about which users have made content contributions. 

Suppose that we add `has_contributions` to the JSON in `/api/v1/whoami` today, and remove the Wiki tomorrow, how are you then to fulfill this piece of information? 
It would NOT be feasible to do a git history lookup, in runtime, on every `whoami` lookup. (We could have a convoluted cron job that compares a week's worth of git logs and pushed that into the user profiles in MySQL)

What's contentious also is; what do you do on the "Contributions" page *within* the settings page? *Today*, it could easily just be a link to `wiki.developer.mozilla.org/contributions?filter-by=peterbe` (made up) or something. What do you do when the content is maintained in git? 

I know these points above aren't super constructive for immediate progress but it's worth raising loud and clear. We need to think about the next 6+ months before it's too late. 

A crazy idea is that we *don't bother with any of this at all* on `developer.mozilla.org` but keep it, as is, on the "View/Edit Profile" over on `wiki.developer.mozilla.org`. Who knows, there might be an entirely different mindset about contributions, that we haven't considered, by the time we're over in decentralized git instead of centralized MySQL.

**Comment by malqinneh** [comment]
> A crazy idea is that we don't bother with any of this at all on developer.mozilla.org but keep it, as is, on the "View/Edit Profile" over on wiki.developer.mozilla.org. Who knows, there might be an entirely different mindset about contributions, that we haven't considered, by the time we're over in decentralized git instead of centralized MySQL.

I don't think it's such a crazy idea 👍 

Only thing to consider are users/contributors that *currently* rely on a link from their developer.mozilla.org profile to get to wiki.developer.mozilla.org /or their contributions.

**Comment by peterbe** [comment]
> that _currently_ rely on

Yeah. So we could be cunning and refer to it as "Wiki contributor" or "Wiki contributions". Then it won't have to be a weird transition when we move away from the Wiki (WYWIWYG).

**Comment by atopal** [comment]
In our meeting yesterday we discussed this and decided to remove the contributions item from the menu and add it to the account. The new designs look good to me.
