### ISSUE TITLE
Consider removing some fonts/variations

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#255]
Tasks:
- [x] Identify where each font and variant is used
- [x] decision about where needed/not needed
- [x] removing unnecessary ones from the site
- [ ] measure and record performance impact

Acceptance Criteria:
- [x] font usage investigated and unnecessary ones removed
- [ ] performance impact reported

**Comment by tkadlec** [comment]
Took a look at where each variant is being used on the home page. Posting images here for posterity.

![fonts-home-body.png](https://images.zenhubusercontent.com/5a0ca0078a75884b908794ed/4626fb6d-c929-4ad4-aafe-afcb68c21131)
![fonts-home-header.png](https://images.zenhubusercontent.com/5a0ca0078a75884b908794ed/55c669a0-e2dd-46a5-8832-720e5583181f)
![fonts-home-footer.png](https://images.zenhubusercontent.com/5a0ca0078a75884b908794ed/e134fceb-2321-4839-b3c7-73d330d6ca8c)

**Comment by tkadlec** [comment]
Font Synthesis testing to see what happens if we only load the regular versions of each font.

Chrome
![Screen Shot 2018-08-23 at 9.24.57 AM.png](https://images.zenhubusercontent.com/5a0ca0078a75884b908794ed/1e4b9d71-f470-4153-ba4f-88c59ca6e93f)

Safari
![Screen Shot 2018-08-23 at 9.25.02 AM.png](https://images.zenhubusercontent.com/5a0ca0078a75884b908794ed/fdea4e83-2eb6-465c-b663-71b6b26cba74)

Firefox
![Screen Shot 2018-08-23 at 9.24.37 AM.png](https://images.zenhubusercontent.com/5a0ca0078a75884b908794ed/4a450878-71f3-4f09-9399-12f9570811d7)

**Comment by atopal** [comment]
@tkadlec can we get this with a wiki article page?

**Comment by tkadlec** [comment]
@atopal Like so? https://github.com/mdn/mdn-fiori/wiki/MDN-Web-Fonts

@schalkneethling Let me know if I should do this as a page elsewhere. I know we put the metrics here and I _think_ that's where you wanted these kinds of things.

**Comment by schalkneethling** [comment]
@tkadlec That totally works for me. Thanks a lot!

**Comment by atopal** [comment]
Hey Tim, can you share your numbers here too? I was kinda hoping for a bigger impact, but I still think we should go ahead with just Zilla slab and bold. Can you prep the PR?

**Comment by jwhitlock** [comment]
The changes in PR #4967 have been deployed, and there's a lot more Verdana.

**Comment by jwhitlock** [comment]
Follow-on work to try Arial in [bug 1491154](https://bugzilla.mozilla.org/show_bug.cgi?id=1491154).
