### ISSUE TITLE
Clean up/expand/clarify Watch expressions docs

### ISSUE THREAD

**Issue by valgrimm** [mdn/sprints#2588]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

This description is vague and will be corrected. I was going to use this article as a source for a dev tool tip, but @chrisdavidmills noticed that it doesn't behave as described, namely not indicating when the expression value changes. He suggested that the article needs cleanup.

**Comment by chrisdavidmills** [comment]
Page in question: https://wiki.developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Set_Watch_Expressions

Val is right — when you set an expression (such as watching the value of a variable, or testing whether it is higher than a certain value), it seems to set ot the correct value initially, but then doesn't update as the variable value changes in the environment.

We miust be missing something here, but it'd be good to expand the page with some more information and steps to get it to work, and use cases.

**Comment by hamishwillee** [comment]
@chrisdavidmills I used some very simple test code: [testwatch.zip](https://github.com/mdn/sprints/files/5656944/testwatch.zip). Dumped both files into any folder, load HTML, set  breakpoint in **example.js** in `myFunction1()` then pressed the button1. This should allow you to then trace through the code watching `test` iterate. 

My observation is that watch expressions are fragile, particularly if side effects are used (watch expressions that modify values in the code itself). For example, the screenshot shows second last value of 7 irrespective of what you do (refresh or step) and the first two values of text are mismatched/can't both be true.
![image](https://user-images.githubusercontent.com/5368500/101445051-e1126200-3974-11eb-8358-b01848804a59.png)
Generally however it seems to work OK as long as you don't have a side effect.

Observations:
1. You can specify a variable you like to watch. If it is in scope it will be displayed with a value (otherwise undefined). If it is an object you can expand it. 
2. You can add a watch on a variable or expression and it is evaluated immediately, but other (old) watches are not re-evaluated until you trigger a new evaluation by debugging or hitting the refresh icon.
3. You can add a watch like `fred=1+3`, but you can't add `var fred = 1+3`. I suspect it looks for a real var in this case, and it is undefined.
4. Side effects are possible - so `text=text+1` will change the variable in code. If you hit refresh the variable will update the stored value even if you don't iterate through the code. The watch is evaluated in order, so if you change the value of the variable in a later watch, the earlier values are not updated in the watch window.

I have updated. It is certainly a lot better IMO but would appreciate feedback, as this is a feature I rarely use.

**Comment by chrisdavidmills** [comment]
@hamishwillee LGTM; I've done a bit of cleanup on the page, and I think this is ready to close now.

**Comment by hamishwillee** [comment]
Thanks. FWIW, the fact that you are expected to add boilerplate text to notes, tips etc (e.g. `<strong>Important</strong>:`) drives me crazy. Could so easily be done automatically.

**Comment by chrisdavidmills** [comment]
Yup ;-)
