### ISSUE TITLE
Optimizing images: automated process for processing user generated content

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#260]
Task
- [ ] measure and record performance impact

References
- [bug 839559](https://bugzilla.mozilla.org/show_bug.cgi?id=839559)

Acceptance Criteria:
- [ ] When user uploads content, content is automatically compressed
- [ ] When user uploads content, content is automatically resized
- [ ] When user uploads content, content is automatically reformatted
- [ ] performance impact reported

**Comment by schalkneethling** [comment]
@tkadlec I have also thought about this. I do not believe our current infrastructure will make this a trivial thing to accomplish. Although @jwhitlock will not better than me on this topic.

Wonder if our current CDN has similar support?

**Comment by tkadlec** [comment]
Not sure about whether we want to do static tests. This was always a lower
impact optimization that is not going to move any primary metrics. Don't
get me wrong, good to do, but not game-changing.

Could you walk me through why it would take 3-9 months? I don't doubt it, I
just dont have the experience with your infrastructure to understand the
potential pitfalls.

- Tim

**Comment by jwhitlock** [comment]
The [file attachments](https://bugzilla.mozilla.org/buglist.cgi?product=developer.mozilla.org&component=File%20attachments&resolution=---&list_id=14430457) and [editing](https://bugzilla.mozilla.org/buglist.cgi?product=developer.mozilla.org&component=Editing&resolution=---&list_id=14430464) code have several issues, some of which will need to be fixed in order to make a change to the way images are added. Fixing these systems has not been a priority, and some work would be needed to identify the blockers for this idea.

We allow multiple attachment types, and we'd need to fork the code for images vs non-images. We could implement a dual UI - use this form provided by Cloudinary for image uploads, and this form for non-image uploads. Making a nice UI will take more work. Translations are a requirements, which usually means implementing our own UI rather than using the provider's. Integration with CKEditor would be nice, but would probably require updating CKEditor.

We'd need to decide if wiki editors get to choose image optimization parameters, or if we'd pick defaults. Do we enforce those restrictions, or allow users to pick unrestricted via the URL? Each have design consequences.

In the past, content has been a problem. Users upload personal images, using MDN to serve them. Worse, they upload illegal images such as child pornography. We've needed tools to monitor image content in the past, and the ability to remove objectionable images. Maybe cloudinary would be an improvement here.

After that, we'd have a process where new image uploads, moving forward, get optimized. However, the benefit is only realized if existing images are optimized. There's currently over 10,000 attachments, and 65,000 documents. It should be possible to move images to cloudinary, but we don't have a mechanism for updating the in-content URLs of images. We could implement a redirect, and carry the debt forward. Which depresses me.

Some of this is front-end, and you are probably more familiar with the issues with updating front-end code. I'm not terribly familiar with the backend code, and I doubt @escattone is either. My impression is that the backend attachment code should be re-written from scratch rather than built on. You'll be competing for frontend and backend resources versus other priorities.

That's what comes to mind. This idea has been around for 6 years ([bug 824331](https://bugzilla.mozilla.org/show_bug.cgi?id=824331)), and each time it comes up, the 3 - 9 month ballpark estimate stops work. We'd need a clear message from the team that this is worth spending time on versus other projects, and management commitment to a multi-quarter goal.
