### ISSUE TITLE
Optional chaining demo crash

### ISSUE THREAD

**Issue by MackanPS** [mdn/sprints#2657]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In the "Optional chaining" documentation the example crashes when run, it gives an "Error: Unexpected token '.'" error when tried.

https://imgur.com/a/Q5MWOjH

**Comment by MackanPS** [comment]
[](url)

**Comment by chrisdavidmills** [comment]
It looks like this is behaving as expected — on Firefox it gives an error, as it is not supported yet, and on Chrome release it currently also gives an error because it is supported behind a flag (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Browser_compatibility).

If you try it in the latest Chrome Canary, it works by default.
