### ISSUE TITLE
JS Array exercise pb

### ISSUE THREAD

**Issue by HALLneufmilles** [mdn/sprints#2668]
Hello,

page:
https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/tableaux
exercise: Display product.

This Iframe with exercice doesn't work. I did it several time and check but still doesn't work.
Could you please check what is the probleme. I am sur this is not due to my code.
Find attached my code that strictly the same as solution.
![Array Exercise](https://user-images.githubusercontent.com/59488578/71996676-e3d47680-323c-11ea-8d48-9a57e4fc48a1.JPG)
https://transfernow.net/42iuy7u5m10v

best regards

**Comment by chrisdavidmills** [comment]
I don't think there is anything wrong with the page here. When you press the "Show solution" button, the correct code (still in English, unfortunately) is filled in and renders fine.

Maybe you could check your code against ours, to see if it gives you an idea of what the problem is?

If you do that and still can't see a problem, feel free to send me your code so I can try to debug it.
