### ISSUE TITLE
/en-US/docs/Web/API/Document_Object_Model/Introduction

### ISSUE THREAD

**Issue by k-rahman** [mdn/sprints#2717]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

**-In the link below, you mention that "The HTMLElement class, in turn, implements Node, so every element is also a node (but not the other way around). "**

https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API

![Screenshot 2020-01-25 at 17 14 09](https://user-images.githubusercontent.com/55299478/73123202-22d12e80-3f96-11ea-8d39-925701542f29.png)

**-In the link below, you wrote the opposite "each node is an element."**

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction

![Screenshot 2020-01-25 at 17 17 25](https://user-images.githubusercontent.com/55299478/73123259-cde1e800-3f96-11ea-802d-dfa66bed5760.png)

**Comment by chrisdavidmills** [comment]
Thanks for reporting this. In the second instance you cite, I've updated the wording to 

"Note: Because the vast majority of code that uses the DOM revolves around manipulating HTML documents, it's common to refer to the nodes in the DOM as elements, although strictly speaking not every node is an element."
