### ISSUE TITLE
partially wrong code in english and french pages for <input type="date">

### ISSUE THREAD

**Issue by voronamanga** [mdn/sprints#2744]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
MDN page : input type="date"

In english, please see following part : Handling browser support > Examples > Javascript, code , line 44: 
const isLeap = new Date(year, 1, 29).getMonth() === 1;
Français : Gérer la prise en charge des navigateurs > Exemples > 2° bloc de code  ligne 52, même déclaration de constante.

I think this can't work for 2 reasons:
- we want to look for februar 29th and not january (wrong month number);
- as surprising as it can be, new Date(2021, 2, 29).getMonth() will return 2 even if the date doesn't exist.

I would suggest to replace this line with: 
const isLeap = parseInt(selectedYear, 10) % 4 === 0;

**Comment by chrisdavidmills** [comment]
I'm pretty sure this isn't wrong. Let's walk through the code in question:

`const isLeap = new Date(year, 1, 29).getMonth() === 1`

For a start, JS counts from 0, so January is month 0, February is month 1, etc.

Here we saying, if I create a new Date that is February 29th of the current year, if I run `getMonth()`  on it does it return 1 (February) still? If there are only 28 days in that year's February it will roll over to March the 1st, and the value returned by getMonth() will be 2.

You can test this like so

`console.log(new Date(2019, 1, 29).getMonth())`

`console.log(new Date(2020, 1, 29).getMonth())`

2020 is a leap year, so the value returned from the second one will be 2

So we do a test to see if the result is 1, and store it in a constant.

If it is 1, we set the numbers of days to 29 for that month, 28 otherwise:

`dayNum = isLeap ? 29 : 28;`

Does that help?

I think originally I had something closer to your suggestion, but then I read somewhere that this isn't going to be accurate 100% of the time, so I looked for something more robust.

**Comment by voronamanga** [comment]
> For a start, JS counts from 0, so January is month 0, February is month 1, etc.

OK, so my mistake comes from there ... as often, wrong explanation of an issue. The code did'nt work but it had to be for another reason then.

> I read somewhere that this isn't going to be accurate 100% of the  time

That's right, I did'nt know it : "Every year that is exactly divisible by four is a leap year, except for years that are exactly divisible by 100, but these centurial years are leap years if they are exactly divisible by 400. For example, the years 1700, 1800, and 1900 are not leap years, but the years 1600 and 2000 are." [https://en.wikipedia.org/wiki/Leap_year](url)

> Does that help?

Certainly ! Thanks and sorry for the wrong report.

**Comment by chrisdavidmills** [comment]
> The code did'nt work but it had to be for another reason then.

Do you mean my code, or some code your are writing? 

> Certainly ! Thanks and sorry for the wrong report.

No need to apologise; it's always worth investigating things if they don't seem to work, or don't make sense!

**Comment by voronamanga** [comment]
> Do you mean my code, or some code your are writing?

I mean my own implementation (and interpretation) of your code in a function which turns a single field "date" into 3 fields "text" (day-month-year), so it is very likely that the issue came from me.

**Comment by chrisdavidmills** [comment]
> I mean my own implementation...

Ah, OK! Glad things seem to be working OK for your case, but feel free to ping me if you need any help in the future.

**Comment by voronamanga** [comment]
Thanks!
