### ISSUE TITLE
Template Literals takes so long to appear on JS Learning Area pathway

### ISSUE THREAD

**Issue by EduardoPazz** [mdn/sprints#2759]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Hello, folks. First of all, I thank all the MDN team for delivering this high quality content on this high quality environment, and I send a "hello" from Brazil.

I just wanted to ask you guys to introduce the concept of "template literals" in the beginning of JavaScript Learning Area, 'cause this technique is such useful over the simple "concatenation", and it takes so long to appear, in my opinion (just appears on https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Inheritance , a OOJS content, a pretty advanced context to introduce a String shorthand)

![Opera Snapshot_2020-02-04_194956_developer mozilla org](https://user-images.githubusercontent.com/53970946/73794711-c76a2200-4787-11ea-98cf-4736cb5837c8.png)

**Comment by chrisdavidmills** [comment]
Hi @EduardoPazz , and thank you for your kind words!

Also thanks for bringing this up — basically, this happened because a lot of the basic learning content was written before we started using modern ES features in our content (this decision was only made a couple of years ago).

This bit of content was written after that.

I think the best thing for me to do would be to add a section to our [strings article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings) to cover usage of template literals, and then gradually start changing the examples over.

**Comment by chrisdavidmills** [comment]
New section written to cover template literals:

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings#Template_literals

**Comment by chrisdavidmills** [comment]
New skilltest example created to test template literal knowledge:

https://wiki.developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Strings#Strings_4

What do you think @EduardoPazz ? Does this look for now?
