### ISSUE TITLE
As the PM I want to know what the performance benefit of inlining interactive examples would be, so we can prioritize

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#278]

**Comment by atopal** [comment]
Taks:
- [ ] 

Acceptance Criteria:
- [ ] Proof of concept that allows comparison with production interactive examples
- [ ] Performance improvement reported for JS interactive examples
- [ ] Performance improvement reported for CSS interactive examples
- [ ] Performance improvement reported for HTML interactive examples

**Comment by hobinjk** [comment]
The root problem is that IEs involve loading tons of resources in an iframe which is also the hero content for the page. I think these acceptance criteria match up with that a bit more since I think the same performance improvements will apply to all classes of IEs.

- [ ] Measure current performance of JS, CSS, and HTML interactive examples
- [ ] Pick the slowest of JS, CSS, and HTML IEs to evaluate further, unless all three have significantly different profiles
- [ ] Measure performance of IE with code fully inlined
- [ ] Measure performance of IE with frame on same origin (no second connection required)

**Comment by hobinjk** [comment]
Inline loads and completes earlier (start 0s, interactive 0.8s, complete 3s). On the other hand, the embed starts late but completes relatively quickly (start 3.2s, interactive 3.8s, complete 4.5s). The inline also has CSS issues that highlight the potential issues that would come with "real" inlining.

Inlined timeline:
![box-shadow-inline.gif](https://images.zenhubusercontent.com/5b4f43e0822079669831e125/4881528c-f62c-41f9-bee1-1d610f87b71d)

Embedded timeline:
![box-shadow-embed.gif](https://images.zenhubusercontent.com/5b4f43e0822079669831e125/e719a27a-da8b-48e7-b300-70eb1edb609a)

**Comment by atopal** [comment]
James, can you share the profiles for both cases?

**Comment by hobinjk** [comment]
Sorry for not providing the link here! It was only in the user stories tracking spreadsheet before. https://docs.google.com/spreadsheets/d/14-Vjq-gmZSB1Y7ZI8jexnowTTpVSJLvrTAS5nMCjbNU/edit#gid=0
Unfortunately it's only visible to Mozilla employees, so the tl;dr of that for anyone following along is this timing data:

Inlined loaded | Inlined interactive | Inlined complete
24.6 | 838.8 | 3061

Embedded loaded | Embedded interactive | Embedded complete
3254.4 | 3860.2 | 4520.6

**Comment by jmswisher** [comment]
@hobinjk @atopal Can this issue be closed?

**Comment by atopal** [comment]
@hobinjk were the results measured with the JS and HTML interactive examples too, or only the CSS ones? 

Noting here that the linked spreadsheet has 5 measurements. The time to interactive is at least 75% better in the inlined version.

**Comment by jmswisher** [comment]
Can this be closed? If not all the ACs were met, perhaps we need a new issue?

**Comment by atopal** [comment]
Yes, this was synthetic testing showing good results, the current work is on real user metricss
