### ISSUE TITLE
/en-US/docs/Web/API/Document/getElementsByClassName

### ISSUE THREAD

**Issue by PinkDev1** [mdn/sprints#2810]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName
It should be noted that the following example:
> Get all elements that have a class of 'test', inside of an element that has the ID of 'main':
`document.getElementById('main').getElementsByClassName('test')`

Does NOT imply that the following would be possible in a similar manner:

_Get all elements that have a CLASS of 'test', inside of an element that has the CLASS of 'main':_
`document.getElementsByClassName("main").getElementsByClassName("test")`

**PROOF that finding an element of a certain CLASS INSIDE another element of a certain CLASS is not possible using a similar sintaxys:** https://jsbin.com/pebumoyuga/1/edit?html,output

**Comment by chrisdavidmills** [comment]
Yes. The code line you've written above doesn't work because `getElementsByClassName()` has to be called on `document`, or a reference to an element that you want to search inside for elements with a particular class (or particular classes).

When you chain two `getElementsByClassName()` calls together, you are trying to call the second one on an `HTMLCollection`, which won't work.

In the JSBin example you've provided, the following would work:

`console.log(document.getElementsByClassName("nest")[0].getElementsByClassName("egg"));`

`console.log(document.querySelector(".nest").getElementsByClassName("egg"));`

You also need to run them after the DOM has loaded, otherwise it won't work. This can be achieved by putting the `<script>` element just before the closing `</body>` tag, or by other means; see this link for more info: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#Script_loading_strategies

**Comment by PinkDev1** [comment]
omg, You're right. I should've payed more attention.
Thanks for responding! I'll close this issue.

**Comment by chrisdavidmills** [comment]
> omg, You're right. I should've payed more attention.
Thanks for responding! I'll close this issue.

You're welcome, always happy to help!
