### ISSUE TITLE
/fr/docs/Web/JavaScript/Reference/Opérateurs/Opérateurs_logiques

### ISSUE THREAD

**Issue by JGrimbert** [mdn/sprints#2906]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
False translation in this page. In the description part :

> Renvoie expr1 si cette expression peut être convertie en false, sinon renvoie expr2. Donc, lorsqu'il est utilisé `avec des valeurs booléennes`, && renvoie true` si les deux opérandes peuvent être converties en true`, sinon il renvoie false. 

This sentence is confusing : If second operand was converted : 
- `true && 1` should return true.
- The second operand would not be a boolean.

This description is suffisant :
> Renvoie expr1 si cette expression peut être convertie en false, sinon renvoie expr2. 

Idem for || operator

**Comment by SphinxKnight** [comment]
fixed with https://wiki.developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs/Op%C3%A9rateurs_logiques$compare?locale=fr&to=1611615&from=1562654

@JGrimbert Thanks for reporting, I concur this was not necessary nor "efficient". Please do not hesitate to edit pages if you see such mistakes :) (anyone can contribute)
