### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications$history

### ISSUE THREAD

**Issue by joekingTheThird3** [mdn/sprints#3076]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

in section 'Example: Showing thumbnails of user-selected images'
code has img.file = file;
seems like you can't do that, you have to create the attribute - I changed to
img.setAttribute("file",file.name);
We now have made an attribute and the value is the file.name. Not sure how you would get the full path to the actual file. Interesting that if you reference an attribute that doesn't exist it gives me no error.

**Comment by chrisdavidmills** [comment]
Hi @joekingTheThird3 !

This is a bit of weird example. This works firstly because HTML is permissive — you can set any attribute you like on an element, and it will work. It just won't give you any special abilities. And secondly, you are basically just adding a property to an object instance that represents an image element. If the property doesn't already exist, then it will be added.

One thing — you mention that `img.file = file` doesn't work. Doesn't `img.file = file.name` work? This would effectively be doing the same thing as `img.setAttribute("file",file.name);`, surely?

We are basically just using the anonymous attribute as a data store. It would be better to use a [data attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) for this purpose — that's the official way of doing such a thing.
