### ISSUE TITLE
/en-US/docs/Web/CSS/Containing_block - define "table container"

### ISSUE THREAD

**Issue by anno1985** [mdn/sprints#3087]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

[The article](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block) mentions a "table container", but the term [doesn't seem to be defined on MDN yet](https://www.google.com/search?q=mdn+%22table+container%22+site%3Adeveloper.mozilla.org).
> If the position property is static, relative, or sticky, the containing block is formed by the edge of the content box of the nearest ancestor element that is either a block container (such as an inline-block, block, or list-item element) or establishes a formatting context (such as a table container, flex container, grid container, or the block container itself).

**Comment by chrisdavidmills** [comment]
@anno1985 I can't find a definition in a spec anywhere, but I'd imagine this just means the containing box given by default to a `<table>` element  on a web page, or to another element that has `display: table` set on it. We don't have a documentation section for CSS tables unfortunately; it is quite low priority really because for modern layout stuff you can just use flexbox/grid to solve the same problems but more effectively, and CSS tables were only really useful for some quite specific uses in legacy layouts. 

Maybe we could add a glossary page to cover this?

**Comment by rachelandrew** [comment]
The table wrapper box is probably what we are looking for: https://www.w3.org/TR/css-tables-3/#table-wrapper-box

It is described as creating a block formatting context, so I have updated the text and also created a couple of short glossary entries for the table wrapper box and table grid box in the PR linked above.
