### ISSUE TITLE
/en-US/docs/Web/API/Performance/timing

### ISSUE THREAD

**Issue by Dornhoth** [mdn/sprints#3093]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Hello :),
[Navigation Timing Level 2](https://w3c.github.io/navigation-timing/) still being a draft, should the [timing](https://developer.mozilla.org/en-US/docs/Web/API/Performance/timing) property really be marked as deprecated? `performance.getEntriesByType('navigation')` is not yet supported in every browser, `performance.timing` is still the way to go.
[timeOrigin](https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin) in the level 2 Performance interface doesn't correspond to timing, I think [PerformanceNavigationTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming) would make more sense.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/44942312/79052373-64d54c80-7c36-11ea-9a36-a5b891003661.png">

**Comment by sideshowbarker** [comment]
The MDN docs are correct to mark it as deprecated, given that it’s listed in the Obsolete section of the current spec https://w3c.github.io/navigation-timing/#obsolete.

So it’s appropriate for the MDN docs to let web developers know that it’s been deprecated. Without that deprecation warning, developers might otherwise have no way of realizing that it’s been deprecated.

In the case of developers who realize that it’s deprecated but choose to use it in current code anyway, that’s fine. The deprecation doesn’t prohibit any developers from using it — anyone can choose to continue to use it. The deprecation notice is just a way of telling developers, Avoid using this *unless* you’re sure what you’re doing and you understand that the code you’re writing now may eventually break at some point later if browsers end up removing this feature.

**Comment by Dornhoth** [comment]
So even though the level 2 document is still a draft, it is considered the “current  spec”?
As the alternative is still marked as an experimental feature, I find it confusing. 
The second message, linking the timeOrigin feature, is still wrong though.

**Comment by sideshowbarker** [comment]
> So even though the level 2 document is still a draft, it is considered the “current spec”?

Yes — in particular it is with regard to what the spec editors and the working group are currently recommending that web developers should use.

Some of the context for this is at https://github.com/w3c/performance-timeline/issues/68 and specifically at https://github.com/w3c/performance-timeline/issues/68#issuecomment-279152400:

> We kept `performance.timing` and all the related definitions in the draft precisely because we believed that removing it would be impossible in short~medium term. Implementers will need to support both. However, we wanted to actively discourage use of NT1 interface + provide a clear visual indication when looking at its definition

So the current intent from the spec editors and working group is to “actively discourage” use of `performance.timing`. Given that, it seems appropriate for MDN to also be accurately indicating that it’s actively discouraged.

>  As the alternative is still marked as an experimental feature, I find it confusing.

I agree. I think it’s inherently confusing, and maybe the working group can do more to mitigate some of the confusion. I raised https://github.com/w3c/performance-timeline/issues/165 to suggest they make an update to the spec. Feel free of course to weigh in there with a comment, if you have more to add.

> The second message, linking the timeOrigin property, is still wrong though.

I agree. So I updated the article to recommend `PerformanceNavigationTiming` instead — and in https://github.com/w3c/performance-timeline/issues/165 I explicitly ask the group whether that actually is the recommended replacement, and if not, what is.
