### ISSUE TITLE
Fr proxy documentation is incomplete: /fr/docs/Web/JavaScript/Reference/Objets_globaux/Proxy

### ISSUE THREAD

**Issue by Blind4Basics** [mdn/sprints#3112]
Hello,

Not sure if I should post this in french or english... Let's say english.

I just observed that the french version of the documentation about proxies is lacking the description of all the traps methods one can find in the english version.

* french: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Proxy#M%C3%A9thodes_pour_le_gestionnaire
* english: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#Methods_of_the_handler_object

I didn't check if the same problem appears for other languages.

Cheers!

**Comment by chrisdavidmills** [comment]
Hi @Blind4Basics !

Unfortunately there are a lot of translations on MDN that are not up to date with the English version. We don't ave an official transation procedure, or teams working on them all. It is done on an adhoc volunteer basis, mostly.

Would you be interested in bringing this translation to up to date? @SphinxKnight does alot of French translations, and could help you with some pointers.

**Comment by SphinxKnight** [comment]
Hello @Blind4Basics bonjour :) 

I'll go with English as well for Chris ^^.
Thanks for the feedback, there was a typo in the "macro" which was supposed to list all of the methods: that I fixed.

However this is just a quick patch and this "old" macro should be removed altogether + the page needs a bit of love. @Blind4Basics would you be interested in updating the page so that it matches the English version? If not, tell me and I'll take care :)

As Chris said, this is all done on a volunteering basis so if you want/are able to lend a hand, you're more than welcome :)

**Comment by Blind4Basics** [comment]
Hello, again,

Thanks for the suggestion (and the correction, ofc). Unfortunately, I'm only a hobbyist at coding, so... I'm sorry but I'm not volunteer to go further for now.  ;s

thx again and take care!
