### ISSUE TITLE
 [WebAPI] IndexedDB, Fx 77 tasks

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3244]
# Trello

https://trello.com/c/StA65qFA/113-indexeddb-api

# Acceptance criteria

1. - [x] [Implement IDBCursor request attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1536540)

**Comment by Elchi3** [comment]
@chrisdavidmills I didn't see this one filed in any issue for Firefox 77 yet. 
Do you want to take this one on or who would be good for IndexedDB?

**Comment by chrisdavidmills** [comment]
Sure, I can take that one. Looks like it got missed because I forgot to set it as part of the Firefox 77 epic. I'll do that now

**Comment by chrisdavidmills** [comment]
I've updated the necessary docs pages:

* https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor
* https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/request

(Well, fixed them up slightly; looks like @sideshowbarker did most of this already ;-) )

I've not added a release note yet, or updated the BCD, because I can't seem to get the feature to work in Firefox 77. I've asked the engineer about it.

**Comment by chrisdavidmills** [comment]
Ah, looks like I didn't have my Nightly updated properly ;-)

Rel note added: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/77#APIs

**Comment by chrisdavidmills** [comment]
browser-compat-data update submitted: https://github.com/mdn/browser-compat-data/pull/6177
