### ISSUE TITLE
Misc changes, Fx 78

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3292]
## Story

As a web developer, I want to know about latest miscellaneous web platform changes in Firefox.

## Acceptance criteria

The following bugs are dev-doc-complete, BCD is updated, an entry to Firefox release notes is added, experimental features page is updated, the content has been reviewed as needed.

1. - [x] [Define @@toStringTag on DOM objects](https://bugzilla.mozilla.org/show_bug.cgi?id=1277799)
2. - [x] [Enable \<link rel=preload> on Nightly and Early Beta only by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1639607)

**Comment by Elchi3** [comment]
@chrisdavidmills can you take these misc updates? If so, please estimate this issue. Thank you!

**Comment by chrisdavidmills** [comment]
I've removed the DDN keyword from 1509933, and removed it from this US. I don't think this needs docs after all.

I'm not sure what needs to be done for 1277799; I've asked evilpie for clarification here.

**Comment by chrisdavidmills** [comment]
So evilpie replied; see https://bugzilla.mozilla.org/show_bug.cgi?id=1277799#c28

The jist is, because of an `Object.prototype.toString` spec change, the engineers had to add a `Symbol.toStringTag` property to all DOM prototype objects, to expose the name used for the object inside the value returned by `toString()`.

So for example, try this in your console:

```
let test = document.createElement('button');
test.toString();
test[Symbol.toStringTag];
```

This is kind of mostly an internal detail, but it is still exposed to the web, and people could use it to do weird things.

If we wanted to document this exhaustively, we would need to add a `Symbol.toStringTag` property subpage to every Interface with a prototype. That's a lot of pages — https://developer.mozilla.org/en-US/docs/Web/API#Interfaces — and it would also require compat data for each one, etc.

This could take weeks, and I'm not convinced it is that useful. 

I'd advise adding a rel note to cover this, and then maybe mentioning it in a single, general place to cover it, in case anyone comes searching.

@Elchi3 have you any thoughts on this, and can you suggest a useful single place to document this?

**Comment by Elchi3** [comment]
Yeah, no need to add this bit to every interface. It isn't *that* important. 

Fx for devs rel note is enough and maybe an explanatory section at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag ? I don't think this needs BCD either.

**Comment by Elchi3** [comment]
@chrisdavidmills I'ved added [Enable <link rel=preload> on Nightly and Early Beta only by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1639607) here. It doesn't require full docs yet, but an update to the experimental features page. It is planned to be shipped in 79 or later. So, to be clear this task isn't the full doc work for rel=preload yet.

**Comment by chrisdavidmills** [comment]
OK, 1277799 documented:

* Section added to describe what's happened, just on the main Symbol global object docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag#toStringTag_available_on_all_DOM_prototype_objects
* Rel note added: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#JavaScript

**Comment by chrisdavidmills** [comment]
1639607 documented:

* Entry added to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#HTML

**Comment by Elchi3** [comment]
Thanks!
