### ISSUE TITLE
overflow-inline media query example shows block overflow

### ISSUE THREAD

**Issue by Kilian** [mdn/sprints#3336]
# Request type
- [x] Correction or update

# Details
If I understand overflow-inline correctly, the example on the [overflow-inline page ](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@media/overflow-inline) it should trigger if there is an inline (e.g. horizontal) scroll, but the example shows vertical (block direction) scrolling. Should the paragraph have a `white-space:nowrap` to trigger horizontal scroll instead?

**Comment by chrisdavidmills** [comment]
@Kilian yeah, I think what you are are saying makes sense. Although testing it, the media query seems to take effect regardless of whether the content is overflowing in the block or inline direction, or even at all. I think it's got more to do with the device's default behavior, rather than what you set in the CSS?

I've made the change anyway, to see what the effect is, and if this looks like it makes any more sense.

**Comment by Kilian** [comment]
Yeah, not sure how it's implemented. I think it checks the _capability_ of a user agent, though I would also expect `overflow-inline: scroll` to evaluate to false if there is an `overflow:hidden` on the `html` element, which isn't the case.
