### ISSUE TITLE
Initial ES spec was deleted from reference pages

### ISSUE THREAD

**Issue by bisubus** [mdn/sprints#3348]
## URL(s)

JS reference pages:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf
etc.

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

The problem affects all JS reference pages. `Initial definition` section is missing after mass edits by fscholz with comments like "Remove spec status column", "Remove obsolete specs / status column" dated January, 2020, e.g.:

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign$compare?locale=en-US&to=1602238&from=1599674

Currently is no way to determine that the feature belongs to ES2015 spec:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

The information is still available on editable page with `ECMAScript 2015` tag but the page isn't reachable for readers (no link) and they are unaware of it:

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

Tags aren't consistent, there's no tag for a page for ES2019 feature:

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

And a page for current spec (ES2020) feature:

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

I believe this is an important piece of information that should be available to users and not be edited out.

/cc @Elchi3

**Comment by sideshowbarker** [comment]
I agree with the changes that @Elchi3 made and so I do not agree with what this issue is proposing. We don’t attempt systematically identify which version of a particular spec was the first to define a particular feature — and we shouldn’t attempt to.

The only requirement for the Specifications data is that it provide a link to the section of the current spec in which the feature is specified. There’s no requirement for the Specifications section to do anything more than that — and attempting to make the Specifications section do more than that just creates additional work and complexity beyond what’s actually required.

I’m not asserting that information about what spec version initially defined a particular feature isn’t useful information; instead I’m just asserting that it’s not axiomatic that MDN must be the place which provides that information.

**Comment by Elchi3** [comment]
> The problem affects all JS reference pages. `Initial definition` section is missing after mass edits by fscholz with comments like "Remove spec status column", "Remove obsolete specs / status column" dated January, 2020, e.g.:

Yup, I did this on purpose. The old spec tables were linking to outdated specs which we considered harmful. Users should always consult the latest specs, not initial, outdated, wrong specs.

> I believe this is an important piece of information that should be available to users and not be edited out.

Linking to outdated specs is a no go, but we might want to consider adding the year when a feature was introduced back. So far, however, this didn't seem very important. Why is it an "important piece of information" for you? What's your use case? 

This issue will probably end up as a duplicate of https://github.com/mdn/sprints/issues/2735. Thanks for filing, though.

**Comment by cpcallen** [comment]
I concur with @bisubus that this is a bug.  As an implementor of an JS interpreter targeting multiple version of the ECMAScript spec, most of the information in MDN is too vague to be of much use, but the one thing that has until now been _extremely_ useful to me was the table containing a list of all the relevant specifications in which a given feature was added, substantially changed or removed.

Since MDN appears to be firmly set on this destructive change, is there an alternative place where one might find (and/or contribute to building) a comprehensive catalogue of changes to the spec in summary form?

**Comment by bisubus** [comment]
Thanks for the clarification. Indeed, #2735 covers this, didn't find it.

I don't see a problem with leaving links to original specs for historical purposes, yes, keeping `Initial definition: ECMAScript 2015` line without a link in `Specifications` would solve the case IMO.

My current main use case is choosing ES target for projects and making features in use to fit it. If the target is ES2018 because of syntactic features (object spread), polyfillable features from ES2019, etc need to be shimmed. If it's a lib with additional compat restrictions, we instruct end user which ES2015+ features exactly need to be polyfilled.

I know firsthand of its importance because I heavily used MDN for educational purposes previously. It would be very confusing if there were no easy and reliable way to figure out which API is ES5 and which is ES6 apart from raw specs and random articles. MDN saves lives.

**Comment by Elchi3** [comment]
> but yes, keeping `Initial definition: ECMAScript 2015` line without a link in `Specifications` would solve the case IMO.

Cool, let's continue to try to address this in https://github.com/mdn/sprints/issues/2735 then.

**Comment by Elchi3** [comment]
> Since MDN appears to be firmly set on this destructive change, is there an alternative place where one might find (and/or contribute to building) a comprehensive catalogue of changes to the spec in summary form?

I would talk to spec authors. MDN targets mostly web developers. Some specs actually do maintain a changelog, but I guess it depends on the author(s).
