### ISSUE TITLE
"HTML forms" doesn't show up

### ISSUE THREAD

**Issue by lh070355** [mdn/sprints#3357]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
In some pages under [HTML folder](https://developer.mozilla.org/en-US/docs/Learn/HTML), the "HTML forms" doesn't show up.

**Comment by chrisdavidmills** [comment]
This is because the HTMl Forms module has been moved to a new home — [Web Forms](https://developer.mozilla.org/en-US/docs/Learn/Forms) — outside of the HTML topic, because the forms module covers aspects of styling, scripting, and even server-side handling. Way more than just HTML.

But some of the static pages are not refreshed yet, so the HTML Forms module still shows up inside the HTML topic. If you see this anywhere, try force-refreshing the page (`Ctrl`/`Cmd` + `Shift` + `R`) to try to force a regeneration of the page.

Thanks for reporting.
