### ISSUE TITLE
Running parcel in section Having fun with Parcel fails /en-US

### ISSUE THREAD

**Issue by davidecr2010** [mdn/sprints#3366]
# Request type

- [x] Correction or update

# Details

The tutorial describes the installation of the NPM module parcel-bundler and later ask to run with
`parcel index.html`

This command fails to properly run as parcel command is not found in the project folder and instead should be executed as:
`npx parcel index.html` 
or 
`./node_modules/parcel-bundler/bin/cli.js index.html`

Issue described here: 
[https://stackoverflow.com/questions/59707387/parcel-command-not-found](https://stackoverflow.com/questions/59707387/parcel-command-not-found)

Seems like if the script were part of the package.json it might work like suggested but default install of parcel-bundler doesn't make that update. 

**Tested with**

_Ubuntu 20.04_
npm -v
6.14.5
node -v
v12.18.0

_Windows 10_
npm -v
6.14.5
node -v
v14.4.0

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management
Section> Having fun with Parcel

**Comment by chrisdavidmills** [comment]
Interesting. I've just tested this section again, and it seems to work fine for me. It is my understanding that since you install parcel earlier on with `npm install parcel-bundler`, you should just be able to use it with `parcel index.html`.

Maybe this is a platform difference? I am on macOS.

Just in case, I've added a note to tell the reader to try running it with `npx` if they get problems with the regular command.
