### ISSUE TITLE
U - Firefox 79 release docs (July 28th)

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3406]
# User story
As a web developer, I want to know how about new features in the latest Firefox release.

# Acceptance criteria

1. - [x] Firefox 79 release notes are updated with all DDN and DDC bugs.
2. - [x] Experimental Features page is updated.
3. - [x] platform-status is updated accordingly.
5. - [x] Hacks blogpost written about Fx 79 new features
6. - [x] Links to the Fx hacks blog post is added to the rel notes on MDN.
7. - [x] [A new version of the mdn-data npm package is released](https://github.com/mdn/data/blob/master/docs/publishing.md), if changes were made in the last sprint.
8. - [x] The BCD browser json files mark Firefox 79 as the current release

**Comment by chrisdavidmills** [comment]
I've checked all of this out:

* 79 rel notes look to be finished, and changed so that it says it is released.
* Hacks post published, and link to it added to Fx 79 rel notes
* Not sure if we need any updates to Experimental features and platform-status; couldn't see anything obvious
* Didn't do a data package push; struggling for time, and only one very small change made in the last month
* PR to update Fx versions on the BCD repo: https://github.com/mdn/browser-compat-data/pull/6446/files
