### ISSUE TITLE
MDN Learn HTML - issue with character reference equivalents 

### ISSUE THREAD

**Issue by BenRamins** [mdn/sprints#3516]
## URL(s)

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started 

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

Hi! First, I'm sorry if I'm using the wrong form. I'm new to coding and to Github! 

I believe there is a mistake in the Introduction to HTML - Getting Started page. 
In the "Single or double quotes?" section, you give this example of using HTML entities so as not to break the code:

`<a href='http://www.example.com' title='Isn&#39;t this fun?'>A link to my example.</a>`

And then, in the "Entity references: Including special characters in HTML" section, you give `&apos;` for a single quote. 

If I understand correctly, &apos is not a CURRENTLY valid HTML character entity reference. 

Thank you for reading. And apologies if I'm bringing a non-issue to your attention

**Comment by chrisdavidmills** [comment]
Hi @BenRamins !

This is the perfect place to report such a concern, so no worries there at all!

So I've looked over this bit, and I've actually changed to first instance to use the `apos` entity reference instead of the unicode thingy, for consistency, and because apos is a bit more logical to understand.

Where did you get the info that `apos` is not a valid reference? It is listed here: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Character_entity_references_in_HTML

And I also tried putting it through the W3C HTML validator and it didn't flag up an error.

**Comment by BenRamins** [comment]
I guess the consistency is what caught my eye in the first place, so thank you for the change! 

As far as `&apos;` goes, I guess I got things mixed up. The main issues I read were about best practices to support legacy browsers, in which case `&#39;` was recommended as `&apos;` used to NOT be a valid reference in HTML 4. My apologies! (like I said, I'm new...)

**Comment by chrisdavidmills** [comment]
> I guess the consistency is what caught my eye in the first place, so thank you for the change!

Cool, yeah that's definitely better.

> As far as &apos; goes, I guess I got things mixed up. The main issues I read were about best practices to support legacy browsers, in which case &#39; was recommended as &apos; used to NOT be a valid reference in HTML 4. My apologies! (like I said, I'm new...)

Ah! That makes sense. And no worries. As a beginner it is difficult sometimes to work out what is current and what is old information. It's always good to find an up-to-date source, and also to ask questions if something doesn't make sense.
