### ISSUE TITLE
br not working as they should in the firefox browser

### ISSUE THREAD

**Issue by MichaelOdumosu57** [mdn/sprints#3531]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [x ] New documentation
- [ ] Correction or update

# Details
1.JPG br is supposed to do line breaks act as a \n its not doing so here what is going on here can anyone help me debug this the site is https://bpoker.github.io/Guadalupe dont fill out the form let it fail and hit the submit button to see the dialog in question, this is only on mozilla and mozilla web browser none of the other browser even IE is having this issue
![1](https://user-images.githubusercontent.com/21322737/88454846-3889b880-ce40-11ea-8973-99626dfdf400.JPG)

**Comment by chrisdavidmills** [comment]
@MichaelOdumosu57 Hi there!

This is a really weird set of source code, and on inspection, Firefox seems to be getting served some slightly different styles to Chrome.

The problem is that *everything* is being absolutely positioned, including the `<br>` elements, which are all just sitting up in the top left hand corner of the browser window, doing nothing. I tried changing them to `position: static`, which made the phone numbers sit in a vertical line rather than being all bunched together.

But then you've still got the problem that the paragraphs are also absolutely positioned in exact places in the browser window, which means that they overlap with the lists of phone numbers, etc.

What are you using to create this layout? It would be much better if you just absolutely positioned the overall error box, and then let all the items inside it just be positioned in normal flow.
