### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/CSS/font-size

### ISSUE THREAD

**Issue by dcompcoder** [mdn/sprints#3616]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Under the heading "[Ems](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#Ems)", part of the third sentence states that "an `em` is equal to the font size of the element on which the `em` is used". However, in the fourth paragraph after this is the statement that "`em` and `ex` units on the `font-size` property are relative to the parent element's font size (unlike all other properties, where they're relative to the font size on the element)". So, which statement is correct? Is an `em` equal to the font size of the element on which the `em` is used? Or, is an `em` relative to the parent element's font size?

https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#Ems

**Comment by mdsearle** [comment]
@dcompcoder & @chrisdavidmills 

Please forgive me if I'm out of line with my comment. By way of introduction/explanation, I just discovered that I can contribute to the MDN by working on issues. However, I haven't quite figured out the complete methodology for taking a task and working on it. However, I want to offer information that I believe answers @dcompcoder's question.

I found the following information in the [W3C Editor's Draft](https://drafts.csswg.org/css-values-4/#font-relative-length). 

6.1.1. Font-relative Lengths: the **em**, **ex**, cap, ch, ic, rem, lh, rlh units

The font-relative lengths refer to the font metrics of the element on which they are used—or, in the case of rem and rlh, the metrics of the root element.

[image of the word Sphinx showing how it fits on the line of text, The common typographic metrics are shown.] Image alternate text: The word 'Sphinx' annotated with various font metrics: ascender height, to the top of the h’s serif; cap height, to the visually approximate top of the S; the x-height, to the visually approximate top of the x; the baseline, along the bottom of S, h, i, n, and x; and the descender height, to the bottom fo the p.

Definitions of the em and ex unit from the Editor's draft, for your reference: 

em unit: Equal to the computed value of the font-size property of the element on which it is used.

example 1: 
The rule:
h1 { line-height: 1.2em }
means that the line height of h1 elements will be 20% greater than the font size of h1 element. On the other hand:

example 2:
h1 { font-size: 1.2em }
means that the font size of h1 elements will be 20% greater than the computed font-size inherited by h1 elements.

ex unit: Equal to the used x-height of the first available font [CSS3-FONTS]. The x-height is so-called because it is often equal to the height of the lowercase "x". However, an ex is defined even for fonts that do not contain an "x". The x-height of a font can be found in different ways. Some fonts contain reliable metrics for the x-height. If reliable font metrics are not available, UAs may determine the x-height from the height of a lowercase glyph. One possible heuristic is to look at how far the glyph for the lowercase "o" extends below the baseline, and subtract that value from the top of its bounding box. In the cases where it is impossible or impractical to determine the x-height, a value of 0.5em must be assumed.

**Comment by chrisdavidmills** [comment]
Hi @mdsearle ! Yes, this does sound relevant. I was hoping to get around to looking at this soon, but there are always so many things to do ;-)

I'd be very grateful if you could have a look at investigating/fixing this. To do so is pretty simple — you get an MDN account, then ask me to assign you to the bug you want to work on, then you have a go at fixing it, then ask me for a review.

I've written up full instructions at https://developer.mozilla.org/en-US/docs/MDN/Contribute/Fixing_MDN_content_bugs.

**Comment by mdsearle** [comment]
Thank you @chrisdavidmills. I'm glad to help, in fact, I'm excited!

I have a GitHub and an MDN account. I read your document. I don't fully understand where I ask you to assign the issue to me. Do I do that here in GitHub or on MDN?

**Comment by chrisdavidmills** [comment]
> I don't fully understand where I ask you to assign the issue to me. Do I do that here in GitHub or on MDN?

Here, in the GitHub issue. I've updated the instruction document to make it a bit more obvious, as I appreciate it wasn't ;-)

I've assigned you, as I'm assuming you want to give it a go. Please reach out if you have any questions.

**Comment by mdsearle** [comment]
@chrisdavidmills this is how I would fix the page in question:

Remove the following paragraph from underneath the Ems heading/section.

> em and ex units on the font-size property are relative to the parent element's font size (unlike all other properties, where they're relative to the font size on the element). This means em units and percentages do the same thing for font-size.

Then I would create a new heading/section to describe the Ex unit and how it works.

I think this approach resolves the problem of the Ems description contradiction, and it provides an opportunity to fully describe the Ex unit and how to use it. I don't see that there is a section for the Ex unit in the document.

If that seems like a satisfactory resolution, what is my next step?

**Comment by chrisdavidmills** [comment]
@mdsearle that sounds like a good approach to me. Your next step is to make the change, then tell us when you are done. I can have a look, and it'd be good to ask @dcompcoder to have look too, as they firstsubmitted the issue.

Thanks!

**Comment by chrisdavidmills** [comment]
@mdsearle Thanks for updating the page! I've given your work a bit of a clean up in terms of the text and the source code (a bit of cruft had crept into the markup, which is always worth checking on), but overall this was looking really good — I think your description is really helpful.

I'm closing this now, but feel free to chime in @dcompcoder is you have any other comments.

Good job.
