### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH

### ISSUE THREAD

**Issue by mi-st** [mdn/sprints#3651]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [X ] Correction or update

# Details

There is:
_PATCH (like PUT) may have side-effects on other resources._

Should be 
_PATCH (like POST) may have side-effects on other resources._

PUT is idempotent it should have any side effects. POST may have side effect.
 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH

**Comment by JennyDC2020** [comment]
Can I make the correction in [the linked page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) via editing the Wiki? 
I can also make the same change to the [Spanish](https://developer.mozilla.org/es/docs/Web/HTTP/Methods/PATCH) and the [Portuguese](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Methods/PATCH) twin pages, if helpful.

**Comment by hamishwillee** [comment]
@JennyDC2020 Thanks very much for the offer. I've made the change to the English - since I had to confirm for myself this was correct anyway. I have tried to make the change to Spanish and Portuguese but not sure I managed that correctly.

**Comment by hamishwillee** [comment]
Closed, fixed in https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH$compare?locale=en-US&to=1647264&from=1623246 . The defect report is correct/consistent - thanks for posting @mi-st .

@chrisdavidmills FWIW , I'm not exactly convinced the use of the term _**side effects** on other resources_ - in https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH (and other HTTP docs) is useful. 

I understand the intent is to say that the methods are not idempotent - they change the data in an unpredictable/inconsistent way on each call rather than having the same effect on each call. To me a side effect is some kind of observable effect other than the one intended - in this case I would assume we're saying that some other resource gets changed than the one we expect. That is not what is happening.

**Comment by hamishwillee** [comment]
OK,  closing as "Done"
