### ISSUE TITLE
Misleading CORS description

### ISSUE THREAD

**Issue by AmirNamdar** [mdn/sprints#3654]
# Request type
- [X] Correction or update

#URI
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

# Details
Hi team,
I Noticed information that can appear conflicting.
Regarding the entity (browser / server) that determines which resources can be accessed from different origins.

At the beginning of the article it appears to be that is solely the browser that restricts from the app different origins access:
> Cross-Origin Resource Sharing (CORS) is a mechanism that uses additional HTTP headers **to tell browsers to give a web application running at one origin, access to selected resources from a different origin**.

However, over the [functional overview](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Functional_overview) section of, it is told that the server controls the access restrictions:
> The Cross-Origin Resource Sharing standard works by adding new HTTP headers that let **servers describe which origins are permitted to read that information from a web browser**.

In a sense both statements are correct but the first statement alone strikes **confusing and somewhat misleading** to me.

I would change the first statement to be: 
`Cross-Origin Resource Sharing (CORS) is a headers based mechanism that **lets the server control over which origins can access its resources. Using the additional HTTP headers, browsers can give a web application** running at one origin, access to selected resources from a different origin.`

used [W3C wiki ](https://www.w3.org/wiki/CORS_Enabled#How_can_I_participate.3F) to confirm that

Thanks, 
Amir.

**Comment by sideshowbarker** [comment]
Thanks for taking time to raise this.

> At the beginning of the article it appears to be that is solely the browser that restricts from the app different origins access:
> 
> > Cross-Origin Resource Sharing (CORS) is a mechanism that uses additional HTTP headers **to tell browsers to give a web application running at one origin, access to selected resources from a different origin**.

I believe the above statement is completely accurate. The browser is the agent which enforces the same-origin policy — by default, blocking frontend JavaScript from accessing responses from any cross-origin requests — and the browser is the agent which decides whether to un-block frontend JavaScript from accessing responses if the right HTTP headers are included in the response.

And more specifically, in the CORS protocol, the browser is the *only* place where any actual blocking happens. In the CORS protocol, servers don’t do any blocking — instead servers continue to receive requests and send responses exactly as they otherwise normally do; the only difference that CORS-enabling a server makes is to cause the server to send additional HTTP headers in its responses.

> However, over the [functional overview](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Functional_overview) section of, it is told that the server controls the access restrictions:
> 
> > The Cross-Origin Resource Sharing standard works by adding new HTTP headers that let **servers describe which origins are permitted to read that information from a web browser**.

That does not say that servers “control” the access restrictions. Instead it says that servers add new HTTP headers that *describe* the origins to which they want browsers to permit read access.

> used [W3C wiki ](https://www.w3.org/wiki/CORS_Enabled#How_can_I_participate.3F) to confirm that

That wiki page is not authoritative in any way, and is years out of date. It shouldn’t be relied on for anything

> In a sense both statements are correct but the first statement alone strikes confusing and somewhat misleading to me.
> I would change the first statement to be:
> `Cross-Origin Resource Sharing (CORS) is a headers based mechanism that **lets the server control over which origins can access its resources. Using the additional HTTP headers, browsers can give a web application** running at one origin, access to selected resources from a different origin.`

With respect, I don’t consider that an improvement over the current language in the MDN article.

The behavior of the CORS protocol itself is objectively pretty confusing and counter-intuitive —  so I think the confusion here is somewhat due just to the inherently confusing nature of the CORS protocol. But I don’t think the current language in the article is misleading; that language was chosen carefully — to reflect the actual CORS protocol behavior — and I believe that language as currently written does in fact accurately reflect the actual CORS protocol behavior.

**Comment by hamishwillee** [comment]
IMO you're both right - the first statement is strictly accurate and a little unhelpful. CORS also does a little more than that - see the preflight stuff. I propose to change the first paragraph from:

> **Cross-Origin Resource Sharing** ({{Glossary("CORS")}}) is a mechanism that uses additional {{Glossary("HTTP")}} headers to tell browsers to give a web application running at one {{glossary("origin")}}, access to selected resources from a different origin. A web application executes a cross-origin HTTP request when it requests a resource that has a different origin (domain, protocol, or port) from its own.

TO

> **Cross-Origin Resource Sharing** ({{Glossary("CORS")}}) is an {{Glossary("HTTP")}}-header based mechanism that allows a server to indicate any other {{glossary("origin")}}s (domain, protocol, or port) than its own from which a browser should permit loading of resources.

And perhaps also **append** (?):

> CORS also provides mechanisms (HTTP headers) that enable making a *preflight request* to the server hosting the cross domain resource, in order to check that it will permit the actual request. These headers allow you to indicate, for example, the HTTP method and headers that will be used in the actual request. 


Further @chrisdavidmills I think this is wrong in [Same origin policy > how to add cross origin access](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#How_to_allow_cross-origin_access) it says 

> Use CORS to allow cross-origin access. CORS is a part of HTTP that lets servers specify what hosts are permitted to load content from that server.

Shouldn't it be:

> Use CORS to allow cross-origin access. CORS is a part of HTTP that lets servers specify any other hosts from which a browser should permit loading of content.

**Comment by sideshowbarker** [comment]
> CORS also provides mechanisms (HTTP headers) that enable making a preflight request to the server hosting the cross domain resource, in order to check that it will permit the actual request. These headers allow you to indicate, for example, the HTTP method and headers that will be used in the actual request.

Since the preflight is something that the browser on its own controls completely, it seems odd to me to have *“enable making a preflight request”* and *“these headers allow you to indicate”* in the description. The values of the Access-Control-Request-Headers and Access-Control-Request-Method request headers in the preflight are set completely by the browser, and the browser doesn’t programatically expose anything about the preflight OPTIONS request to frontend JavaScript code.

Also, we should be careful to use “cross-origin” and not just “cross-domain” — since even a same-domain request may be a cross-origin request (if the protocol or port number are different).

So something like the following would seem more accurate —

> CORS also relies on a mechanism by which browsers make a “preflight” request to the server hosting the cross-origin resource, in order to check that the server will permit the actual request. In that preflight, the browser sends headers which indicate the HTTP method and headers that will be used in the actual request.

**Comment by hamishwillee** [comment]
@sideshowbarker Thanks very much. I did not draw the conclusion from the preflight info in that document that it is the browser that manages the preflight request. In hindsight that is clear. I have replaced the text as you indicated. I also tidied the description further down to make this more obvious when scan-reading.

- I made a few changes in the body to replace domain with origin (where it was clear it really means origin and not domain). Feel free to subedit directly in the MDN doc if you see some I have missed. You clearly understand this much better than I do :-0
- On statement seems "flippant" - *Cross-site requests are preflighted like this since they may have implications to user data.* Do you know where I might find out more information on the implications?

**Comment by sideshowbarker** [comment]
> One statement seems "flippant" - _Cross-site requests are preflighted like this since they may have implications to user data._ Do you know where I might find out more information on the implications?

I am pretty sure that was probably intended to essentially just be restating the same thing is the part of the **Functional overview** that says, *“for HTTP request methods that can cause side-effects on server data (in particular, HTTP methods other than GET, or POST with certain MIME types)”* — in other words, the distinction that the HTTP spec makes in https://tools.ietf.org/html/rfc7231#section-4.2.1 between “safe” and “unsafe” methods.

Given that distinction is usually framed in language that talks about changing state on the server, maybe we want to consider trying to use that kind of language here. Or I dunno, maybe that just makes it less approachable to developers.

The relevant language in the original HTTP 1.0 RFC at https://tools.ietf.org/html/rfc1945#section-12.2 was this:

> The writers of client software should be aware that the software represents the user in their interactions over the Internet, and should be careful to allow the user to be aware of any actions they may take which may have an unexpected significance to themselves or others.

So maybe that _”Cross-site requests are preflighted like this since they may have implications to user data”_ language in the MDN article could be refined to say something more like:

> Cross-site requests that may have possibly-unexpected side effects on the state of user data on a server are preflighted like this to allow the server to explicitly opt-in to receiving such requests.

Stepping back, I guess another way to frame it is: for “unsafe” requests that can change server state (POST, PUT, DELETE, etc.), if the browser and server just used the mechanism that works for non-preflighted requests (that is, the server just receives the request and sends a response — with or without the Access-Control-Allow-Origin header to indicate to the browser whether should expose the response), then any surprising/unexpected side effects would have already occurred by the time the browser gets the response — so by that time it would be too late to prevent them.

So maybe another way we could word the language in the MDN article is something like:

> Cross-site requests that can change the state of user data on a server are preflighted in order to prevent the requests from having that effect unexpectedly. The preflight is what the CORS protocol uses to require servers to explicitly state the kinds of requests the server expects to receive, and that the server opts in to allowing.
