### ISSUE TITLE
SVG "dominant-baseline" page contains an example with an incorrect attribute value

### ISSUE THREAD

**Issue by willdean** [mdn/sprints#3663]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The SVG "dominant-baseline" page contains an example with an incorrect use of "baseline" as a value for this attribute.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline

The first code example contains 

```
 <text dominant-baseline="baseline" x="30" y="20">Baseline</text>
```
As one of three examples - however, "baseline" is not a valid value for this attribute, and the example only appears to work because the default "auto" gives the intended result by luck.

This 'baseline' value appears in later examples too.

I am not quite sure what the best way to correct this should be (hence not submitting a correction directly) - would `auto` be a better replacement for `baseline` if one is trying to give a simple three line example?

**Comment by chrisdavidmills** [comment]
@willdean I was tempted to use `text-bottom` as a replacement, but `text-[bottom|top]` don't seem to work either, so auto is better for now, I think.

I've replaced the `baseline` instance in the first example with `auto`, and removed the one in the second example because `auto` was already an option.
