### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

### ISSUE THREAD

**Issue by gnbl** [mdn/sprints#3676]
# Request type
- [x ] Correction or update

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color#Value

The second note states:

`Note: Any web browser that doesn't support an input of type color will naturally fall back to the type text. Because users can write colors in many different ways (such as rgb(255, 255, 0)), one way to work around this is to set a pattern attribute equal to either #[0-9a-f]{6} or #[0-9A-Fa-f]{6} (preferably the latter because some users may not expect a different result with just a letter-case change) and set a placeholder attribute equal to a color representing the expected format of the user's input, such as #ff0000.`

The [w3c validator](https://validator.w3.org/) reports using these [`<input>` attributes ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes) for type `color` as errors:

> Error: Attribute pattern is only allowed when the input type is email, password, search, tel, text, or url.
> Error: Attribute placeholder is only allowed when the input type is email, number, password, search, tel, text, or url.

The note should mention this conflict.

**Comment by sideshowbarker** [comment]
I raised https://github.com/whatwg/html/issues/5908 to start discussion about updating the HTML spec to allow input elements in the Color state to have `pattern` and `placeholder` attributes.

The spec currently does not allow that, which is why the validator is flagging it as an error.

If the spec ends up changing to allow it, then I’ll also update the validator to allow it — which will resolve this issue.

But if https://github.com/whatwg/html/issues/5908 ends up being rejected, then we’ll need to consider changing the guidance in the MDN article to align with the spec requirements.

In the meantime, I’ve updated the MDN article to add a link to that HTML spec issue.

**Comment by sideshowbarker** [comment]
Update: Over at https://github.com/whatwg/html/issues/5908 it was pointed out that all current browsers have support for doing the expected rendering for color-state input.

Specifically, there’s been support for it in Firefox since 2014 (v29), Chrome since 2012 (v20), and Safari since 2018 (v12).

I don’t know how many Safari users there might be who are still running Safari 12 or earlier, but given the way that Apple manages updates, I’d think it wouldn’t be very many.

Given all that, it seems like that note in MDN is basically obsolete.

So I now suggest that we resolve this by removing the entire note.

Let me know if you think that would be an acceptable resolution to this issue — and if not, why not (for example, if there are actually a lot of users still running Safari 12 or earlier).

**Comment by gnbl** [comment]
Sure, thanks for looking into it.

I should have mentioned before, the validator also warns:

> The color input type is not supported in all browsers. Please be sure to test, and consider using a polyfill.

This could be revised as well, then. Could it point to further information at MDN or https://caniuse.com/input-color ?

**Comment by sideshowbarker** [comment]
> Sure, thanks for looking into it.
> 
> I should have mentioned before, the validator also warns:
> 
> > The color input type is not supported in all browsers. Please be sure to test, and consider using a polyfill.
> 
> This could be revised as well, then. Could it point to further information at MDN or https://caniuse.com/input-color ?

Thanks for catching that. With Thanks for catching that. With validator/validator@637eb49, I went ahead and dropped that warning from the validator, along with all other warnings about various `input[type]` states — because we now have support for all of them in at least two current browsers (and in most cases, in all current browsers now).

I pushed that change to https://validator.w3.org/nu/ just now, so I should no longer report that warning.

**Comment by sideshowbarker** [comment]
OK, per the discussion here, I updated the MDN article to completely remove that note.

If you consider than an acceptable resolution, please feel free to go ahead and close this issue. (I don’t actually have the necessary GitHub permissions here myself to close issues.)
