### ISSUE TITLE
https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox$history

### ISSUE THREAD

**Issue by onfire4hire** [mdn/sprints#3745]
Correction
In the align-items section there is a problem in the embedded live code viewer
a height seems to be set to the parent container alongside other properties like the dotted border however the problem is that specifying a height is misleading  because the elements end up stretching to that height because it was initially set, and not the height of the tallest element that supposedly determines the height of the container as the tutorial illustrates,  typing in the .box class height: unset; solved for me
URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox#The_two_axes_of_flexbox

**Comment by rachelandrew** [comment]
The example explains that it sets a height. The height of the flex container can be defined by a height, or by the tallest item. Both are valid and it means that it is easier to see the difference caused by the different alignment methods. The text makes it clear that a height has been set.

> " Try this in the live example — I have given the flex container a height in order that you can see how the items can be moved around inside the container."

In the PR linked above I've changed the text above to mention that the height can be dictated by the tallest item or a height set on the container itself.
