### ISSUE TITLE
Wrong Inheritance for Date

### ISSUE THREAD

**Issue by roninbar** [mdn/sprints#3764]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

`Date.prototype` does not inherit from `Function.prototype`. It inherits from `Object.prototype`.
Please fix the Inheritance section of the sidebar.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by sideshowbarker** [comment]
There is code in https://github.com/mdn/kumascript/blob/master/macros/JSRef.ejs that seems to be programmatically determining whether to show **Function** or **Object** in the JS sidebar. But I don’t understand how it makes the determination for any cases other than the ones that are hardcoded there.

But maybe somebody else taking a look at that source can figure out what it’s doing (and how to correct it).

---

And speaking of hardcoding, at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object, I notice the sidebar there shows `Object` also inheriting from `Function` — and that’s because the line at https://github.com/mdn/kumascript/blob/master/macros/JSRef.ejs#L46 seems to be hardcoded to set that.

I raised https://github.com/mdn/kumascript/pull/1428 for that

**Comment by jchimene** [comment]
Looking into this.

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1517](https://github.com/mdn/content/issues/1517) via [**ZenHub**](https://www.zenhub.com/)
