### ISSUE TITLE
Immutability of JavaScript primitives

### ISSUE THREAD

**Issue by mzoz** [mdn/sprints#3772]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://wiki.developer.mozilla.org/en-US/docs/Glossary/Primitive#Another_Example_Step-by-step
This code example and the following explanation is merely indicating that JavaScript function calls pass arguments by value which can be also seen in other languages, not sufficiently a proof that primitives are immutable. 

Also it says
> All primitives are immutable, i.e., they cannot be altered.

However, in [ECMA-262 standard](https://www.ecma-international.org/ecma-262/11.0/index.html), there's zero mention of immutability of primitives except for Symbol type.

**Comment by sideshowbarker** [comment]
I agree that https://developer.mozilla.org/en-US/docs/Glossary/Primitive#Another_Example_Step-by-step example wasn’t a good example for the immutability of primitives in JavaScript, so I’ve removed that example completely. 

And anyway the https://developer.mozilla.org/en-US/docs/Glossary/Primitive page is not really where that kind of example belonged to begin with, because that example went way beyond what’s necessary for the context of a Glossary entry.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures is where any longer examples for this should be.


And at https://developer.mozilla.org/en-US/docs/Glossary/Primitive#Example there’s already an example which shows that strings in JavaScript are immutable (and really, it seems like strings are the only primitive time in JavaScript for which immutability isn’t already obvious).

> However, in [ECMA-262 standard](https://www.ecma-international.org/ecma-262/11.0/index.html), there's zero mention of immutability of primitives except for Symbol type.

I realize the spec never explicitly uses the word *immutable* for string primitives, but it seems like it follows from the fact that JavaScript assigns string by value and not by reference, and passes strings by value.

**Comment by mzoz** [comment]
Thanks for your update!
