### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

### ISSUE THREAD

**Issue by teo1978** [mdn/sprints#3851]
# Request type

Issue

# Details
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

The sentence:

> **When callbacks** queued by requestAnimationFrame() **begin to fire multiple callbacks in a single frame**, each receives the same timestamp even though time has passed during the computation of every previous callback's workload

is awfully unclear.

Is it a typo? Is it perhaps supposed to be:

> **When multiple callbacks** queued by requestAnimationFrame() **begin to fire  in a single frame**, each receives the same timestamp [...]

Either way it's confusing and needs to be made clearer, perhaps with an example.

**Comment by hamishwillee** [comment]
Thanks @teo1978. Yes that is confusing, and IMO your wording is definitely better. I don't find your version ambiguous or confusing (it implies an implementation where all callbacks queued between window paints for a particular frame are executed in a loop, with the timestamp set before the loop). 

My concern is what a user should _do_ with this information. @Rumyra is the expert. Any ideas?

**Comment by Rumyra** [comment]
I agree that the proposed sentence is clearer and am on board with the change requested.

In regards to an example it's actually within that doc anyway, this just hasn't (again) been made very clear. As a user it's useful to know this information as you should harness the use of timestamps within animations, for the reason we're discussing and also because of the reason in the warning directly underneath.

The example on that page uses the timestamp to move an animation forward, if multiple callbacks are stacked with the same timestamp nothing will happen in regards to the animation until a callback comes with a different timestamp.

Also as the callback timestamp is a DomHighResTimeStamp I would speculate having more than one callback with the same timestamp would be pretty rare, in which case I think the information we have on this page works, albeit maybe updating the example section to re-iterate this point.

Happy to be assigned if you need @hamishwillee

**Comment by hamishwillee** [comment]
Hi @Rumyra

I updated the page with the text above and a forward reference to the example:

> When multiple callbacks queued by `requestAnimationFrame()` begin to fire in a single frame, each receives the same timestamp even though time has passed during the computation of every previous callback's workload (in the code example below we only animate the frame when the timestamp changes, i.e. on the first callback).

I have assigned this to you for any further changes you think necessary! Thanks very much.

**Comment by Rumyra** [comment]
Oh yeh that's brill @hamishwillee 👍

Had a check through and I have nothing more to add - all looks great.

Wondering if it's @chrisdavidmills that has authority to close :)

**Comment by chrisdavidmills** [comment]
Closed! ;-)

**Comment by hamishwillee** [comment]
> Wondering if it's @chrisdavidmills that has authority to close :)

If Chris didn't want us to close things he shouldn't have given me the power :-). Generally I'll close anything I'm fairly confident of.

**Comment by chrisdavidmills** [comment]
To be clear, I'm happy for you folks to close things if you're pretty sure they're fixed, they've had a review, etc.

**Comment by Rumyra** [comment]
Awesome & awesome - I almost clicked the big green button, but juuust wanted to make sure - will do in future :)
