### ISSUE TITLE
https://developer.mozilla.org/zh-CN/docs/Web/CSS/z-index

### ISSUE THREAD

**Issue by RolkerMan** [mdn/sprints#3891]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

In the demo section,the z-index value of the green box doesn't seemed to be the reason why it's above the dashed-box.

It is more like that the z-index of dashed box is set to an integer, which establishes a local stacking context for the dashed box, as mentioned in the docs.

See the screenshot below for more information.
![MDN 文档bug](https://user-images.githubusercontent.com/14216401/99162280-efcf7580-2736-11eb-9763-e9809c810c21.png)

https://developer.mozilla.org/zh-CN/docs/Web/CSS/z-index

**Comment by chrisdavidmills** [comment]
@RolkerMan yes, you are right. To make them not create new stacking contexts, one way is to make sure all positioned elements are in the same level of nesting in the DOM. I changed the English version so that this is fixed:

https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/z-index#Examples

What do you think? If you think this is good, can you please update the zh-CN version?

**Comment by RolkerMan** [comment]
@chrisdavidmills I'd like to update the zh-CN version, but I couldn't see the changed content you mentioned in the Example section for the en version.

**Comment by chrisdavidmills** [comment]
No worries. I've updated it myself.
