### ISSUE TITLE
[DevTools] Page inspector

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3908]
## Acceptance criteria

1. - [x] The listed features are documented sufficiently on MDN
2. - [x] BCD is updated - *HW: not applicable*
3. - [x] Interactive example and data repos are updated if appropriate - *HW: not applicable*
4. - [x] The content has been reviewed as needed
5. - [x] Set bugs to dev-doc-complete
6. - [x]  Add entry to Firefox release notes if feature is enabled in release
7. - [x] Add entry to Firefox experimental features page if feature is not yet enabled in release - *HW: Not applicable (enabled in release by default)*

## Related Gecko bugs

1. - [x] [Add functionality to display tabbing order overlay](https://bugzilla.mozilla.org/show_bug.cgi?id=1654956) — nice little addition to the Firefox accessibility inspector. Needs documenting somewhere appropriate.

**Comment by hamishwillee** [comment]
Essentially feature is a checkbox you can select to add numbered highlight showing the tab-order - the order that you would scroll through links/buttons if you press tab. This is useful because we expect pages to have a logical tab order for people who can't use mouse, and this lets us immediately see that the order is sensible.

The feature is not dynamic; if there is a closed panel when you select the checkbox, the items will not automatically update once you have 

Docs that need to be updated.
- Needs to be added here: https://wiki.developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector
- May also need cross links from: 
  - https://wiki.developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#UI_controls
  - https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Accessibility

Note https://wiki.developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector is a little out of date in term of some UI elements -e.g. the [turn off button](https://bugzilla.mozilla.org/show_bug.cgi?id=1632937#c3). Might need to cleanup a few images.

**Comment by chrisdavidmills** [comment]
Reviewed, small edits made, but very happy with this; reads really nicely.

Thanks @hamishwillee !
