### ISSUE TITLE
Specifications link for ShadowRoot.delegatesFocus should be removed

### ISSUE THREAD

**Issue by unarist** [mdn/sprints#3917]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

https://wiki.developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus

This article refers to https://dom.spec.whatwg.org/#shadowroot-delegates-focus but the spec only mentions about an internal field, not a public attribute on interfaces. So the link should be removed I think.

**Comment by sideshowbarker** [comment]
cc @gregwhitworth, who added the spec link (to place in the spec where the internal field is defined)

For the record here, in Blink `ShadowRoot` objects do expose a `delegatesFocus` attribute — because the Blink IDL at https://chromium.googlesource.com/chromium/src/+/refs/heads/master/third_party/blink/renderer/core/dom/shadow_root.idl has it. But it’s not clear why — since no such property is defined in the IDL at https://dom.spec.whatwg.org/#interface-shadowroot for `ShadowRoot`, nor being defined in the interface chain `ShadowRoot` inherits from (`Node`/`DocumentFragment`)

So I’ve raised https://github.com/mdn/browser-compat-data/pull/7620 to mark this as non-standard in BCD.

**Comment by chrisdavidmills** [comment]
I think I've fixed the spec link too: https://github.com/mdn/content/commit/196fb5d90f7551993e729a2a9fd422e2f482eacd
