### ISSUE TITLE
Link (ARIA Form)

### ISSUE THREAD

**Issue by LUCASLATORRE** [mdn/sprints#3982]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
Hi. Please, I can't access this link that says more information about forms with ARIA.

https://developer.mozilla.org/en-US/Accessibility/Accessible_forms

Thanks a lot.

**Comment by LUCASLATORRE** [comment]
This link I found in the documentation it self at this link: https://developer.mozilla.org/pt-BR/docs/Web/Accessibility/ARIA/Web_applications_and_ARIA_FAQ

**Comment by chrisdavidmills** [comment]
Hi @LUCASLATORRE !

Yeah, that forms article no longer exists at that URL. I found the closest article that we still have, and updated the link in the English version so that it points to the correct place.

Unfortunately we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
