### ISSUE TITLE
img onerror is deprecated?

### ISSUE THREAD

**Issue by dartess** [mdn/sprints#4014]
## URL(s)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img

## Request type

- [ ] New documentation
- [x] Correction or update

## Details

The `onerror` attribute is marked as deprecated. However, I don't understand why.

[Image loading errors](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#image_loading_errors) sections does not contain any notes about it.  Internet searches also came to nothing. This is confusing.

**Comment by hamishwillee** [comment]
@teoli2003 as per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#browser_compatibility the `onerror` is marked as deprecated for the `img` element - can you answer why?
I'm asking you because you added this data in https://github.com/mdn/browser-compat-data/pull/388

It is also shown as deprecated in [caniuse](https://caniuse.com/mdn-html_elements_img_onerror) but that could just be a data copy from MDN

**Comment by ZaneCEO** [comment]
Also discussed here: https://stackoverflow.com/a/77278205/1204976

**Comment by ferdnyc** [comment]
@dartess

My PR to remove the deprecation flag from `onerror` was just merged, this can (finally!) be closed. Our long <s>national</s> global nightmare is over.

**Comment by ferdnyc** [comment]
(And in fact, [the MDN `<img>` page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#browser_compatibility) is already updated!)

**Comment by dipikabh** [comment]
Thanks, @ferdnyc for your contribution and persistence to get this fixed. Closing this one because the related browser-compact-data PR is merged.

**Comment by dartess** [comment]
@ferdnyc better late than never :)
