### ISSUE TITLE
Link to discontinued site and not existing document

### ISSUE THREAD

**Issue by pasta23pl** [mdn/sprints#4018]
# Request type

- [] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x ] Correction or update

# Details

https://developer.mozilla.org/pl/docs/Web/Tutorials
Tutoriale Javascript -> JavaScript Best Practices (WebPlatform.org) -> https://webplatform.github.io/docs/wiki/tutorials/javascript_best_practices

Link on the page  "JavaScript Best Practices (WebPlatform.org)" is not found
404
Please remove link or replace with https://www.w3schools.com/js/js_best_practices.asp

**Comment by pasta23pl** [comment]
Another one on the same page
JavaScript Garden
https://clarle.github.io/yui3/blog/2006/11/27/video-crockford-advjs/
404

**Comment by pasta23pl** [comment]
Actually there is more and more, don't understand why links point to English sites, if this is PL translation, shouldn't they point to Polish documents only?

**Comment by hamishwillee** [comment]
Thanks for reporting. Closing, because the Polish translation is frozen: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize

Note, if you are able to unfreeze the translation, then the rules for what links exist etc would largely be up to the translation teams. Most teams seem to keep English links unless there is a good alternative in the language of choice.
