### ISSUE TITLE
The images don't load

### ISSUE THREAD

**Issue by LEIMAG7** [mdn/sprints#4029]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Does not load any of the images on the MDN website when translated into Spanish and other languages: https://developer.mozilla.org/es/docs/Learn/HTML
![ScreenShot_20220713164344](https://user-images.githubusercontent.com/103673753/178849785-843c40f4-183b-468d-a590-53fa7ebd73bb.png)
![ScreenShot_20220713164032](https://user-images.githubusercontent.com/103673753/178849803-28a0ea42-4cd5-4362-930f-fd8844744e96.png)
![ScreenShot_20220713164234](https://user-images.githubusercontent.com/103673753/178849824-b9dc93b6-94c1-45f5-b307-5c5f42bd5400.png)
![ScreenShot_20220713164359](https://user-images.githubusercontent.com/103673753/178849832-cd6a7271-1fc8-43b3-beeb-e7821f6ef3d2.png)

**Comment by queengooborg** [comment]
Hi @LEIMAG7! This repository (mdn/sprints) isn't really used to track MDN issues any longer. If this is still an issue, please scroll down to the "Found a content problem with this page?" section and use the "Report the content issue" link to report the issue on the appropriate repository (mdn/translated-content) so that the appropriate team can resolve your issue quickly. Thank you in advance!

**Comment by hamishwillee** [comment]
@Rumyra Should we be archiving or at least locking this repo to new input except from core team?  Confusing to have yet another way to post and track stuff.
