### ISSUE TITLE
Wrong link on page "Promises benutzen"

### ISSUE THREAD

**Issue by Skasi** [mdn/sprints#4030]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The "async/await" link at the end of the [German MDN article "Using Promises"](https://developer.mozilla.org/de/docs/Web/JavaScript/Guide/Using_promises#siehe_auch) links to an English "queueMicrotasks" article instead of async/await. See this screenshot:

![grafik](https://user-images.githubusercontent.com/132906/184122130-e8e3ea90-80c5-44be-b6c5-f16ee683097d.png)

This is the wrong link:
❌ https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask

I used the English "Using Promises" page to find the correct link for async/await. This would be the correct link for the German version:
✔️ https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by queengooborg** [comment]
Hi @Skasi! This repository (mdn/sprints) isn't really used to track MDN issues any longer. If this is still an issue, please scroll down to the "Found a content problem with this page?" section and use the "Report the content issue" link to report the issue on the appropriate repository (mdn/content) so that the appropriate team can resolve your issue quickly. Thank you in advance!
