### ISSUE TITLE
no content 

### ISSUE THREAD

**Issue by mahoni1105** [mdn/sprints#4037]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update
Correction or update

# Details

when i press the button "guides" no content in Russian language
https://developer.mozilla.org/ru/docs/Learn

https://developer.mozilla.org/ru/docs/Learn
![scrin](https://user-images.githubusercontent.com/123073839/223022337-de53d82a-2a38-4327-8542-84db49bd700e.png)

**Comment by queengooborg** [comment]
Hi there!  This repository (mdn/sprints) isn't really used to track MDN issues any longer.  If this is still an issue, please scroll down to the "Found a content problem with this page?" section and use the "Report the content issue" link to report the issue on the appropriate repository (mdn/translated-content) so that the appropriate team can resolve your issue quickly.  Thank you in advance!

**Comment by caugner** [comment]
This seems to have been fixed in the mean-time, see: https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/Installing_basic_software

![Image](https://github.com/mdn/sprints/assets/495429/affe96b9-1958-4ee4-ac19-773c4ff7ad16)
