### ISSUE TITLE
Tutorials of "Implement a settings page" should use synced storage

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#410]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415798

# Acceptance criteria

- [ ] Update example(s) in page to use storage.sync
- [ ] Update example(s) in examples repo as appropriate.

**Comment by irenesmith** [comment]
[Implement a settings page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page)

Updated the page so that the example uses storage.sync instead of storage.local
I also added the necessary id key to the manifest

Finally, modified the code description to talk about storage.syn and added a note that is possible to store settings in local storage instead.
