### ISSUE TITLE
User Guide: Media Capabilities

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#415]
Create Overview page for Media Capabilities API

## User Story

FF63 is launching with mediaCapabilities. Docs on the API are complete. Need a user guide.

## Acceptance Criteria

[X] User guide complete
[] usable interactive fully functional example

**Comment by estelle** [comment]
a guide article called "Using the API", which is a subpage of the main API landing page and describes how to use the API at a basic level.

**Comment by estelle** [comment]
Having issues with the live example not showing....

**Comment by chrisdavidmills** [comment]
Live example now fixed, thanks to @jwhitlock ; I also tweaked it a bit.

I did a review/copy edit of the article; here's some feedback!

1. Make sure all titles are written in sentence case, not all words capitalized
2. I moved it to https://developer.mozilla.org/en-US/docs/Web/API/Media_Capabilities_API/Using_the_Media_Capabilities_API — all usage guides should be put as children on the main API landing page
3. The live example was broken because the specified ID inside the first parameter did not match the ID of the heading the same code is contained under (in this case, the "Media Capabilities live example" `<h2>`). Always check this first if you get problems with live examples.
4. I added two more parameters to your live sample call — a width and height respectively.
5. Remember that the actual API is called "Media Capabilities API", not the space between the two words; the main interface is MediaCapabilities. I changes a few instances as I copy edited the article.
6. You're using CSS-style comments in your JS examples for single line comments. The double slash syntax is preferred in single line cases.
7. You've still not created https://developer.mozilla.org/en-US/docs/Web/API/WorkerNavigator/mediaCapabilities, right? No biggie, but just checking.
