### ISSUE TITLE
Update Third party APIs article

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#655]
Our [third party APIs learning area tutorial](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs) needs updating so that the Google Maps API examples work. It also needs checking generally.

# Acceptance criteria

1. - [x] Google Maps API examples updated so that they work.
2. - [x] Article updated to suit
3. - [x] Rest of the examples tested to see if they work, and updated as necessary

# Tasks

See above.

**Comment by chrisdavidmills** [comment]
First bit of work done — update https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction to remove references to Geolocation API and Google Maps, and replace then with a simple Web Audio API example instead.

Long story short, I worked out how to use the new Google Maps API, but Geolocation seems really fiddly and broken across browsers, especially on macOS. I decided to remove it, to save learners from the pain of fiddling with it.

**Comment by wbamberg** [comment]
@chrisdavidmills , I can do this.

**Comment by chrisdavidmills** [comment]
@wbamberg yay, thanks Will!

**Comment by wbamberg** [comment]
## Comments

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Third_party_APIs

-----------

>  just _get all our code examples_ at once"

Not strictly in scope, but the link tells people to:

1. install Git
2. get a GitHub account
3. clone

For people just playing around, who don't already have this set up, it's much easier to just download the ZIP from GitHub, so this page should explain that as an alternative. Also even if you do want to clone the examples, you don't need a GitHub account (I think?).

------------

> Some APIs handle access to their functionality slightly differently, requiring the developer to make an HTTP request to a specific URL pattern to retrieve data (see _Fetching data from the server_).

I don't think this is a helpful link at this point. It would be better to link to the RESTful example lower down the page, than to plunge someone into XHR/Fetch here.

-------------

> Permissions are handled differently

I don't know if this is worth saying, but it's not just that the mechanism is different - the whole purpose is different. Permissions prompts for built-in APIs are designed to protect the user. API keys are designed to protect the API provider.

In fact I'd suggest omitting any comparison with permissions prompts here, and just call this section "They (usually) require API keys"

-------------

> they tend to use key codes

"key codes" makes me think of keyboard keys. Maybe just "keys" is better here?

------------

> The point of requiring a key is so that not just anybody can use API functionality without any accountability.

This sentence is a bit tortured. Better: "Requiring a key enables the API provider to hold users of the API accountable."

------------

> Next, get your developer key using the following steps:

Wow what a rigmarole. You're not going to like this, but I think that for an introductory article this is too much, and we should choose a different API. Signing up is OK (necessary for almost all APIs I think) but requiring a credit card is a much bigger obstacle. I don't want to give them my CC. Many people don't have one.

(Actually I have an old Google key with no CC, and it kind of works, although you get a "for development purposes only" overlay.)

Also Google's UI for these things is complex and subject to frequent changes, compared with most other sites. It's much better when you can just say "sign up for a key" and trust that the site will have a decent UI guiding people through.

------------

> Adding a custom marker", step 3

The code sample here:

```js
var marker = new google.maps.Marker({
  position: latlng,
  icon: iconBase + 'flag_maps.png',
  map: map
});
```

...doesn't work because `latlng` isn't defined. In the previous iteration, `position` is a literal.

------------

> See _Map marker or Icon names_ to

This link gets a deprecation warning. Fusion tables (whatever these are) are going away.

-------------

This code:

```js
var contentString = '<div id="content"><h2 id="firstHeading" class="firstHeading">Custom info window</h2><p>This is a cool custom info window.</p></div>';
```

Would be much better as a multiline template literal:

```js
var contentString = 
  `<div id="content">
     <h2 id="firstHeading" class="firstHeading">Custom info window</h2>
     <p>This is a cool custom info window.</p>
  </div>`;
```

----------

In this code:

```js
var infowindow = new google.maps.InfoWindow({
  content: contentString
});
```

Should be `infoWindow`? (i.e. use camelCase for variable names?)

-----------

> To sign up for an NYTimes API key, you need to go to https://developer.nytimes.com/signup.

That link has moved. And the new link in that page is broken. Surely it's better to send people to https://developer.nytimes.com/ ?

------------

> Next, wait a few minutes, then get the key from your email.

This wasn't how the process worked for me - the key was in the page after I asked to create it. Perhaps the process has changed?

-------------

> between the API, and your app

Remove this comma.

-------------

> This runs a function called fetchResults() when the form is submitted (the button is pressed).

It looks like it actually runs a function called `submitSearch`:

```js
searchForm.addEventListener('submit', submitSearch);
```

 (I know, which calls `fetchResults`, but still this looks wrong).

------------

This code:

```js
// Assemble the full URL
url = baseURL + '?api-key=' + key + '&page=' + pageNumber + '&q=' + searchTerm.value + '&fq=document_type:("article")';
```

Would be much nicer with a string literal.

-------------

> So, a complete URL would end up looking something like this: `https://api.nytimes.com/svc/search/v2/articlesearch.json?api-key=4f3c267e125943d79b0a3e679f608a78&page=0&q=cats
&fq=document_type:("article")&begin_date=20170301&end_date=20170312`


Do you want to have a real API key in this example URL?

-------------

> Note: You can find more details of what URL parameters can be included in the _Article Search API reference_.

Link is 404. It will be much less fragile just to point people at the top-level docs for the API.

-------------

In this code:

```js
function displayResults(json) {
...
};
```

...extra `;` at the end of this function.

--------------

> To work out which properties in the article objects contained the right data to show, we consulted the _Article Search API reference_.

404 again.

----------------

> If you try the example now, it should work, although the pagination buttons won't work yet.

This example doesn't work for me - I get a CORS error (Firefox and Chrome). I get the same error with the finished example from GitHub. That makes it hard for me to review some of the other code in this example since I can't see its effect.

-----------------

> (this technique is needed at the time of writing to stop floated layouts from breaking.)

Consider using flex or grid instead of floated layouts?

-----------------

> and returning the results, so you don't have to write them out yourself using say fetch or XHR.

"say fetch or XHR" is a little sloppy for beginners. At least it should link Fetch and XHR to docs.

------------------

https://github.com/mdn/learning-area/blob/master/javascript/apis/third-party-apis/youtube/index.html#L57-L68 - similar comment as above, this is very fragile given how often Google changes their UIs.

------------------

> We also built another example for you to study and learn from — see our _YouTube video search example_. This uses two related APIs:

The mdn.github.io page linked here doesn't work, I believe because a valid API key isn't included. That's expected, but there's not much point publishing to github.io an example that won't work - the whole point of github.io examples is that they work out of the box.

----------------

> You'll still need to get an API key and insert it into the code to get it working, like with the other examples.

I wasn't able to get this example working even after adding an API key. In Chrome I get this in the console:

"Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null')."

Perhaps it doesn't work for a file:// URL?

Again that makes it hard for me to review some of the other code in this example since I can't see its effect.

--------------

Overall comments:

* I haven't commented in detail on code style stuff. But I think we should consider using "modern JS" idioms (`let` and `const`, arrow functions, `for...of`, template literals) in our examples. I'd love for us to be teaching this stuff.

* I'd suggest we have less detailed info on how to get an API key (i.e. walking people through the screens on someone else's site) because it's so likely to get out of date, and that's a really frustrating experience. Better to point them at the developer page and hope it is usable.

* As I said, I'd suggest not using Google APIs for this, but instead choosing third-party APIs with less onerous key requirements, better stability, and better UIs for getting keys. The NYT example is fine for that.

**Comment by chrisdavidmills** [comment]
> For people just playing around, who don't already have this set up, it's much easier to just download the ZIP from GitHub

This is a good point. I've updated that section to first give the reader a direct link to the zip, in case they don't want to do all that GitHub malarkey.

> It would be better to link to the RESTful example lower down the page, than to plunge someone into XHR/Fetch here.

Good point; changed.

> In fact I'd suggest omitting any comparison with permissions prompts here, and just call this section "They (usually) require API keys"

I changed the title as requested, but I did still keep in the comparison, adding a note to say that API keys are more to protect API vendors. I thought this was interesting and useful.

> "key codes" makes me think of keyboard keys. Maybe just "keys" is better here?

Agreed. Updated to "developer keys"

> "The point of requiring a key is so that not just anybody can use API functionality without any accountability.

Yup, agree it is tortured. I have updated it!"

> doesn't work because latlng isn't defined. In the previous iteration, position is a literal.

Good catch — updated.

**Comment by chrisdavidmills** [comment]
> This link gets a deprecation warning. Fusion tables (whatever these are) are going away.

I've removed the link until I work out what to do here.

> Would be much better as a multiline template literal:

I'm going to leave this as is for now; I might be getting rid of the Google Maps API example.

> Should be infoWindow? (i.e. use camelCase for variable names?)

Yes, it really should. Fixed!

> That link has moved. And the new link in that page is broken. Surely it's better to send people to https://developer.nytimes.com/ ?

I've sent them to the getting-started page, which works.

> This wasn't how the process worked for me - the key was in the page after I asked to create it. Perhaps the process has changed?

Damn, looks like it. I've updated the instructions.

>> between the API, and your app

> Remove this comma.

I've done so.

> It looks like it actually runs a function called submitSearch:

Ah yes, updated!

> Do you want to have a real API key in this example URL?

Nope, oops! Placeholder put in.

> Link is 404. It will be much less fragile just to point people at the top-level docs for the API.

Agreed. Fixed.

> extra ; at the end of this function.

Removed!

> 404 again.

Fixed, again.

> This example doesn't work for me - I get a CORS error (Firefox and Chrome). I get the same error with the finished example from GitHub. That makes it hard for me to review some of the other code in this example since I can't see its effect.

Hrm, it seems to work for me. Have you got your API key put in place? This is needed.

> Consider using flex or grid instead of floated layouts?

Given that layout isn't the main purpose of this tutorial, I'm gonna skip this one.

> "say fetch or XHR" is a little sloppy for beginners. At least it should link Fetch and XHR to docs.

I've just deleted this bit, as it didn't really add much anyway.

> similar comment as above, this is very fragile given how often Google changes their UIs.

Again, I might get rid of this example. Haven't decided what to do yet.

> The mdn.github.io page linked here doesn't work, I believe because a valid API key isn't included. That's expected, but there's not much point publishing to github.io an example that won't work - the whole point of github.io examples is that they work out of the box.

Good point. I've removed the link to the gh-pages example.

**Comment by chrisdavidmills** [comment]
> I haven't commented in detail on code style stuff. But I think we should consider using "modern JS" idioms (let and const, arrow functions, for...of, template literals) in our examples. I'd love for us to be teaching this stuff.

There is a initiative started to change all of the learning area to use let/const. Finding time to do it is just a pain. I will leave this for now, as I'm already starting to spend way longer on this update than I'd hoped.

> I'd suggest we have less detailed info on how to get an API key (i.e. walking people through the screens on someone else's site) because it's so likely to get out of date, and that's a really frustrating experience. Better to point them at the developer page and hope it is usable.\

Yup, I think this is a good point. I've alfready made this better, and as I said before, I'll probably get rid of the Google Maps example. I'm thinking of replaceing it with [MapQuest](https://developer.mapquest.com/documentation/mapquest-js/v1.3/), which seems less painful. I'll try and write an example to cover this tomorrow.


As I said, I'd suggest not using Google APIs for this, but instead choosing third-party APIs with less onerous key requirements, better stability, and better UIs for getting keys. The NYT example is fine for that.

**Comment by wbamberg** [comment]
Thanks for the updates Chris, they look good to me. I'm glad you're considering using a different example.

>>  This example doesn't work for me - I get a CORS error (Firefox and Chrome). I get the same error with the finished example from GitHub. That makes it hard for me to review some of the other code in this example since I can't see its effect.

> Hrm, it seems to work for me. Have you got your API key put in place? This is needed.

Yes, with the API key. Without it you get 401 (unauthorized) error. I get the CORS error with the key I got, and also with the key that you had embedded in the URL above. In Chrome the error is:

```
Access to fetch at 'https://api.nytimes.com/svc/search/v2/articlesearch.json?api-key=
MY_KEY&page=0&q=sdd&fq=document_type:(%22article%22)' from origin 'null' has
been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains
multiple values '*, *', but only one is allowed. Have the server send the header with a
valid value, or, if an opaque response serves your needs, set the request's mode to
'no-cors' to fetch the resource with CORS disabled.
```

...and in Firefox something similar:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote
resource at https://api.nytimes.com/svc/search/v2/articlesearch.json?api-key=MY_KEY
&page=0&q=sssqs&fq=document_type:(%22article%22). (Reason: Multiple CORS header
‘Access-Control-Allow-Origin’ not allowed).
```

Weirdly, if I just paste the URL into the browser it works and I get the expected JSON back.

**Comment by chrisdavidmills** [comment]
Argh, this is so annoying. I literally just tested it when I was updating the article and I'm sure it worked. I've emailed the NYTimes devs about it to see if they can fix this, and I've put a note in the text at the moment to say this doesn't work and we are trying to get it fixed.

In better news, I replaced the Google Maps example with a Mapquest example, and that seems to work fine and be a lot simpler to work through.

**Comment by chrisdavidmills** [comment]
@wbamberg Update — I talked to the NYTimes devs, and they looked into the problem. They have fixed their server, and now the NYtimes example is working fine again. Result!

**Comment by wbamberg** [comment]
Both the MapQuest and the NYTimes examples work well now, thanks for the updates. I had only one comment really: it's a bit unclear whether you intend the API key variable for the MapQuest example to have a real key or a placeholder.

Currently it has what looks like a real key in index.html (https://github.com/mdn/learning-area/blob/master/javascript/apis/third-party-apis/mapquest/index.html#L19) but a placeholder in expanded-example.html (https://github.com/mdn/learning-area/blob/master/javascript/apis/third-party-apis/mapquest/expanded-example.html#L18).

There were a few typos which I will fix if I can find them again :).

**Comment by chrisdavidmills** [comment]
Thanks for the typo fixes!

To sort out the mapquest API key issue, I've created an explicit starter file for them to start the tutorial from, which doesn't have the API key in it, just a placeholder.

I wanted to have an example that they could see working, as well as one to start from with a placeholder. These two are separate files now.

Interestingly enough, this has lead me to notice that the mapquest examples seem to work without an API key....oh well.
