### ISSUE TITLE
Impossible to edit any page of MDN

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/sprints#725]
Steps to reproduce:
1. Login into MDN
2. Open any article for edition

Current result (reproduced in release Fx/Edge/Chrome):
No editor is displayed. It's impossible to edit the content.
3 errors appear in the console

Expected result:
CKeditor loads as usual and a contributor is able to edit a page.

**Comment by SphinxKnight** [comment]
[developer.mozilla.org-1544770319746.log](https://github.com/mdn/sprints/files/2678934/developer.mozilla.org-1544770319746.log)
Here is the log I got from Chrome

**Comment by schalkneethling** [comment]
And of course it works fine when running locally ;p - Makes me think it has something to do with the build maybe? The file it is failing to load is in the bundle. What I do notice however is that the source is located at:

```
kuma/static/js/libs/ckeditor/source/plugins/a11ychecker/lang/en.js
```

And the build is at:

```
kuma/static/js/libs/ckeditor/build/ckeditor/lang/en.js
```

The one it is failing to load is at:

```
/static/js/libs/ckeditor/build/ckeditor/plugins/a11ychecker/lang/en.js?t=IBDI
```

**Comment by schalkneethling** [comment]
The file it is after seems to be located here instead:
https://developer.mozilla.org/static/js/libs/ckeditor/build/ckeditor/lang/en.js?t=IBDI

**Comment by a2sheppy** [comment]
Yeah, it sounds like the editor didn't get rebuilt ant its files checked in, maybe.

**Comment by a2sheppy** [comment]
It looks like `a11yhelp` got added to the build, but not `a11ychecker`.

**Comment by chrisdavidmills** [comment]
Weirdly enough, it looks like some people are still managing to make edits.

**Comment by jwhitlock** [comment]
The build is fine, as shown by it working in development and staging. The issue is that the production CDN was returning last week's version of this file:

https://developer.mozilla.org/static/js/libs/ckeditor/build/ckeditor/lang/en.js?t=IBDI

CKEditor uses the build timestamp (``t=IBDI``) for cache breaking, but our CDN discards all query string parameters for the ``/static`` path. It appears we need an exception for ``t=`` for the CKEditor build folder.

The CDN is composed of many caching servers distributed globally. My guess is that some people were able to edit because their CDN had the more recent copy of ``en.js``. 

If we waited a week, editing would work for everyone. However, in the holiday spirit, I told the CDN to invalidate the cache for this folder and download fresh files. Editing should now work for everyone.

**Comment by SphinxKnight** [comment]
Confirming it works now on my "edge"
