### ISSUE TITLE
DDN 65: env() page

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#775]
CSS environment variables (the env() function) have been implemented https://bugzilla.mozilla.org/show_bug.cgi?id=1462233
https://drafts.csswg.org/css-env-1/#env-function
https://developer.mozilla.org/en-US/docs/Web/CSS/env

Explaination needs help

- [X] - BCD
- [X] - data/syntax

We have a page for the env() variable, but it needs some work to get it into shape, for example cssinfo macro adding, example adding, general checking to make sure it is up-to-date wirth the latest spec.

ACCEPTANCE CRITERIA
- [X] - DDC
- [X] - https://developer.mozilla.org/en-US/docs/Web/CSS/env is grokkable

**Comment by estelle** [comment]
@chrisdavidmills Can you take a gander at https://developer.mozilla.org/en-US/docs/Web/CSS/env and see if it's more grokable. BTW, thank you for doing a chunk of it!

**Comment by chrisdavidmills** [comment]
@estelle I've given the page a review, and cleaned it up a bit. This is looking really good, thanks!

The only comment I've got is that the explanatory text in the example comment (https://developer.mozilla.org/en-US/docs/Web/CSS/env#Examples) is confusing. There's a typio in there, and I'm not sure what it is supposed to say. If you could clear that up, making it clear also that the fourth env variable is not used because it's casing is wrong thereforew the fallback is used, it would be great.

Even better, showing a couple of screen shots of what the difference is between say, desktop and a phone with a notch or an apple watch would be very useful.
