### ISSUE TITLE
"Manipulating the browser history" is unclear / disputed within the document

### ISSUE THREAD

**Issue by ben-turner** [mdn/sprints#804]
# Request type
- [ ] New documentation
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/API/History_API

# Details
The following paragraph seems to have some debate about what will happen in this scenario. The changes made [in this diff](https://developer.mozilla.org/en-US/docs/Web/API/History_API$compare?locale=en-US&to=1356534&from=1327665) are unclear, however I am completely unfamiliar with this API and therefore can't fix it with any accuracy. Guidance in how this API behaves in that situation is appreciated.

Struck-through text is as it appears in the document.

> Suppose now that the user navigates to http://google.com, then clicks the Back button. At this point, the URL bar will display http://mozilla.org/bar.html, and <s>the page will get will not get a popstate event whose state object contains a copy of stateObj</s> if you read the history.state you will get the stateObj. popstate event won't be fired because the page has been reloaded. The page itself will look like bar.html.

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:
None

**Comment by irenesmith** [comment]
After testing the behavior, I have corrected the paragraph as follows:

Suppose now that the user navigates to http://google.com, then clicks the Back button. At this point, the URL bar will display http://mozilla.org/bar.html and history.state will contain the stateObj. The popstate event won't be fired because the page has been reloaded. The page itself will look like bar.html.

**Comment by ben-turner** [comment]
Thanks, @irenesmith! That looks much better now.
