### ISSUE TITLE
Use of wrong domain in Response Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by maddiel** [mdn/sprints#845]
# Request type
- [x] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*

This is a simple issue but it could be confusing for people trying to understand how CORS works. 

The **Access-Control-Allow-Origin** should return the value of the **Origin** header in the preflight request for a successful authorized response as meant in this [example](https://mdn.mozillademos.org/files/16401/preflight_.png).

You state the following only a few paragraphs before this image:
"Note that now, no domain other than http://foo.example (identified by the ORIGIN: header in the request, as in line 10 above) can access the resource in a cross-site manner. The Access-Control-Allow-Origin header should contain the value that was sent in the request's Origin header."

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:
I couldn't find any reports of this issue.

BTW, Love MDN guys!

**Comment by maddiel** [comment]
Sorry, what should be updated is the [Origin] header value to make it consistent with the examples that follow.

**Comment by hamishwillee** [comment]
This issue was posted some time ago, and it is quite possible that this was fixed in the interim.  As is it looks now I do not see any problem with the document with respect to the use of the `Origin` and `Access-Control-Allow-Origin` headers (though I did make some minor modifications to make it even more clear).

Essentially the [first example](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios) _first_ shows a simple case where the allowed origin returned is a wildcard, but at that point explains that you can instead return the domain IFF you want to restrict access. It also points to the fact that you have to set a real domain if you want to use "credentials" (and links to the appropriate sections).
Later one, when we return an actual domain this is noted.

I'll mark this as closed. If you disagree, could you please reopen this issue and make the modifications you think are necessary (we can then review!). 

Thanks!
