### ISSUE TITLE
https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/JavaScript_basics

### ISSUE THREAD

**Issue by asyashkot** [mdn/sprints#866]
# Request type
- [ ] New documentation
- [- ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/JavaScript_basics

# Details
*Please describe the change you are requesting. If you know of technical experts who can review the change, please mention them.*
Последнее задание (Добавление персонального приветственного сообщения). Нужно уточнить, что для корректной работы кода следует в настройках браузера отключить (Блокировать сторонние файлы cookie). Иначе не работает кнопка "Change user"

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by jmswisher** [comment]
Google translation: Last task (Adding a personalized welcome message). It is necessary to clarify that for the correct operation of the code should be disabled in the browser settings (Adding a personal greeting message). Otherwise, the "Change user" button does not work.

Need to check whether this is a translation update issue, or an issue in the English original.

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
