### ISSUE TITLE
KeyboardEvent/key example not working in Fx, due to e.data support

### ISSUE THREAD

**Issue by tk1** [mdn/sprints#871]
# Request type
- [ ] New documentation
- [x ] Correction or update

## Page to change
If this request relates to an existing article, please give its URL:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

# Details
The example doesn't work in Firefox. If you type an a, the message "input event. you have just inputed "undefined"" is displayed. The reason for this is that e.data is not implemented in Firefox. see https://developer.mozilla.org/en-US/docs/Web/Events/input : compatibility table, line "data"

## Related issues
If this request relates to other issues in Bugzilla or GitHub, please provide links:

**Comment by duduindo** [comment]
Yes. See the msuhr's comment  [Bugzilla#998941](https://bugzilla.mozilla.org/show_bug.cgi?id=998941#c17)

**Comment by a2sheppy** [comment]
Hahaha! This one tricked me, because the fix to implement `InputEvent.data` went in last week, so the sample was working fine for me. I'm on the fence about even fixing this, given that this will resolve itself in a few weeks.

I have made a few adjustments to the early parts of the page, and to the example, but otherwise I'm not sure this is something that we should change.

**Comment by a2sheppy** [comment]
I've added a note right below the sample output that explains the situation, and have noted on [bug 998941](https://bugzilla.mozilla.org/show_bug.cgi?id=998941) that the note needs to be removed when we document the implementation of the `data` property on `InputEvent`.
