### ISSUE TITLE
React Spike: Try server-side rendering

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#969]
# User story
As an MDN developer, I want to try React server side rendering, so I can determine whether it will be an important part of our transition to React.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1525719

As we convert pages to React, we suspect that we will need or want to use server-side rendering to improve page load time. So this user story is about figuring out how to do that and how to integrate into our build and deploy system. And about determining how  much it improves performance.

This work is likely to require integration with our Django build system, and so it should probably wait until after John has done some work to document and update the build system.

# Acceptance criteria
- server side rendering is working for a test endpoint, possibly only handling the logged-out case and not yet working for logged-in users
- server-side rendering works automatically as part of the build process
- we have data showing the impact of SSR on page load times.

**Comment by davidflanagan** [comment]
@unclechu: let's move the discussion of SSR here, since this is the user story about that.

In your last comment over on the other thread, it sounded like you were talking about having a Node server to do SSR on demand. We're not ready to go that far. What I'd like to explore as part of this user story is whether we can do SSR as part of the build process, and integrate the output of React SSR into the Jinja templates that our python server uses.

That may not be what you volunteered to help with, but if you have any expertise in setting up that kidn of build-time SSR, your suggestions are welcome. Thanks again for offering.

**Comment by unclechu** [comment]
@davidflanagan I'm just proposing different solutions. If there's possible way to produce static content during the build process (I mean no blockers such as parts which are always dynamically generated) it's even better because no other layer waste resources and result is delivered to a user as fast as possible.

In this case we just need to write some js script that will produce rendered result or by itself save it to a file(s) as some templates or something like that, I'll look at your repo soon and see what I can do.

**Comment by davidflanagan** [comment]
SSR is working now; this story is no longer needed.

**Comment by blikblum** [comment]
Hi @davidflanagan

Can you share data showing the impact of SSR on page load times?
