### ISSUE TITLE
 w3c documentation on csp2 suggests to use child-src over frame-src - mdn says exactly the opposite

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#998]
Cross-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1513001

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src

https://www.w3.org/TR/CSP2/#changes-from-level-1

Here the documentation states that child-src is to be used over frame-src option. 

https://www.w3.org/TR/CSP2/#frame_src
In this section it is clearly stated that the frame-src directive is deprecated.

**Comment by wbamberg** [comment]
Thanks for filing! I've moved the "deprecated" notices for [child-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src) to [frame-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src).

@sideshowbarker, since [you added the "deprecated" notice to `child-src`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src$compare?locale=en-US&to=1268529&from=1254769), I'd be happy if you could confirm that this is correct or if I'm missing something here. Thanks!

**Comment by sideshowbarker** [comment]
So in the current CSP spec at https://w3c.github.io/webappsec-csp/#changes-from-level-2, neithe child-src nor frame-src is deprecated any longer:

https://w3c.github.io/webappsec-csp/#changes-from-level-2

> The `frame-src` directive, which was deprecated in CSP Level 2, has been undeprecated, but continues to defer to `child-src` if not present (which defers to `default-src` in turn).

Given that, I’ve removed the "deprecated" notice from https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src

I also raised https://github.com/mdn/browser-compat-data/pull/3635 to get BCD updated.

(The only directive that’s now still deprecated in the CSP spec is the `report-uri` directive.)

**Comment by wbamberg** [comment]
OK, given that I think we can close this bug.
